auxiliary_functions.hpp
constexpr sign_e NumRepr::Char2Sign(char ch) noexcept
References NumRepr::vminus, NumRepr::vplus.
constexpr sign_e NumRepr::Int2Sign(IntT nu) noexcept
References NumRepr::vminus, NumRepr::vplus.
constexpr sign_funct_e NumRepr::Int2SignFunct(IntT nu) noexcept
References NumRepr::vminus, NumRepr::vplus, NumRepr::vzero.
constexpr sign_funct_e NumRepr::Nat2SignFunct(NatIntT nu) noexcept
References NumRepr::vplus, NumRepr::vzero.
constexpr size_t NumRepr::detail::ceilsqrt(size_t n, size_t low, size_t high) noexcept
References NumRepr::detail::ceilsqrt.
Referenced by NumRepr::detail::ceilsqrt, NumRepr::auxiliary_functions::is_prime.
constexpr size_t NumRepr::detail::ceilsqrt(size_t n) noexcept
References NumRepr::detail::ceilsqrt.
constexpr bool NumRepr::detail::find_factor(size_t n, size_t low, size_t high) noexcept
References NumRepr::detail::find_factor.
Referenced by NumRepr::detail::find_factor, NumRepr::auxiliary_functions::is_prime.
constexpr bool NumRepr::auxiliary_functions::is_prime(size_t n) noexcept
References NumRepr::detail::ceilsqrt, NumRepr::detail::find_factor.
Referenced by NumRepr::dig_t< UINT_T, B >::is_prime.
constexpr bool NumRepr::auxiliary_functions::is_power_of_2(uint128_t num) noexcept
References NumRepr::auxiliary_functions::is_power_of_2.
Referenced by NumRepr::auxiliary_functions::is_power_of_2.