basic_types.hpp
using chint = char
NUEVOS NOMBRES PARA LOS ENTEROS O PARECIDOS.
using schint = signed char
using ssint = signed short int
using sint = signed int
using slint = signed long int
using sllint = signed long long int
using uchint = unsigned char
using usint = unsigned short int
using uint = unsigned int
using ulint = unsigned long int
using ullint = unsigned long long int
using uint128_t = __uint128_t
using sint128_t = __int128_t
using size_t = std::size_t
using sint8_t = std::int8_t
using sint16_t = std::int16_t
using sint32_t = std::int32_t
using sint64_t = std::int64_t
using uint8_t = std::uint8_t
using uint16_t = std::uint16_t
using uint32_t = std::uint32_t
using uint64_t = std::uint64_t
using NumRepr::type_traits::sig_UInt_for_UInt_t = typedef typename detail::__sig_UInt_for_UInt_t<UInt_t>::type
using NumRepr::type_traits::sig_SInt_for_UInt_t = typedef typename detail::__sig_SInt_for_UInt_t<UInt_t>::type
using NumRepr::type_traits::sig_UInt_for_SInt_t = typedef typename detail::__sig_UInt_for_SInt_t<SInt_t>::type
METAFUNCION : DA EL SIGUIENTE TIPO ENTERO PARA EL ACTUAL TIPO ENTERO POR ESPCECIALIZACION EXPLICITA
using NumRepr::type_traits::sig_SInt_for_SInt_t = typedef typename detail::__sig_SInt_for_SInt_t<SInt_t>::type
METAFUNCIONES PARA DAR CON LOS MAXIMOS NUMEROS QUE CABEN EN UN TIPO Y SIMILARES
using NumRepr::type_traits::UIntTypeForRadix_t = typedef typename UIntTypeForRadix<Type,Radix>::UIntType
DEFINICION PARA ESPECIALIZACION TYPE_TRAITS::UINTTYPEFORRADIX UNSIGNED POSIBLY RADIX NON VALID
using NumRepr::type_traits::TypeFromIntNumber_t = typedef UIntTypeForRadix_t<decltype(Radix),Radix>
constexpr CharT NumRepr::nullchar
constexpr bool NumRepr::type_traits::has_the_same_size
constexpr bool NumRepr::type_traits::is_unsigned_sz_gt_v
constexpr bool NumRepr::type_traits::is_unsigned_sz_geqt_v
constexpr bool NumRepr::type_traits::is_signed_sz_gt_v
constexpr bool NumRepr::type_traits::is_signed_sz_geqt_v
constexpr bool NumRepr::type_traits::is_sz_gt_v
constexpr bool NumRepr::type_traits::is_sz_geqt_v
METAFUNCION : DA EL SIGUIENTE TIPO NATURAL PARA EL ACTUAL TIPO NATURAL POR ESPECIALIZACION EXPLICITA
char * NumRepr::clear_ccad(char *, usint)
Referenced by NumRepr::devCadenaC.
constexpr const char * NumRepr::devCadenaC(T< B > arg, std::size_t long_ccad=64) noexcept
References NumRepr::clear_ccad.
constexpr char * NumRepr::clear_ccad(char *cad_c, std::size_t long_de_cad_c) noexcept
constexpr unsigned long long NumRepr::atoull(char *text) noexcept
consteval UINT_T NumRepr::type_traits::maxbase()
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::assign, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator Int_Type.
consteval UINT_T NumRepr::type_traits::submaxbase()
consteval UINT_T NumRepr::type_traits::minbase()
consteval UINT_T NumRepr::type_traits::subminbase()
consteval UINT_T NumRepr::type_traits::monobase()
consteval UINT_T NumRepr::type_traits::nobase()
consteval UINT_T NumRepr::type_traits::maxdigit()
consteval UINT_T NumRepr::type_traits::submaxdigit()
consteval UINT_T NumRepr::type_traits::digit_0()
consteval UINT_T NumRepr::type_traits::digit_1()
consteval UINT_T NumRepr::type_traits::base_2()
consteval bool NumRepr::type_traits::base_geqt_2()
consteval bool NumRepr::type_traits::base_leqt_max()
consteval bool NumRepr::type_traits::suitable_base()
consteval UINT_T NumRepr::type_traits::middle_max()
consteval UINT_T NumRepr::type_traits::sqrt_max()
DECLARACION DE UN TYPE_TRAITS PARA LITERALES INTEGRALES NOVALIDOS.
QUEREMOS FABRICAR LA METAFUNCION TypeFromIntNumber_t<numero_sin_signo> QUE DEVUELVA EL TIPO ENTERO SIN SIGNO MAS PEQUENO PARA EL NUMERO numero_sin_signo
static constexpr std::array< T_head, n_head+n_tail_head+(...+(n_tail_tail))> && NumRepr::concatenate_arrays(std::array< T_head, n_head > &&arg_head, std::array< T_tail_head, n_tail_head > &&arg_tail_head, std::array< T_tail_tail, n_tail_tail > &&... arg_tail_tail) noexcept
< CONCATENACION DE ARRAYS HOMOGENEOS DEFINICION GENERAL PARA 3+* ARRAYS DE LONGITUDES n_head Y n_tail_head Y ... n_tail_tail CONCATENACION DE ARRAYS HOMOGENEOS DEFINICION PARA 2 ARRAYS DE LONGITUDES T_1 Y T_0
static constexpr std::array< T_0, n_1+n_0 > && NumRepr::concatenate_arrays(std::array< T_1, n_1 > &&arg_l, std::array< T_0, n_0 > &&arg_r) noexcept