nat_num_t
using nat_num_t< UINT_T, B >::dig_t = dig_t<UINT_T,B>
using nat_num_t< UINT_T, B >::base_num_t = base_num_t<UINT_T,B>
using nat_num_t< UINT_T, B >::nbstr = basic_string< dig >
using nat_num_t< UINT_T, B >::striterator = typename nbstr::iterator
using nat_num_t< UINT_T, B >::rstriterator = typename nbstr::reverse_iterator
using nat_num_t< UINT_T, B >::cstriterator = typename nbstr::const_iterator
using nat_num_t< UINT_T, B >::crstriterator = typename nbstr::const_reverse_iterator
using nat_num_t< UINT_T, B >::b_iterator = typename base_num_t<UINT_T,B>::iterator
using nat_num_t< UINT_T, B >::b_riterator = typename base_num_t<UINT_T,B>::reverse_iterator
using nat_num_t< UINT_T, B >::b_citerator = typename base_num_t<UINT_T,B>::const_iterator
using nat_num_t< UINT_T, B >::b_criterator = typename base_num_t<UINT_T,B>::const_reverse_iterator
using nat_num_t< UINT_T, B >::iterator = typename nat_num_t<UINT_T,B>::iterator
using nat_num_t< UINT_T, B >::riterator = typename nat_num_t<UINT_T,B>::reverse_iterator
using nat_num_t< UINT_T, B >::citerator = typename nat_num_t<UINT_T,B>::const_iterator
using nat_num_t< UINT_T, B >::criterator = typename nat_num_t<UINT_T,B>::const_reverse_iterator
using nat_num_t< UINT_T, B >::base_N_t = std::array<dig_t<UINT_T,B>,N>
using nat_num_t< UINT_T, B >::base_t = nat_reg_N_digs_t<UINT_T,B,2>
using nat_num_t< UINT_T, B >::nat_reg_N_digs_t = nat_reg_N_digs_t<UINT_T,B,N>
using nat_num_t< UINT_T, B >::nat_reg_digs_t = nat_reg_N_digs_t<UINT_T,B,2>
using nat_num_t< UINT_T, B >::int_reg_N_digs_t = int_reg_N_digs_t<UINT_T,B,N>
using nat_num_t< UINT_T, B >::int_reg_digs_t = int_reg_N_digs_t<UINT_T,B,2>
pardigs nat_num_t< UINT_T, B >::aux
size_t nat_num_t< UINT_T, B >::size() const
Referenced by nat_num_t< UINT_T, B >::ceros_a_la_drcha, nat_num_t< UINT_T, B >::ceros_a_la_izqda, nat_num_t< UINT_T, B >::div2, nat_num_t< UINT_T, B >::es_cero, nat_num_t< UINT_T, B >::EuclidDiv, nat_num_t< UINT_T, B >::m_div2, nat_num_t< UINT_T, B >::m_EuclidDiv, nat_num_t< UINT_T, B >::m_rem2, nat_num_t< UINT_T, B >::minus, nat_num_t< UINT_T, B >::nat_num_t, nat_num_t< UINT_T, B >::no_es_cero, nat_num_t< UINT_T, B >::operator uchint, nat_num_t< UINT_T, B >::operator uint, nat_num_t< UINT_T, B >::operator ulint, nat_num_t< UINT_T, B >::operator ullint, nat_num_t< UINT_T, B >::operator usint, nat_num_t< UINT_T, B >::operator vector< dig >, nat_num_t< UINT_T, B >::operator!=, nat_num_t< UINT_T, B >::operator*, nat_num_t< UINT_T, B >::operator*=, nat_num_t< UINT_T, B >::operator+, nat_num_t< UINT_T, B >::operator+=, nat_num_t< UINT_T, B >::operator-, nat_num_t< UINT_T, B >::operator-=, nat_num_t< UINT_T, B >::operator/, nat_num_t< UINT_T, B >::operator/=, nat_num_t< UINT_T, B >::operator<, operator<<, nat_num_t< UINT_T, B >::operator<=, nat_num_t< UINT_T, B >::operator=, nat_num_t< UINT_T, B >::operator==, nat_num_t< UINT_T, B >::operator>, nat_num_t< UINT_T, B >::operator>=, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::reduce_fracc, nat_num_t< UINT_T, B >::rem2, nat_num_t< UINT_T, B >::remBm1.
void nat_num_t< UINT_T, B >::push_front(dig_t parg)
Referenced by nat_num_t< UINT_T, B >::mC_B, nat_num_t< UINT_T, B >::minus, nat_num_t< UINT_T, B >::nat_num_t, nat_num_t< UINT_T, B >::operator*, nat_num_t< UINT_T, B >::operator*=, nat_num_t< UINT_T, B >::operator+, nat_num_t< UINT_T, B >::operator+=, nat_num_t< UINT_T, B >::operator-, nat_num_t< UINT_T, B >::operator=.
dig_t nat_num_t< UINT_T, B >::operator[](uint arg) const
dig_t & nat_num_t< UINT_T, B >::operator[](uint arg)
void nat_num_t< UINT_T, B >::clear()
Referenced by nat_num_t< UINT_T, B >::nat_num_t, nat_num_t< UINT_T, B >::operator=, operator>>.
void nat_num_t< UINT_T, B >::push_back(dig_t arg)
Referenced by nat_num_t< UINT_T, B >::nat_num_t, nat_num_t< UINT_T, B >::operator*, nat_num_t< UINT_T, B >::operator*=, nat_num_t< UINT_T, B >::operator=, operator>>.
striterator nat_num_t< UINT_T, B >::begin()
Referenced by nat_num_t< UINT_T, B >::mC_Bm1, nat_num_t< UINT_T, B >::operator!.
cstriterator nat_num_t< UINT_T, B >::end() const
Referenced by nat_num_t< UINT_T, B >::mC_Bm1, nat_num_t< UINT_T, B >::operator!.
nat_num_t< UINT_T, B >::nat_num_t()
Referenced by nat_num_t< UINT_T, B >::operator-, nat_num_t< UINT_T, B >::operator-=, nat_num_t< UINT_T, B >::operator/, nat_num_t< UINT_T, B >::operator/=, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::reduce_fracc.
const nat_num_t & nat_num_t< UINT_T, B >::operator=(const nat_num_t &a)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t & nat_num_t< UINT_T, B >::operator=(nat_num_t &a)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t< UINT_T, B >::nat_num_t(const nat_num_t &a)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t< UINT_T, B >::nat_num_t(const string &a)
References nat_num_t< UINT_T, B >::clear.
const nat_num_t & nat_num_t< UINT_T, B >::operator=(const string &a)
References nat_num_t< UINT_T, B >::clear.
nat_num_t< UINT_T, B >::operator string() const
nat_num_t< UINT_T, B >::nat_num_t(dig a0)
References nat_num_t< UINT_T, B >::clear.
const nat_num_t & nat_num_t< UINT_T, B >::operator=(const dig &a0)
References nat_num_t< UINT_T, B >::clear.
nat_num_t< UINT_T, B >::nat_num_t(const dig &a1, const dig &a0)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::reduce.
nat_num_t< UINT_T, B >::nat_num_t(const dig &a2, const dig &a1, const dig &a0)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::reduce.
nat_num_t< UINT_T, B >::nat_num_t(const vector< dig > &arg)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::push_back, nat_num_t< UINT_T, B >::reduce.
const nat_num_t & nat_num_t< UINT_T, B >::operator=(const vector< dig > &arg)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::push_back, nat_num_t< UINT_T, B >::reduce.
nat_num_t< UINT_T, B >::operator vector< dig >() const
References nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t< UINT_T, B >::nat_num_t(const pardigs &a)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::reduce.
const nat_num_t & nat_num_t< UINT_T, B >::operator=(const pardigs &a)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::reduce.
nat_num_t< UINT_T, B >::nat_num_t(const n2digs &a)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::reduce.
const nat_num_t & nat_num_t< UINT_T, B >::operator=(const n2digs &a)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::reduce.
nat_num_t< UINT_T, B >::nat_num_t(char ch)
References nat_num_t< UINT_T, B >::clear.
const nat_num_t & nat_num_t< UINT_T, B >::operator=(char ch)
References nat_num_t< UINT_T, B >::clear.
nat_num_t< UINT_T, B >::nat_num_t(uchint a)
References nat_num_t< UINT_T, B >::clear.
const nat_num_t & nat_num_t< UINT_T, B >::operator=(uchint a)
References nat_num_t< UINT_T, B >::clear.
nat_num_t< UINT_T, B >::nat_num_t(usint a)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::push_front.
const nat_num_t & nat_num_t< UINT_T, B >::operator=(usint a)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::push_front.
nat_num_t< UINT_T, B >::nat_num_t(uint a)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::push_front.
const nat_num_t & nat_num_t< UINT_T, B >::operator=(uint a)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::push_front.
nat_num_t< UINT_T, B >::nat_num_t(ulint a)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::push_front.
const nat_num_t & nat_num_t< UINT_T, B >::operator=(ulint a)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::push_front.
nat_num_t< UINT_T, B >::nat_num_t(ullint a)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::push_front.
const nat_num_t & nat_num_t< UINT_T, B >::operator=(ullint a)
References nat_num_t< UINT_T, B >::clear, nat_num_t< UINT_T, B >::push_front.
nat_num_t< UINT_T, B >::operator uint() const
References nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t< UINT_T, B >::operator usint() const
References nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t< UINT_T, B >::operator uchint() const
References nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t< UINT_T, B >::operator ulint() const
References nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t< UINT_T, B >::operator ullint() const
References nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t & nat_num_t< UINT_T, B >::operator=(dig a0)
References nat_num_t< UINT_T, B >::clear.
usint nat_num_t< UINT_T, B >::ceros_a_la_izqda() const
References nat_num_t< UINT_T, B >::size.
Referenced by nat_num_t< UINT_T, B >::digs_no_significativos, nat_num_t< UINT_T, B >::operator!=, nat_num_t< UINT_T, B >::operator<, nat_num_t< UINT_T, B >::operator<=, nat_num_t< UINT_T, B >::operator==, nat_num_t< UINT_T, B >::operator>, nat_num_t< UINT_T, B >::operator>=.
size_t nat_num_t< UINT_T, B >::ceros_a_la_drcha() const
References nat_num_t< UINT_T, B >::size.
Referenced by nat_num_t< UINT_T, B >::digs_fracc_no_significativos, nat_num_t< UINT_T, B >::EuclidDiv, nat_num_t< UINT_T, B >::m_EuclidDiv, nat_num_t< UINT_T, B >::operator/, nat_num_t< UINT_T, B >::operator/=.
usint nat_num_t< UINT_T, B >::digs_no_significativos() const
References nat_num_t< UINT_T, B >::ceros_a_la_izqda.
Referenced by nat_num_t< UINT_T, B >::reduce.
usint nat_num_t< UINT_T, B >::digs_fracc_no_significativos() const
References nat_num_t< UINT_T, B >::ceros_a_la_drcha.
Referenced by nat_num_t< UINT_T, B >::reduce_fracc.
bool nat_num_t< UINT_T, B >::operator==(const nat_num_t &arg) const
References nat_num_t< UINT_T, B >::ceros_a_la_izqda, nat_num_t< UINT_T, B >::size.
bool nat_num_t< UINT_T, B >::operator!=(const nat_num_t &arg) const
References nat_num_t< UINT_T, B >::ceros_a_la_izqda, nat_num_t< UINT_T, B >::size.
bool nat_num_t< UINT_T, B >::operator>=(const nat_num_t &arg) const
References nat_num_t< UINT_T, B >::ceros_a_la_izqda, nat_num_t< UINT_T, B >::size.
bool nat_num_t< UINT_T, B >::operator<=(const nat_num_t &arg) const
References nat_num_t< UINT_T, B >::ceros_a_la_izqda, nat_num_t< UINT_T, B >::size.
bool nat_num_t< UINT_T, B >::operator>(const nat_num_t &arg) const
References nat_num_t< UINT_T, B >::ceros_a_la_izqda, nat_num_t< UINT_T, B >::size.
bool nat_num_t< UINT_T, B >::operator<(const nat_num_t &arg) const
References nat_num_t< UINT_T, B >::ceros_a_la_izqda, nat_num_t< UINT_T, B >::size.
nat_num_t nat_num_t< UINT_T, B >::operator+(const nat_num_t &arg) const
References nat_num_t< UINT_T, B >::push_front, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t nat_num_t< UINT_T, B >::operator-(const nat_num_t &arg) const
References nat_num_t< UINT_T, B >::minus, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t nat_num_t< UINT_T, B >::operator*(const nat_num_t &arg) const
References nat_num_t< UINT_T, B >::push_back, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t nat_num_t< UINT_T, B >::operator/(const nat_num_t &arg) const
References nat_num_t< UINT_T, B >::ceros_a_la_drcha, nat_num_t< UINT_T, B >::nat_num_t, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t nat_num_t< UINT_T, B >::operator%(const nat_num_t &arg) const
References nat_num_t< UINT_T, B >::reduce.
nat_num_t nat_num_t< UINT_T, B >::operator*(pardigs a) const
References nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t nat_num_t< UINT_T, B >::operator+(dig arg) const
References nat_num_t< UINT_T, B >::push_front, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t nat_num_t< UINT_T, B >::operator-(dig arg) const
References nat_num_t< UINT_T, B >::minus, nat_num_t< UINT_T, B >::nat_num_t, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t nat_num_t< UINT_T, B >::operator*(dig a) const
References nat_num_t< UINT_T, B >::push_front, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
const nat_num_t & nat_num_t< UINT_T, B >::operator+=(const nat_num_t &arg)
References nat_num_t< UINT_T, B >::push_front, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
const nat_num_t & nat_num_t< UINT_T, B >::operator-=(const nat_num_t &arg)
References nat_num_t< UINT_T, B >::minus, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
const nat_num_t & nat_num_t< UINT_T, B >::operator*=(const nat_num_t &arg)
References nat_num_t< UINT_T, B >::push_back, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t nat_num_t< UINT_T, B >::substr(size_t pos, size_t n) const
Referenced by nat_num_t< UINT_T, B >::div2, nat_num_t< UINT_T, B >::EuclidDiv, nat_num_t< UINT_T, B >::m_div2, nat_num_t< UINT_T, B >::m_EuclidDiv.
const nat_num_t & nat_num_t< UINT_T, B >::operator/=(const nat_num_t &arg)
References nat_num_t< UINT_T, B >::ceros_a_la_drcha, nat_num_t< UINT_T, B >::nat_num_t, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
const nat_num_t & nat_num_t< UINT_T, B >::operator%=(const nat_num_t &arg)
References nat_num_t< UINT_T, B >::reduce.
const nat_num_t & nat_num_t< UINT_T, B >::operator*=(pardigs a)
References nat_num_t< UINT_T, B >::push_back, nat_num_t< UINT_T, B >::reduce.
const nat_num_t & nat_num_t< UINT_T, B >::operator+=(dig arg)
References nat_num_t< UINT_T, B >::push_front, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
const nat_num_t & nat_num_t< UINT_T, B >::operator-=(dig arg)
References nat_num_t< UINT_T, B >::minus, nat_num_t< UINT_T, B >::nat_num_t, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
const nat_num_t & nat_num_t< UINT_T, B >::operator*=(dig arg)
References nat_num_t< UINT_T, B >::push_front, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
nat_num_t nat_num_t< UINT_T, B >::operator-() const
References nat_num_t< UINT_T, B >::push_front, nat_num_t< UINT_T, B >::reduce.
nat_num_t nat_num_t< UINT_T, B >::minus(size_t sz) const
References nat_num_t< UINT_T, B >::push_front, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
Referenced by nat_num_t< UINT_T, B >::operator-, nat_num_t< UINT_T, B >::operator-=.
nat_num_t nat_num_t< UINT_T, B >::operator!() const
References nat_num_t< UINT_T, B >::begin, nat_num_t< UINT_T, B >::end, nat_num_t< UINT_T, B >::reduce.
const nat_num_t & nat_num_t< UINT_T, B >::mC_B()
References nat_num_t< UINT_T, B >::push_front, nat_num_t< UINT_T, B >::reduce.
const nat_num_t & nat_num_t< UINT_T, B >::mC_Bm1()
References nat_num_t< UINT_T, B >::begin, nat_num_t< UINT_T, B >::end, nat_num_t< UINT_T, B >::reduce.
nat_num_t nat_num_t< UINT_T, B >::abs() const
Referenced by nat_num_t< UINT_T, B >::div2, nat_num_t< UINT_T, B >::EuclidDiv, nat_num_t< UINT_T, B >::m_EuclidDiv, nat_num_t< UINT_T, B >::remBm1.
const nat_num_t & nat_num_t< UINT_T, B >::m_abs()
Referenced by nat_num_t< UINT_T, B >::divB.
nat_num_t nat_num_t< UINT_T, B >::divB() const
References nat_num_t< UINT_T, B >::m_abs, nat_num_t< UINT_T, B >::reduce.
dig nat_num_t< UINT_T, B >::remB() const
References nat_num_t< UINT_T, B >::reduce.
const nat_num_t & nat_num_t< UINT_T, B >::m_divB()
References nat_num_t< UINT_T, B >::reduce.
dig nat_num_t< UINT_T, B >::m_remB()
References nat_num_t< UINT_T, B >::reduce.
nat_num_t nat_num_t< UINT_T, B >::div2() const
References nat_num_t< UINT_T, B >::abs, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size, nat_num_t< UINT_T, B >::substr.
dig nat_num_t< UINT_T, B >::rem2() const
References nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
const nat_num_t & nat_num_t< UINT_T, B >::m_div2()
References nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size, nat_num_t< UINT_T, B >::substr.
dig nat_num_t< UINT_T, B >::m_rem2()
References nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
dig nat_num_t< UINT_T, B >::remBm1() const
References nat_num_t< UINT_T, B >::abs, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::size.
pardigs nat_num_t< UINT_T, B >::g_aux() const
void nat_num_t< UINT_T, B >::p_aux(pardigs arg)
Referenced by operator>>.
bool nat_num_t< UINT_T, B >::es_cero() const
References nat_num_t< UINT_T, B >::size.
bool nat_num_t< UINT_T, B >::no_es_cero() const
References nat_num_t< UINT_T, B >::size.
pair< nat_num_t, nat_num_t > nat_num_t< UINT_T, B >::EuclidDiv(const nat_num_t &arg) const
References nat_num_t< UINT_T, B >::abs, nat_num_t< UINT_T, B >::ceros_a_la_drcha, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::reduce_fracc, nat_num_t< UINT_T, B >::size, nat_num_t< UINT_T, B >::substr.
pair< nat_num_t, const nat_num_t & > nat_num_t< UINT_T, B >::m_EuclidDiv(const nat_num_t &arg)
References nat_num_t< UINT_T, B >::abs, nat_num_t< UINT_T, B >::ceros_a_la_drcha, nat_num_t< UINT_T, B >::reduce, nat_num_t< UINT_T, B >::reduce_fracc, nat_num_t< UINT_T, B >::size, nat_num_t< UINT_T, B >::substr.
const nat_num_t & nat_num_t< UINT_T, B >::operator++()
nat_num_t nat_num_t< UINT_T, B >::operator++(int)
const nat_num_t & nat_num_t< UINT_T, B >::operator--()
nat_num_t nat_num_t< UINT_T, B >::operator--(int)
const nat_num_t & nat_num_t< UINT_T, B >::reduce()
References nat_num_t< UINT_T, B >::digs_no_significativos, nat_num_t< UINT_T, B >::nat_num_t, nat_num_t< UINT_T, B >::size.
Referenced by nat_num_t< UINT_T, B >::div2, nat_num_t< UINT_T, B >::divB, nat_num_t< UINT_T, B >::EuclidDiv, nat_num_t< UINT_T, B >::m_div2, nat_num_t< UINT_T, B >::m_divB, nat_num_t< UINT_T, B >::m_EuclidDiv, nat_num_t< UINT_T, B >::m_rem2, nat_num_t< UINT_T, B >::m_remB, nat_num_t< UINT_T, B >::mC_B, nat_num_t< UINT_T, B >::mC_Bm1, nat_num_t< UINT_T, B >::minus, nat_num_t< UINT_T, B >::nat_num_t, nat_num_t< UINT_T, B >::operator uchint, nat_num_t< UINT_T, B >::operator uint, nat_num_t< UINT_T, B >::operator ulint, nat_num_t< UINT_T, B >::operator ullint, nat_num_t< UINT_T, B >::operator usint, nat_num_t< UINT_T, B >::operator vector< dig >, nat_num_t< UINT_T, B >::operator!, nat_num_t< UINT_T, B >::operator%, nat_num_t< UINT_T, B >::operator%=, nat_num_t< UINT_T, B >::operator*, nat_num_t< UINT_T, B >::operator*=, nat_num_t< UINT_T, B >::operator+, nat_num_t< UINT_T, B >::operator+=, nat_num_t< UINT_T, B >::operator-, nat_num_t< UINT_T, B >::operator-=, nat_num_t< UINT_T, B >::operator/, nat_num_t< UINT_T, B >::operator/=, nat_num_t< UINT_T, B >::operator=, nat_num_t< UINT_T, B >::rem2, nat_num_t< UINT_T, B >::remB, nat_num_t< UINT_T, B >::remBm1.
nat_num_t nat_num_t< UINT_T, B >::reduce() const
References nat_num_t< UINT_T, B >::digs_no_significativos, nat_num_t< UINT_T, B >::nat_num_t, nat_num_t< UINT_T, B >::size.
const nat_num_t & nat_num_t< UINT_T, B >::reduce_fracc()
References nat_num_t< UINT_T, B >::digs_fracc_no_significativos, nat_num_t< UINT_T, B >::nat_num_t, nat_num_t< UINT_T, B >::size.
Referenced by nat_num_t< UINT_T, B >::EuclidDiv, nat_num_t< UINT_T, B >::m_EuclidDiv.
nat_num_t nat_num_t< UINT_T, B >::reduce_fracc() const
References nat_num_t< UINT_T, B >::digs_fracc_no_significativos, nat_num_t< UINT_T, B >::nat_num_t, nat_num_t< UINT_T, B >::size.
void nat_num_t< UINT_T, B >::resize(size_t arg)
nat_num_t & nat_num_t< UINT_T, B >::insert(size_t pos1, const dig_t chardig)
nat_num_t & nat_num_t< UINT_T, B >::insert(size_t pos1, size_t n, dig_t c)
const nat_num_t & nat_num_t< UINT_T, B >::operator&=(const nat_num_t &arg)
nat_num_t & nat_num_t< UINT_T, B >::erase(size_t pos, size_t npos)
iterator nat_num_t< UINT_T, B >::erase(iterator first, iterator last)
void nat_num_t< UINT_T, B >::div_gen_step(const nat_num_t &dvsor, nat_num_t &rem, nat_num_t &coc, usint &ndig) const
void nat_num_t< UINT_T, B >::div_uno(nat_num_t &rem, nat_num_t &dvndo, nat_num_t &dvsor, const usint szndo, const usint szsor) const