func_refvar_t
vector< vector<bool> > func_refvar_t< aT, T >::mapmem
Referenced by func_refvar_t< aT, T >::borra_var, func_refvar_t< INT **, INT *, INT >::borra_var, func_refvar_t< UINT **, UINT *, UINT >::borra_var, func_refvar_t< aT, T >::existe_lugar_de_base, func_refvar_t< INT **, INT *, INT >::existe_lugar_de_base, func_refvar_t< UINT **, UINT *, UINT >::existe_lugar_de_base, func_refvar_t< aT, T >::func_refvar_t, func_refvar_t< INT **, INT *, INT >::func_refvar_t, func_refvar_t< UINT **, UINT *, UINT >::func_refvar_t, func_refvar_t< aT, T >::insert, func_refvar_t< INT **, INT *, INT >::insert, func_refvar_t< UINT **, UINT *, UINT >::insert.
map< string , par_dir_t > func_refvar_t< aT, T >::mapvd
Referenced by func_refvar_t< aT, T >::borra_var, func_refvar_t< INT **, INT *, INT >::borra_var, func_refvar_t< UINT **, UINT *, UINT >::borra_var, func_refvar_t< aT, T >::este_nombre_ya_ha_sido_declarado, func_refvar_t< INT **, INT *, INT >::este_nombre_ya_ha_sido_declarado, func_refvar_t< UINT **, UINT *, UINT >::este_nombre_ya_ha_sido_declarado, func_refvar_t< aT, T >::get, func_refvar_t< INT **, INT *, INT >::get, func_refvar_t< UINT **, UINT *, UINT >::get, func_refvar_t< aT, T >::insert, func_refvar_t< INT **, INT *, INT >::insert, func_refvar_t< UINT **, UINT *, UINT >::insert, func_refvar_t< aT, T >::operator(), func_refvar_t< INT **, INT *, INT >::operator(), func_refvar_t< UINT **, UINT *, UINT >::operator().
aT** func_refvar_t< aT, T >::matd
Referenced by func_refvar_t< aT, T >::func_refvar_t, func_refvar_t< INT **, INT *, INT >::func_refvar_t, func_refvar_t< UINT **, UINT *, UINT >::func_refvar_t, func_refvar_t< aT, T >::get, func_refvar_t< INT **, INT *, INT >::get, func_refvar_t< UINT **, UINT *, UINT >::get, func_refvar_t< aT, T >::operator(), func_refvar_t< UINT **, UINT *, UINT >::operator(), func_refvar_t< aT, T >::~func_refvar_t, func_refvar_t< INT **, INT *, INT >::~func_refvar_t, func_refvar_t< UINT **, UINT *, UINT >::~func_refvar_t.
vector<uint> func_refvar_t< aT, T >::cuentavars
Referenced by func_refvar_t< aT, T >::borra_var, func_refvar_t< INT **, INT *, INT >::borra_var, func_refvar_t< UINT **, UINT *, UINT >::borra_var, func_refvar_t< aT, T >::escribe_var, func_refvar_t< INT **, INT *, INT >::escribe_var, func_refvar_t< UINT **, UINT *, UINT >::escribe_var, func_refvar_t< aT, T >::func_refvar_t, func_refvar_t< INT **, INT *, INT >::func_refvar_t, func_refvar_t< UINT **, UINT *, UINT >::func_refvar_t.
bool func_refvar_t< aT, T >::insert(string nombre, uchint base, uchint var_base)
References func_refvar_t< aT, T >::mapmem, func_refvar_t< aT, T >::mapvd.
Referenced by func_refvar_t< aT, T >::escribe_var, func_refvar_t< INT **, INT *, INT >::escribe_var, func_refvar_t< UINT **, UINT *, UINT >::escribe_var.
func_refvar_t< aT, T >::func_refvar_t(const func_refvar_t &)
bool func_refvar_t< aT, T >::escribe_var(string nombre, uchint base, uchint var_base)
References func_refvar_t< aT, T >::cuentavars, func_refvar_t< aT, T >::insert.
func_refvar_t< aT, T >::func_refvar_t()
References func_refvar_t< aT, T >::cuentavars, func_refvar_t< aT, T >::mapmem, func_refvar_t< aT, T >::matd.
func_refvar_t< aT, T >::~func_refvar_t()
References func_refvar_t< aT, T >::matd.
void func_refvar_t< aT, T >::borra_var(string nombre)
References func_refvar_t< aT, T >::cuentavars, func_refvar_t< aT, T >::mapmem, func_refvar_t< aT, T >::mapvd.
bool func_refvar_t< aT, T >::existe_lugar_de_base(uchint Base)
References func_refvar_t< aT, T >::mapmem.
bool func_refvar_t< aT, T >::este_nombre_ya_ha_sido_declarado(string nombre)
References func_refvar_t< aT, T >::mapvd.
Referenced by func_refvar_t< aT, T >::operator(), func_refvar_t< INT **, INT *, INT >::operator(), func_refvar_t< UINT **, UINT *, UINT >::operator().
T< B > func_refvar_t< aT, T >::get(string nombre)
References func_refvar_t< aT, T >::mapvd, func_refvar_t< aT, T >::matd.
bool func_refvar_t< aT, T >::operator()(string nombre, string lhs)
References func_refvar_t< aT, T >::este_nombre_ya_ha_sido_declarado, func_refvar_t< aT, T >::mapvd, func_refvar_t< aT, T >::matd.