dig_t.hpp
using NumRepr::digit_t = typedef dig_t< type_traits::TypeFromIntNumber_t<B>, static_cast<type_traits::TypeFromIntNumber_t<B> >(B) >
SOLO HAY QUE DECLARAR digit_t<2> o digit_t<10> o ...
consteval UINT_T NumRepr::ui_1() noexcept
Referenced by NumRepr::dig_t< UINT_T, B >::is_0_divisor, NumRepr::dig_t< UINT_T, B >::is_0or1, NumRepr::dig_t< UINT_T, B >::is_1, NumRepr::dig_t< UINT_T, B >::is_not_1, NumRepr::dig_t< UINT_T, B >::is_unit, NumRepr::dig_t< UINT_T, B >::operator++, NumRepr::dig_t< UINT_T, B >::operator--.
consteval dig_t< UINT_T, B > NumRepr::dig_max() noexcept
DEFINCION DE template<uint128_t Radix> digito_t{};.
Referenced by NumRepr::dig_t< UINT_T, B >::mult_inv.
std::istream & NumRepr::operator>>(std::istream &is, dig_t< UINT_T, Base > &arg)
TODO : ESTA VERSION + VERSION CON TRATAMIENTO DE ERRORES RUNTIME
std::ostream & NumRepr::operator<<(std::ostream &os, dig_t< UINT_T, Base > arg)