NumRepr::lex
reglexst_e
sintaxerrlexst_e
semerrlexst_e
lexst_e
bool NumRepr::lex::is_digit(char)
Referenced by NumRepr::dig_t< UINT_T, B >::get_digit_token, NumRepr::dig_t< UINT_T, B >::get_radix_token.
size_t NumRepr::lex::digit_value(char)
Referenced by NumRepr::dig_t< UINT_T, B >::get_digit_token, NumRepr::dig_t< UINT_T, B >::get_radix_token.
bool NumRepr::lex::is_valid_char(char)
bool NumRepr::lex::char_value(char)
bool NumRepr::lex::is_separator(char)
Referenced by NumRepr::dig_t< UINT_T, B >::get_digit_token, NumRepr::dig_t< UINT_T, B >::get_radix_token.
bool NumRepr::lex::is_end_of_number(char)
bool NumRepr::lex::is_whitespace(char)
bool NumRepr::lex::is_end_descriptor(char)
bool NumRepr::lex::is_radix_descriptor(char)
bool NumRepr::lex::is_sign(char)
sign_e NumRepr::lex::sign_value(char)
References NumRepr::vminus, NumRepr::vplus.