NumRepr
sign_e
sign_funct_e
dig_format_e
num_type_e
nat_num_format_e
int_num_format_e
rat_num_format_e
binop_e
using NumRepr::chint_t = typedef char
NUEVOS NOMBRES PARA LOS ENTEROS O PARECIDOS.
using NumRepr::schint_t = typedef signed char
using NumRepr::ssint_t = typedef signed short int
using NumRepr::sint_t = typedef signed int
using NumRepr::slint_t = typedef signed long int
using NumRepr::sllint_t = typedef signed long long int
using NumRepr::uchint_t = typedef unsigned char
using NumRepr::usint_t = typedef unsigned short int
using NumRepr::uint_t = typedef unsigned int
using NumRepr::ulint_t = typedef unsigned long int
using NumRepr::ullint_t = typedef unsigned long long int
using NumRepr::uint128_t = typedef __uint128_t
using NumRepr::sint128_t = typedef __int128_t
using NumRepr::size_t = typedef std::size_t
using NumRepr::sint8_t = typedef std::int8_t
using NumRepr::sint16_t = typedef std::int16_t
using NumRepr::sint32_t = typedef std::int32_t
using NumRepr::sint64_t = typedef std::int64_t
using NumRepr::int8_t = typedef std::int8_t
using NumRepr::int16_t = typedef std::int16_t
using NumRepr::int32_t = typedef std::int32_t
using NumRepr::int64_t = typedef std::int64_t
using NumRepr::fast8_t = typedef std::int_fast8_t
using NumRepr::fast16_t = typedef std::int_fast16_t
using NumRepr::fast32_t = typedef std::int_fast32_t
using NumRepr::fast64_t = typedef std::int_fast64_t
using NumRepr::least8_t = typedef std::int_least8_t
using NumRepr::least16_t = typedef std::int_least16_t
using NumRepr::least32_t = typedef std::int_least32_t
using NumRepr::least64_t = typedef std::int_least64_t
using NumRepr::uint8_t = typedef std::uint8_t
using NumRepr::uint16_t = typedef std::uint16_t
using NumRepr::uint32_t = typedef std::uint32_t
using NumRepr::uint64_t = typedef std::uint64_t
using NumRepr::ufast8_t = typedef std::uint_fast8_t
using NumRepr::ufast16_t = typedef std::uint_fast16_t
using NumRepr::ufast32_t = typedef std::uint_fast32_t
using NumRepr::ufast64_t = typedef std::uint_fast64_t
using NumRepr::uleast8_t = typedef std::uint_least8_t
using NumRepr::uleast16_t = typedef std::uint_least16_t
using NumRepr::uleast32_t = typedef std::uint_least32_t
using NumRepr::uleast64_t = typedef std::uint_least64_t
using NumRepr::intmax_t = typedef std::intmax_t
using NumRepr::uintmax_t = typedef std::uintmax_t
using NumRepr::digit_t = typedef dig_t< TypeFromIntNumber_t<static_cast<uint128_t>(B)>, static_cast<TypeFromIntNumber_t<static_cast<uint128_t>(B)> >(static_cast<uint128_t>(B)) >
SOLO HAY QUE DECLARAR digit_t<2> o digit_t<10> o ...
using NumRepr::register_of_digits_t = typedef reg_digs_t< type_traits::TypeFromIntNumber_t<B>, static_cast<type_traits::TypeFromIntNumber_t<B> >(B), L >
using NumRepr::register_digs_t = typedef reg_digs_t< TypeFromIntNumber_t<static_cast<uint128_t>(B)>, static_cast<TypeFromIntNumber_t<static_cast<uint128_t>(B)> >(static_cast<uint128_t>(B)), L >
constexpr sign_e NumRepr::Char2Sign(char ch) noexcept
References vminus, vplus.
constexpr sign_e NumRepr::Int2Sign(IntT nu) noexcept
References vminus, vplus.
constexpr sign_funct_e NumRepr::Int2SignFunct(IntT nu) noexcept
References vminus, vplus, vzero.
constexpr sign_funct_e NumRepr::Nat2SignFunct(NatIntT nu) noexcept
References vplus, vzero.
constexpr ullint NumRepr::pot_max_base_B_en_Int_T() noexcept
constexpr ullint NumRepr::num_digs_max_base_B_en_Int_T() noexcept
constexpr ullint NumRepr::max_base_B_en_Int_T() noexcept
consteval UINT_T NumRepr::ui_1() noexcept
Referenced by NumRepr::dig_t< UINT_T, B >::is_0_divisor, NumRepr::dig_t< UINT_T, B >::is_0or1, NumRepr::dig_t< UINT_T, B >::is_1, NumRepr::dig_t< UINT_T, B >::is_not_1, NumRepr::dig_t< UINT_T, B >::is_unit, NumRepr::dig_t< UINT_T, B >::operator++, NumRepr::dig_t< UINT_T, B >::operator--.
consteval dig_t< UINT_T, B > NumRepr::dig_max() noexcept
DEFINCION DE template<uint128_t Radix> digito_t{};.
Referenced by NumRepr::dig_t< UINT_T, B >::mult_inv.
std::istream & NumRepr::operator>>(std::istream &is, dig_t< UINT_T, Base > &arg)
std::ostream & NumRepr::operator<<(std::ostream &os, dig_t< UINT_T, Base > arg)
std::istream & NumRepr::operator>>(std::istream &is, pfx_rat_reg_digs_t< Int_Type, Base, Length > &arg)
std::ostream & NumRepr::operator<<(std::ostream &os, const pfx_rat_reg_digs_t< Int_Type, Base, Long > &arg)
bool NumRepr::is_nat_reg_digs_type_id(std::string in)
ESPECIALIZACIONES PARA NAT_REG_DIGS.
std::string NumRepr::to_nat_reg_digs_type_string()
size_t NumRepr::size_of_nat_reg_digs_type_string_idT()
std::istream & NumRepr::operator>>(std::istream &is, nat_reg_digs_t< Int_Type, Base, Length > &arg)
TODO ESTA VERSION + VERSION CON TRATAMIENTO DE ERRORES EN RUNTIME
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_0.
std::ostream & NumRepr::operator<<(std::ostream &os, const nat_reg_digs_t< Int_Type, Base, Long > &arg)
constexpr reg_digs_t< UInt_t, B, N > NumRepr::concat(const reg_digs_t< UInt_t, B, N > &larg) noexcept
STATIC BASE_N_T<N> CONCAT(BASE_N_T<N>)
STATIC BASE_N_T<N> CONCAT(BASE_N_T<N>) STATIC BASE_N_T<N+M> CONCAT(BASE_N_T<N>,BASE_N_T<M>) STATIC BASE_N_T<N+1> CONCAT(BASE_N_T<N>,DIG_T) STATIC BASE_N_T<1+M> CONCAT(DIG_T,BASE_N_T<M>) STATIC BASE_N_T<1> CONCAT(DIG_T) STATIC BASE_N_T<1+1> CONCAT(DIG_T,DIG_T) STATIC BASE_N_T<SIZEOF...(DIG_PACK)> CONCAT(DIG_T...DIG_PACK) VARIADIC PACK
References concat.
Referenced by concat.
constexpr reg_digs_t< UInt_t, B, N+M > NumRepr::concat(const reg_digs_t< UInt_t, B, N > &larg, const reg_digs_t< UInt_t, B, M > &rarg) noexcept
STATIC BASE_N_T<N+M> CONCAT(BASE_N_T<N>,BASE_N_T<M>)
References concat.
constexpr reg_digs_t< UInt_t, B, N+1 > NumRepr::concat(const reg_digs_t< UInt_t, B, N > &larg, dig_t< UInt_t, B > rarg) noexcept
STATIC BASE_N_T<N+1> CONCAT(BASE_N_T<N>,DIG_T)
References concat.
constexpr reg_digs_t< UInt_t, B, 1+M > NumRepr::concat(dig_t< UInt_t, B > larg, const reg_digs_t< UInt_t, B, M > &rarg) noexcept
STATIC BASE_N_T<1+M> CONCAT(DIG_T,BASE_N_T<M>)
References concat.
constexpr reg_digs_t< UInt_t, B, 1 > NumRepr::concat(dig_t< UInt_t, B > larg) noexcept
STATIC BASE_N_T<1> CONCAT(DIG_T)
References concat.
constexpr reg_digs_t< UInt_t, B, 2 > NumRepr::concat(dig_t< UInt_t, B > larg, dig_t< UInt_t, B > rarg) noexcept
STATIC BASE_N_T<1+1> CONCAT(DIG_T,DIG_T)
References concat.
constexpr reg_digs_t< UInt_t, B, 1+(sizeof ...(Ts))> NumRepr::concat(T0 dig0, Ts ... dig_pack) noexcept
STATIC BASE_N_T<SIZEOF...(DIG_PACK)> CONCAT(DIG_T,DIG_T ... DIG_PACK) VARIADIC
References concat.
constexpr reg_digs_t< UInt_t, B, N+1+(sizeof ...(Ts))> NumRepr::concat(reg_digs_t< UInt_t, B, N > larg, T dig, Ts ... dig_pack) noexcept
STATIC BASE_N_T<N+1+(SIZEOF...(DIG_PACK))> CONCAT(BASE_N_T<N>,DIG_T,DIG_T ... DIG_PACK) VARIADIC
References concat.
constexpr reg_digs_t< UInt_t, B, M+1+(sizeof ...(Ts))> NumRepr::concat(T dig, Ts ... dig_pack, reg_digs_t< UInt_t, B, M > rarg) noexcept
STATIC BASE_N_T<M+1+(SIZEOF...(DIG_PACK))> CONCAT(DIG_T,DIG_T ... DIG_PACK,BASE_N_T<M>) VARIADIC
References concat.
constexpr reg_digs_t< UInt_t, B, N+(...+(N_pack))> NumRepr::concat(reg_digs_t< UInt_t, B, N > larg, reg_digs_t< UInt_t, B, N_pack > ... rarg_pack) noexcept
STATIC BASE_N_T<SIZE_T N,SIZE_T ... N_PACK> CONCAT(BASE_N_T<N> LARG,BASE_N_T<N_PACK> ... RARG_PACK) VARIADIC
References concat.
constexpr reg_digs_t< UINT_T, B, N > NumRepr::operator<<(const reg_digs_t< UINT_T, B, N > &larg, size_t n) noexcept
constexpr const reg_digs_t< UINT_T, B, N > & NumRepr::operator<<=(reg_digs_t< UINT_T, B, N > &larg, size_t n) noexcept
constexpr const reg_digs_t< UINT_T, B, N > & NumRepr::operator>>=(reg_digs_t< UINT_T, B, N > &larg, size_t n) noexcept
constexpr reg_digs_t< UINT_T, B, N > NumRepr::operator>>(const reg_digs_t< UINT_T, B, N > &larg, size_t n) noexcept
constexpr reg_digs_t< UINT_T, B, N > NumRepr::rem_B(const reg_digs_t< UINT_T, B, N > &larg, size_t n) noexcept
References rem_B.
Referenced by rem_B.
constexpr const reg_digs_t< UINT_T, B, N > & NumRepr::m_rem_B(reg_digs_t< UINT_T, B, N > &larg, size_t n) noexcept
References m_rem_B.
Referenced by m_rem_B.
constexpr reg_digs_t< UINT_T, B, N > NumRepr::mer_B(const reg_digs_t< UINT_T, B, N > &larg, size_t n) noexcept
References mer_B.
Referenced by mer_B.
constexpr const reg_digs_t< UINT_T, B, N > & NumRepr::m_mer_B(reg_digs_t< UINT_T, B, N > &larg, size_t n) noexcept
References m_mer_B.
Referenced by m_mer_B.
constexpr const reg_digs_t< UINT_T, B, N > & NumRepr::operator|=(reg_digs_t< UINT_T, B, N > &larg, const reg_digs_t< UINT_T, B, N > &rarg) noexcept
constexpr reg_digs_t< UINT_T, B, N > NumRepr::operator|(const reg_digs_t< UINT_T, B, N > &larg, const reg_digs_t< UINT_T, B, N > &rarg) noexcept
constexpr const reg_digs_t< UINT_T, B, N > & NumRepr::operator&=(reg_digs_t< UINT_T, B, N > &larg, const reg_digs_t< UINT_T, B, N > &rarg) noexcept
constexpr reg_digs_t< UINT_T, B, N > NumRepr::operator&(reg_digs_t< UINT_T, B, N > &larg, const reg_digs_t< UINT_T, B, N > &rarg) noexcept
constexpr reg_digs_t< UINT_T, B, N > NumRepr::m_incr(reg_digs_t< UINT_T, B, N > &rarg) noexcept
TODO 31/12/2022.
References m_incr, NumRepr::reg_digs_t< UINT_T, B, L >::set_0.
Referenced by aprox_units_divB, m_incr.
constexpr dig_t< UINT_T, B > NumRepr::m_sum_digs_carryin1(dig_t< UINT_T, B > &left, dig_t< UINT_T, B > right) noexcept
References NumRepr::dig_t< UINT_T, B >::C_Bm1, m_sum_digs_carryin1.
Referenced by m_sum, m_sum_digs_carryin1.
constexpr dig_t< UINT_T, B > NumRepr::m_sum_digs_carryin0(dig_t< UINT_T, B > &left, dig_t< UINT_T, B > right) noexcept
References NumRepr::dig_t< UINT_T, B >::C_Bm1, m_sum_digs_carryin0.
Referenced by m_sum, m_sum_digs_carryin0.
constexpr dig_t< UINT_T, B > NumRepr::m_sum(reg_digs_t< UINT_T, B, N > &larg, const reg_digs_t< UINT_T, B, N > &rarg) noexcept
References NumRepr::reg_digs_t< UINT_T, B, L >::C_Bm1, m_sum, m_sum_digs_carryin0, m_sum_digs_carryin1.
Referenced by m_sum.
constexpr reg_digs_t< UINT_T, B, N > NumRepr::aprox_units_divB(const reg_digs_t< UINT_T, B, N > &arg) noexcept
< PRECONDITIONS : ARG != 0 AND ARG != 1 >
FUNCIONES DE IMPLEMENTACION DE LA DIVISION ENTRE DOS REGISTROS DE DIGITOS BEGIN POSTCONDICION RET[N-1] == (DIG_1() | DIG_0()) POSTCONDICION RET[N-1] == DIG_1() => RET[N-2,0] == REGD_N_0() HAY QUE VER SI ES POTENCIA DE B : is_any_B_pow
References aprox_units_divB, m_incr.
Referenced by aprox_units_divB.
constexpr reg_digs_t< UINT_T, B, N > NumRepr::aprox_units_divB_n(const reg_digs_t< UINT_T, B, N > &arg) noexcept
FUNCION DE RECURSION PARA LA DIVISION APROX_COC_REM APROXIMA REMAINDER A 2 DIGITOS Y DIVISOR A 1 DIGITO
References aprox_units_divB_n.
Referenced by aprox_units_divB_n.
constexpr std::array< type_traits::sig_UInt_for_UInt_t< UINT_T >, 2 > NumRepr::aprox_coc_rem(const reg_digs_t< UINT_T, B, N > &rem, const reg_digs_t< UINT_T, B, N > &dsor) noexcept
std::array<SIG_UINT_T,2>{}[0] == COC std::array<SIG_UINT_T,2>{}[1] == REM PRECONDICION DSOR != 0 Y DSOR != 1 FUNCION DE RECURSION PARA LA DIVISION SOBRECARGA DE LA ANTERIOR PARA LA RECURSION QUE NO SEA EL PRIMER CASO
constexpr std::array< type_traits::sig_UInt_for_UInt_t< UINT_T >, 2 > NumRepr::aprox_coc_rem(const reg_digs_t< UINT_T, B, N > &rem, const reg_digs_t< UINT_T, B, N > &dsor, type_traits::sig_UInt_for_UInt_t< UINT_T > coc_calculado, type_traits::sig_UInt_for_UInt_t< UINT_T > rem_calculado) noexcept
std::array<SIG_UINT_T,2>{}[0] == COC std::array<SIG_UINT_T,2>{}[1] == REM PRECONDICION DSOR != 0 Y DSOR != 1
constexpr std::array< reg_digs_t< UINT_T, B, std::max(N, M)>, 2 > NumRepr::fediv(const reg_digs_t< UINT_T, B, N > &larg, const reg_digs_t< UINT_T, B, M > &rarg) noexcept
END.
FUNCIONES DE IMPLEMENTACION DE LA DIVISION ENTRE DOS REGISTROS DE DIGITOS
References fediv, NumRepr::reg_digs_t< UINT_T, B, L >::index_of_MSDig, rem.
Referenced by fediv.
bool NumRepr::get_digit_token(std::istream &is, dig_t< UINT_T, B > &dig_value)
FUNCION QUE CONSIGUE EL TOKEN DIGITO.
References get_digit_token.
Referenced by get_digit_token, NumRepr::dig_t< UINT_T, B >::read.
bool NumRepr::get_radix_token(std::istream &is)
FUNCION QUE CONSIGUE EL TOKEN BASE.
References get_radix_token.
Referenced by get_radix_token, NumRepr::dig_t< UINT_T, B >::read.
bool NumRepr::get_digit_loop_token(std::istream &is, reg_digs_t< T, B, L > &value) noexcept
bool NumRepr::read(std::istream &is, reg_digs_t< T, B, L > &value) noexcept
DEFINCION DE template<uint128_t Radix> digito_t{};.
SOLO HAY QUE DECLARAR digit_t<2> o digit_t<10> o ...
std::istream & NumRepr::operator>>(std::istream &is, reg_digs_t< Int_Type, Base, Length > &arg)
SOBRECARGA DE ISTREAM Y OSTREAM CON LOS OPERADORES DE DESPLAZAMEINTO.
std::ostream & NumRepr::operator<<(std::ostream &os, const reg_digs_t< Int_Type, Base, Long > &arg)
void NumRepr::display_constr_UINT_dig_t()
void NumRepr::display_constr_SINT_dig_t()
void NumRepr::display_constr_defecto_dig_t()
void NumRepr::display_constr_copia_dig_t()
void NumRepr::display_constr_movimiento_dig_t()
void NumRepr::display_operator_assign_UINT_dig_t()
void NumRepr::display_operator_assign_SINT_dig_t()
void NumRepr::display_operator_assign_copia_dig_t()
void NumRepr::display_operator_assign_movimiento_dig_t()
void NumRepr::display_operator_preincrement()
void NumRepr::display_operator_postincrement()
void NumRepr::display_operator_predecrement()
void NumRepr::display_operator_postdecrement()
void NumRepr::display_operator_add_assign()
void NumRepr::display_operator_add_assign_uint()
void NumRepr::display_operator_substract_assign()
void NumRepr::display_operator_substract_assign_uint()
void NumRepr::display_operator_mult_assign()
void NumRepr::display_operator_mult_assign_uint()
void NumRepr::display_operator_ediv_assign()
void NumRepr::display_operator_ediv_assign_uint()
void NumRepr::display_operator_erem_assign()
void NumRepr::display_operator_erem_assign_uint()
void NumRepr::display_operator_add()
void NumRepr::display_operator_add_int()
void NumRepr::display_operator_substract()
void NumRepr::display_operator_substract_int()
void NumRepr::display_operator_multiply()
void NumRepr::display_operator_multiply_int()
void NumRepr::display_operator_edivision()
void NumRepr::display_operator_edivision_int()
void NumRepr::display_operator_C_B()
References NumRepr::dig_t< UINT_T, B >::C_B.
void NumRepr::display_operator_C_Bm1()
References NumRepr::dig_t< UINT_T, B >::C_Bm1.
void NumRepr::display_prop_C_B_eq_inv_C_B()
References NumRepr::dig_t< UINT_T, B >::C_B.
void NumRepr::display_prop_C_Bm1_eq_inv_C_Bm1()
References NumRepr::dig_t< UINT_T, B >::C_Bm1.
void NumRepr::display_prop_C_B_minus_1_eq_C_Bm1()
References NumRepr::dig_t< UINT_T, B >::C_B, NumRepr::dig_t< UINT_T, B >::C_Bm1.
void NumRepr::display_unary_operator_minus()
void NumRepr::display_unary_operator_neg()