NumRepr::detail
constexpr size_t NumRepr::detail::ceilsqrt(size_t n, size_t low, size_t high) noexcept
References ceilsqrt.
Referenced by ceilsqrt, NumRepr::auxiliary_functions::is_prime.
constexpr size_t NumRepr::detail::ceilsqrt(size_t n) noexcept
References ceilsqrt.
constexpr bool NumRepr::detail::find_factor(size_t n, size_t low, size_t high) noexcept
References find_factor.
Referenced by find_factor, NumRepr::auxiliary_functions::is_prime.