NumRepr::type_traits
using NumRepr::type_traits::sig_UInt_for_UInt_t = typedef typename ugly_details_UInt_for_UInt::__sig_UInt_for_UInt_t<UInt_t>::type
METAFUNCION : DA EL SIGUIENTE TIPO ENTERO PARA EL ACTUAL TIPO NATURAL POR ESPECIALIZACION EXPLICITA
using NumRepr::type_traits::sig_SInt_for_UInt_t = typedef typename ugly_details_sig_SInt_for_UInt::__sig_SInt_for_UInt_t<UInt_t>::type
METAFUNCION : DA EL SIGUIENTE TIPO NATURAL PARA EL ACTUAL TIPO ENTERO POR ESPECIALIZACION EXPLICITA
using NumRepr::type_traits::sig_UInt_for_SInt_t = typedef typename ugly_details_UInt_for_SInt::__sig_UInt_for_SInt_t<Int_t>::type
METAFUNCION : DA EL SIGUIENTE TIPO ENTERO PARA EL ACTUAL TIPO ENTERO POR ESPECIALIZACION EXPLICITA
using NumRepr::type_traits::sig_SInt_for_SInt_t = typedef typename ugly_details_SInt_for_SInt::__sig_SInt_for_SInt_t<SInt_t>::type
METAFUNCIONES PARA DAR CON LOS MAXIMOS NUMEROS QUE CABEN EN UN TIPO Y SIMILARES
using NumRepr::type_traits::TypeFromIntNumber_t = typedef typename UIntTypeForRadix<decltype(Radix),Radix>::UIntType
QUEREMOS FABRICAR LA METAFUNCION TypeFromIntNumberLTSqrtMaxOfType_t<numero> QUE DEVUELVA EL TIPO ENTERO SIN SIGNO MAS PEQUENO PARA EL NUMERO numero TAL QUE SQRT(TYPE::MAX())>=B-1
using NumRepr::type_traits::GreaterTypeFromIntNumber_t = typedef typename UIntTypeForRadixContainsMultResult<decltype(Radix),Radix>::UIntType
constexpr CharT NumRepr::type_traits::nullchar
constexpr bool NumRepr::type_traits::is_uint_type_for_radix_v
"CLASS" TYPE TYPE DEFINITION template<typename int_type,int_type base> class digito<int_type,base> {}; CONCEPT TYPE TYPE DEFINITION template<allowable_base_type_c int_type,int_type base> class digito<int_type,base> {}; METAOPERADOR QUE NOS DA LA ADECUACION DE UN TIPO PARA SER BASE DE UN SISTEMA DE NUMERACION VALE CUALQUIER TIPO UNSIGNED INTEGRAL QUE NO SEA EL MAYOR CONSIDERADO AQUI EL MAYOR CONSIDERADO ES UINT128_T
constexpr bool NumRepr::type_traits::is_unsigned_type_v
METAOPERADOR QUE NOS DA SI UN TIPO INTEGRAL ES UNSIGNED VALEN LOS QUE VALEN PARA RADIX MAS LOS TIPO MAS GRANDES POR LO TANTO UINT128_T SE CONSIDERA UN UNSIGNED INTEGRAL TYPE
constexpr bool NumRepr::type_traits::is_signed_type_v
METAOPERADOR QUE NOS DA SI UN TIPO INTEGRAL ES SIGNED.
constexpr bool NumRepr::type_traits::is_integral_type_v
METAOPERADOR QUE NOS DA SI UN TIPO ES INTEGRAL.
constexpr bool NumRepr::type_traits::eq_sz_v
METAOPERADORES DE COMPARACION DE CAPACIDAD DE INTEGERS.
constexpr bool NumRepr::type_traits::gt_sz_v
constexpr bool NumRepr::type_traits::lt_sz_v
constexpr bool NumRepr::type_traits::ge_sz_v
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=.
constexpr bool NumRepr::type_traits::le_sz_v
METAFUNCION : DA EL SIGUIENTE TIPO NATURAL PARA EL ACTUAL TIPO NATURAL POR ESPECIALIZACION EXPLICITA
char * NumRepr::type_traits::clear_ccad(char *, usint_t)
Referenced by devCadenaC.
constexpr const char * NumRepr::type_traits::devCadenaC(T< B > arg, std::size_t long_ccad=64) noexcept
References clear_ccad.
constexpr char * NumRepr::type_traits::clear_ccad(char *cad_c, std::size_t long_de_cad_c) noexcept
constexpr unsigned long long NumRepr::type_traits::atoull(char *text) noexcept
consteval UINT_T NumRepr::type_traits::maxbase()
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::assign, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator Int_Type, NumRepr::reg_digs_t< UINT_T, B, L >::operator Int_Type, NumRepr::reg_digs_t< UINT_T, B, L >::operator=.
consteval UINT_T NumRepr::type_traits::submaxbase()
consteval UINT_T NumRepr::type_traits::minbase()
consteval UINT_T NumRepr::type_traits::subminbase()
consteval UINT_T NumRepr::type_traits::monobase()
consteval UINT_T NumRepr::type_traits::nobase()
consteval UINT_T NumRepr::type_traits::maxdigit()
consteval UINT_T NumRepr::type_traits::submaxdigit()
consteval UINT_T NumRepr::type_traits::digit_0()
consteval UINT_T NumRepr::type_traits::digit_1()
consteval UINT_T NumRepr::type_traits::base_2()
consteval bool NumRepr::type_traits::base_geqt_2()
consteval bool NumRepr::type_traits::base_leqt_max()
consteval bool NumRepr::type_traits::suitable_base()
consteval UINT_T NumRepr::type_traits::middle_max()
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_add.
consteval UINT_T NumRepr::type_traits::sqrt_max()
QUEREMOS FABRICAR LA METAFUNCION TypeFromIntNumber_t<numero_sin_signo> QUE DEVUELVA EL TIPO ENTERO SIN SIGNO MAS PEQUENO PARA EL NUMERO numero_sin_signo
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::mult.