nat_reg_digs_t (Copia en conflicto de MSI 2022-11-24).hpp
using SIG_UINT_T = typename type_traits::sig_UInt_for_UInt_t<UINT_T>
using SIG_SINT_T = typename type_traits::sig_SInt_for_UInt_t<UINT_T>
using dig_t = dig_t<UINT_T,B>
using base_N_t = std::array<dig_t,N>
using base_t = base_N_t<L>
using res_base_N_op_t = typename auxiliary_types::result_operation_t<base_N_t<N>,op,N>
using res_base_op_t = typename auxiliary_types::result_operation_t<base_t,op,L>
using nat_reg_N_digs_t = nat_reg_digs_t<UINT_T,B,N>
using res_N_op_t = typename auxiliary_types::result_operation_t<nat_reg_N_digs_t<N>,op,N>
using res_op_t = typename auxiliary_types::result_operation_t<nat_reg_digs_t,op,L>
using reg_ints_t = typename std::array<UINT_T,N>
using reg_suints_t = typename std::array<SIG_UINT_T,N>
using reg_ssints_t = typename std::array<SIG_SINT_T,N>
base_t m_dc
struct NumRepr::nat_reg_digs_t NumRepr::operator(dig_t arg) const noexcept
static consteval dig_t operator::dig_0() noexcept
static consteval dig_t operator::dig_1() noexcept
static consteval dig_t operator::dig_Bm1() noexcept
static consteval dig_t operator::dig_max() noexcept
static consteval dig_t operator::dig_Bm2() noexcept
static consteval dig_t operator::dig_submax() noexcept
static consteval UINT_T operator::ui_0() noexcept
static consteval UINT_T operator::ui_1() noexcept
static consteval UINT_T operator::ui_Bm1() noexcept
static consteval UINT_T operator::ui_B() noexcept
static consteval UINT_T operator::ui_submax() noexcept
static consteval UINT_T operator::ui_max() noexcept
static consteval SIG_UINT_T operator::sui_0() noexcept
static consteval SIG_UINT_T operator::sui_1() noexcept
static consteval SIG_UINT_T operator::sui_Bm1() noexcept
static consteval SIG_UINT_T operator::sui_B() noexcept
static consteval SIG_UINT_T operator::sui_Bp1() noexcept
static consteval base_N_t< N > operator::regd_base_N_0() noexcept
PARA EL TIPO-TEMPLATE BASE_N_T OBTENEMOS CONSTANTES INMEDIATAS TENEMOS CUIDADO DE CREAR UN RVALUE TEMPORAL
static consteval base_N_t< N > operator::regd_base_N_1() noexcept
static consteval base_N_t< N > operator::regd_base_N_Bm1() noexcept
static consteval base_N_t< N > operator::regd_base_N_B() noexcept
static consteval base_N_t< N > operator::regd_base_N_pow_n_B() noexcept
static consteval base_N_t< N > operator::regd_base_N_pow_n_B_m1() noexcept
static consteval base_t operator::regd_base_0() noexcept
IDEM QUE ANTES PERO CON EL TIPO BASE_T ESPECIALIZANDO AL TIPO BASE_N_T<L> DONDE BASE_T == BASE_N_T<L> TENEMOS CUIDADO DE CREAR UN RVALUE TEMPORAL
static consteval base_t operator::regd_base_1() noexcept
static consteval base_t operator::regd_base_Bm1() noexcept
static consteval base_t operator::regd_base_B() noexcept
static consteval base_t operator::regd_base_pow_n_B() noexcept
static consteval base_t operator::regd_base_pow_n_B_m1() noexcept
static consteval nat_reg_digs_t operator::regd_0() noexcept
FUNCIONES INMEDIATAS QUE NOS DAN CONSTANTES DEL TIPO DE LA ACTUAL CLASE SE HACE CREANDO UNA VARIABLE RVALUE TEMPORAL CON LA FUNCION HOMOLOGA PARA BASE_T
static consteval nat_reg_digs_t operator::regd_1() noexcept
static consteval nat_reg_digs_t operator::regd_Bm1() noexcept
static consteval nat_reg_digs_t operator::regd_B() noexcept
static consteval nat_reg_digs_t operator::regd_pow_n_B() noexcept
static consteval nat_reg_digs_t operator::regd_pow_n_B_m1() noexcept
static consteval reg_ints_t< L > operator::regi_0() noexcept
ARRAYS DE ENTEROS (CONSTANTES EN TIEMPO DE COMPILACION INMEDIATAS)
static consteval reg_ints_t< L > operator::regi_1() noexcept
static consteval reg_ints_t< L > operator::regi_Bm1() noexcept
static consteval reg_ints_t< L > operator::regi_B() noexcept
static consteval reg_ints_t< L > operator::regi_pow_n_B() noexcept
static consteval reg_ints_t< L > operator::regi_pow_n_B_m1() noexcept
consteval operator::nat_reg_digs_t() noexcept
CONSTRUCTOR POR DEFECTO.
constexpr operator::nat_reg_digs_t(const std::initializer_list< dig_t > &arg) noexcept
CONSTRUCTOR POR LISTA DE DIGITOS.
constexpr operator::nat_reg_digs_t(const Ts &... args) noexcept
CONSTRUCTOR POR ARGUMENTOS DIGITOS SIN LIMITE: DEDUCE EL TIPO.
constexpr void operator::copy_arg_N(const base_N_t< N > &arg) noexcept
BEGIN : CONSTRUCTOR COPIA/MOVIMIENTO DESDE UN ARRAY DE DIGITOS FUNCION DELEGADA PARA COPIA DE UN ARRAY DEL MISMO TAMANO O UN TAMANO CUALQUIERA "N"
constexpr void operator::move_arg_N(base_N_t< N > &&arg) noexcept
FUNCION DELEGADA PARA MOVER DE UN ARRAY DEL MISMO TAMANO O UN TAMANO CUALQUIERA "N"
constexpr void operator::copy_arg_N(const nat_reg_n_digs_t< N > &arg) noexcept
FUNCION DELEGADA PARA COPIA DE UN NAT_REG_N_DIGS_T DEL MISMO TAMANO O UN TAMANO CUALQUIERA "N"
constexpr void operator::move_arg_N(nat_reg_n_digs_t< N > &&arg) noexcept
FUNCION DELEGADA PARA MOVER DE UN NAT_REG_N_DIGS_T DEL MISMO TAMANO O UN TAMANO CUALQUIERA "N"
constexpr operator::nat_reg_digs_t(const base_N_t< N > &arg) noexcept
CONSTRUCTOR COPIA DESDE UN ARRAY DE DIGITOS.
constexpr operator::nat_reg_digs_t(const base_N_t< N > &&arg) noexcept
CONSTRUCTOR MOVIMIENTO DESDE UN ARRAY DE DIGITOS.
static constexpr base_t operator::normalize(Ints_type ... digits_pow_i) noexcept
END : CONSTRUCTOR COPIA/MOVIMIENTO DESDE UN ARRAY DE DIGITOS.
FUNCION DE NORMALIZACION A LA BASE B DE UN ARGUMENTOS EN UN PACK DE ENTEROS CUALQUIERA
constexpr operator::nat_reg_digs_t(Ints_type ... dig_pow_i) noexcept
CONSTRUCTOR COPIA DESDE ARGUMENTOS ENTEROS SIN LIMITE : DEDUCE EL TIPO.
constexpr operator::nat_reg_digs_t(const nat_reg_N_digs_t< N > &arg) noexcept
CONSTRUCTOR COPIA POR REFERENCIA CONSTANTE.
constexpr operator::nat_reg_digs_t(nat_reg_N_digs_t< N > &&arg) noexcept
CONSTRUCTOR POR MOVIMIENTO.
constexpr const nat_reg_digs_t & operator::operator=(const base_N_t< N > &arg) noexcept
OPERACION ASIGNACION POR COPIA REFERENCIA CONST NO COPIABLE DESDE BASE_N_T.
constexpr nat_reg_digs_t & operator::operator=(base_N_t< N > &arg) noexcept
OPERACION ASIGNACION POR COPIA REFERENCIA DESDE BASE_N_T.
constexpr const nat_reg_digs_t & operator::operator=(base_N_t< N > &&arg) noexcept
OPERACION ASIGNACION POR COPIA MOVIMIENTO DESDE BASE_N_T.
constexpr nat_reg_digs_t & operator::operator=(const nat_reg_N_digs_t< N > &arg) noexcept
OPERACION ASIGNACION POR COPIA REFERENCIA EN LA QUE SE PUEDE COPIAR.
constexpr nat_reg_digs_t & operator::operator=(nat_reg_N_digs_t< N > &&arg) noexcept
OPERACION ASIGNACION POR MOVIMIENTO.
constexpr const nat_reg_digs_t & operator::operator=(const nat_reg_N_digs_t< N > &arg) noexcept
OPERACION ASIGNACION POR COPIA EN LA QUE NO SE PUEDE COPIAR.
static constexpr void operator::set_0(base_N_t &arg) noexcept
static constexpr void operator::set_1(base_N_t &arg) noexcept
static constexpr void operator::set_Bm1(base_N_t &arg) noexcept
static constexpr void operator::set_dig(base_N_t &larg, dig_t d) noexcept
static constexpr void operator::set_fill_dig(base_N_t &larg, dig_t d) noexcept
static constexpr void operator::set_fill_1(base_N_t &larg) noexcept
static constexpr void operator::set_fill_Bm1(base_N_t &larg) noexcept
static constexpr void operator::set_interval_0(base_N_t< N > &larg) noexcept
OPERACION DE PONER A VALOR DIG_0 DEL ARRAY DESDE [N_0 , N_1) EN BASE_N_T<N>
static constexpr void operator::set_interval_Bm1(base_N_t< N > &larg) noexcept
OPERACION DE PONER A VALOR DIG_Bm1 DEL ARRAY DESDE [N_0 , N_1) EN BASE_N_T<N>
static constexpr void operator::set_interval_dig(base_N_t< N > &larg, dig_t dig) noexcept
OPERACION DE PONER A VALOR DIG DEL ARRAY DESDE [N_0 , N_1) EN BASE_N_T<N>
static constexpr void operator::set_interval_0(base_t &larg) noexcept
OPERACION DE PONER A VALOR DIG_0 DEL ARRAY DESDE [N_0 , N_1) EN BASE_T ESPECIALIZACION PARA N==L
static constexpr void operator::set_interval_Bm1(base_t &larg) noexcept
OPERACION DE PONER A VALOR DIG_Bm1 DEL ARRAY DESDE [N_0 , N_1) EN BASE_T ESPECIALIZACION PARA N==L
static constexpr void operator::set_interval_dig(base_t &larg, dig_t dig) noexcept
OPERACION DE PONER A VALOR DIG DEL ARRAY DESDE [N_0 , N_1) EN BASE_T ESPECIALIZACION PARA N==L
constexpr void operator::set_0() noexcept
OPERACION DE LIMPIEZA A CERO DEL NAT_REG_DIGS_T.
Referenced by NumRepr::reg_digs_t< UINT_T, B, L >::operator=.
constexpr void operator::set_Bm1() noexcept
OPERACION DE LIMPIEZA A B-1 DEL NAT_REG_DIGS_T.
constexpr void operator::set_dig(dig_t arg) noexcept
OPERACION DE LIMPIEZA A VALOR DIG_T DEL NAT_REG_DIGS_T.
constexpr void operator::set_interval_0() noexcept
OPERACION DE PONER A VALOR DIG_0 EN [N_0 , N_1) DEL NAT_REG_DIGS_T.
constexpr void operator::set_interval_Bm1() noexcept
OPERACION DE PONER A VALOR DIG_Bm1 EN [N_0 , N_1) DEL NAT_REG_DIGS_T.
constexpr void operator::set_interval_dig(dig_t dig) noexcept
OPERACION DE PONER A VALOR DIG EN [N_0 , N_1) DEL NAT_REG_DIGS_T.
constexpr nat_reg_digs_t & operator::operator=(const dig_t &arg) noexcept
OPERACION COPIA DESDE UN DIGITO (CONVERSION)
static constexpr const base_t & operator::assign(base_t &larg, Int_Type arg) noexcept
OPERACION COPIA DESDE UN ENTERO (CONVERSION A LA BASE B) A UN BASE_T.
constexpr nat_reg_digs_t & operator::operator=(Int_Type arg) noexcept
OPERACION COPIA DESDE UN ENTERO (CONVERSION A LA BASE B)
static constexpr base_N_t< N > operator::concat(const base_N_t< N > &larg) noexcept
STATIC BASE_N_T<N> CONCAT(BASE_N_T<N>)
STATIC BASE_N_T<N> CONCAT(BASE_N_T<N>) STATIC BASE_N_T<N+M> CONCAT(BASE_N_T<N>,BASE_N_T<M>) STATIC BASE_N_T<N+1> CONCAT(BASE_N_T<N>,DIG_T) STATIC BASE_N_T<1+M> CONCAT(DIG_T,BASE_N_T<M>) STATIC BASE_N_T<1> CONCAT(DIG_T) STATIC BASE_N_T<1+1> CONCAT(DIG_T,DIG_T) STATIC BASE_N_T<SIZEOF...(DIG_PACK)> CONCAT(DIG_T ... DIG_PACK) VARIADIC PACK
static constexpr base_N_t< N+M > operator::concat(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
STATIC BASE_N_T<N+M> CONCAT(BASE_N_T<N>,BASE_N_T<M>)
static constexpr base_N_t< N+1 > operator::concat(const base_N_t< N > &larg, dig_t rarg) noexcept
STATIC BASE_N_T<N+1> CONCAT(BASE_N_T<N>,DIG_T)
static constexpr base_N_t< 1+M > operator::concat(dig_t larg, const base_N_t< M > &rarg) noexcept
STATIC BASE_N_T<1+M> CONCAT(DIG_T,BASE_N_T<M>)
static constexpr base_N_t< 1 > operator::concat(dig_t larg) noexcept
STATIC BASE_N_T<1> CONCAT(DIG_T)
static constexpr base_N_t< 2 > operator::concat(dig_t larg, dig_t rarg) noexcept
STATIC BASE_N_T<1+1> CONCAT(DIG_T,DIG_T)
static constexpr base_N_t< 1+(sizeof ...(Ts))> operator::concat(T0 dig0, Ts ... dig_pack) noexcept
STATIC BASE_N_T<SIZEOF...(DIG_PACK)> CONCAT(DIG_T,DIG_T ... DIG_PACK) VARIADIC.
static constexpr base_N_t< N+1+(sizeof ...(Ts))> operator::concat(base_N_t< N > larg, T dig, Ts ... dig_pack) noexcept
STATIC BASE_N_T<N+1+(SIZEOF...(DIG_PACK))> CONCAT(BASE_N_T<N>,DIG_T,DIG_T ... DIG_PACK) VARIADIC.
static constexpr base_N_t< M+1+(sizeof ...(Ts))> operator::concat(T dig, Ts ... dig_pack, base_N_t< M > rarg) noexcept
STATIC BASE_N_T<M+1+(SIZEOF...(DIG_PACK))> CONCAT(DIG_T,DIG_T ... DIG_PACK,BASE_N_T<M>) VARIADIC.
static constexpr base_N_t< N+(...+(N_pack))> operator::concat(base_N_t< N > larg, base_N_t< N_pack... > ... rarg_pack) noexcept
STATIC BASE_N_T<SIZE_T N,SIZE_T ... N_PACK> CONCAT(BASE_N_T<N> LARG,BASE_N_T<N_PACK> ... RARG_PACK) VARIADIC.
static constexpr base_N_t< std::abs< size_t >(iend-ibegin)> operator::subregister(const base_N_t< N > &arg) noexcept
TAKE A SUBREGISTER OF A REGISTER OF DIGITS.
constexpr nat_reg_N_digs_t< N+L > operator::cat(const nat_reg_N_digs_t< N > &arg) const noexcept
SUBREPR => SUB REPRESENTACION.
FORMACION DE UN REG_M_DIGS_T<M> DESDE EL THIS REG_DIGS_T (L) Y REG_N_DIGS_T<N> EN SUS DOS FORMAS: (*THIS)SEGUIDO(ARG) Y (ARG)SEGUIDO(*THIS) : OPERACIONES DE CONCATENACION FORMACION DE UN REG_M_DIGS_T<M> DESDE EL THIS REG_DIGS_T (L) Y REG_N_DIGS_T<N> EN SUS DOS FORMAS: (*THIS)SEGUIDO(ARG) Y (ARG)SEGUIDO(*THIS) : OPERACIONES DE CONCATENACION NAT_REG_N_T<L+M> NAT_REG_T::CAT(NAT_REG_N_T<M>) NAT_REG_N_T<L+M> NAT_REG_T::CAT_INV(NAT_REG_N_T<M>) NAT_REG_N_T<L+1> NAT_REG_T::CAT(DIG_T) NAT_REG_N_T<L+1> NAT_REG_T::CAT_INV(DIG_T)
constexpr nat_reg_N_digs_t< L+1 > operator::cat(dig_t arg) const noexcept
constexpr nat_reg_N_digs_t< N+L > operator::cat_inv(const nat_reg_N_digs_t< N > &arg) const noexcept
constexpr nat_reg_N_digs_t< L+1 > operator::cat_inv(dig_t arg) const noexcept
constexpr nat_reg_N_digs_t< iend-ibegin > operator::subrepr() const noexcept
constexpr operator::operator Int_Type() const noexcept
static constexpr bool operator::is_0(const base_N_t< N > &arg) noexcept
static constexpr bool operator::is_1(const base_N_t< N > &arg) noexcept
static constexpr bool operator::is_Bm1(const base_N_t< N > &arg) noexcept
static constexpr bool operator::is_B(const base_N_t< N > &arg) noexcept
static constexpr bool operator::is_Bp1(const base_N_t< N > &arg) noexcept
static constexpr bool operator::is_B_pow_m1(const base_N_t< N > &arg) noexcept
static constexpr bool operator::is_B_pow(const base_N_t< N > &arg) noexcept
static constexpr bool operator::is_filled_of_1(const base_N_t< N > &arg)
static constexpr bool operator::is_filled_of_Bm1(const base_N_t< N > &arg)
static constexpr bool operator::is_filled_of(const base_N_t< N > &arg)
constexpr bool operator::is_0() const
Referenced by NumRepr::dig_t< UINT_T, B >::is_0_divisor, NumRepr::dig_t< UINT_T, B >::is_maxormin, NumRepr::dig_t< UINT_T, B >::is_near_maxormin, NumRepr::dig_t< UINT_T, B >::is_unit, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator!=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator-=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator==, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator>, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator>=.
constexpr bool operator::is_1() const
Referenced by NumRepr::dig_t< UINT_T, B >::is_near_maxormin, NumRepr::dig_t< UINT_T, B >::is_unit, NumRepr::dig_t< UINT_T, B >::mult_inv, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator-=.
constexpr bool operator::is_Bm1() const
Referenced by NumRepr::dig_t< UINT_T, B >::is_Bm1orBm2, NumRepr::dig_t< UINT_T, B >::is_maxormin, NumRepr::dig_t< UINT_T, B >::is_near_maxormin.
constexpr bool operator::is_B() const
constexpr bool operator::is_Bp1() const
constexpr bool operator::is_B_pow_m1() const
constexpr bool operator::is_B_pow() const
constexpr bool operator::is_filled_of_1() const
constexpr bool operator::is_filled_of_Bm1() const
constexpr bool operator::is_filled_of() const
static constexpr bool operator::operator==(const base_N_t< N > &larg, const dig_t &rarg)
COMPARACIONES ENTRE BASE_N_T Y DIG_T EN FORMA BASE_N_T<N> @ DIG_T STATIC
static constexpr bool operator::operator!=(const base_N_t< N > &larg, const dig_t &rarg)
static constexpr bool operator::operator>(const base_N_t< N > &larg, const dig_t &rarg)
static constexpr bool operator::operator<(const base_N_t< N > &larg, const dig_t &rarg)
static constexpr bool operator::operator>=(const base_N_t< N > &larg, const dig_t &rarg)
static constexpr bool operator::operator<=(const base_N_t< N > &larg, const dig_t &rarg)
static constexpr bool operator::operator==(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
COMPARACIONES ENTRE BASE_N_T Y BASE_N_T HETEROGENEOS EN GENERAL EN FORMA BASE_N_T<N> @ BASE_N_T<M> STATIC
static constexpr bool operator::operator!=(const base_N_t< N > &larg, const base_N_t< M > &rarg)
static constexpr bool operator::operator>(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
static constexpr bool operator::operator<(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
static constexpr bool operator::operator>=(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
static constexpr bool operator::operator<=(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
constexpr bool operator::operator==(const base_N_t< N > &arg) const noexcept
constexpr bool operator::operator==(const nat_reg_N_digs_t< N > &arg) const noexcept
constexpr bool operator::operator!=(const base_N_t< N > &arg) const noexcept
constexpr bool operator::operator!=(const nat_reg_N_digs_t< N > &arg) const noexcept
constexpr bool operator::operator<=(const base_N_t< N > &arg) const noexcept
constexpr bool operator::operator<=(const nat_reg_N_digs_t< N > &arg) const noexcept
constexpr bool operator::operator>=(const base_N_t< N > &arg) const noexcept
constexpr bool operator::operator>=(const nat_reg_N_digs_t< N > &arg) const noexcept
constexpr bool operator::operator<(const base_N_t< N > &arg) const noexcept
constexpr bool operator::operator<(const nat_reg_N_digs_t< N > &arg) const noexcept
constexpr bool operator::operator>(const base_N_t< N > &arg) const noexcept
constexpr bool operator::operator>(const nat_reg_N_digs_t< N > &arg) const noexcept
constexpr std::strong_ordering operator::operator<=>(const nat_reg_N_digs_t< N > &arg) const noexcept
OPERADOR COMPARACION SPACESHIP C++20.
constexpr std::weak_ordering operator::operator<=>(const base_N_t< N > &arg) const noexcept
OPERADOR COMPARACION SPACESHIP C++20.
constexpr std::weak_ordering operator::operator<=>(const dig_t &arg) const noexcept
OPERADOR COMPARACION SPACESHIP C++20.
constexpr dig_t operator::get() const noexcept
constexpr dig_t operator::put(dig_t arg) noexcept
constexpr dig_t & operator[](size_t idx) const noexcept
constexpr Int_Type operator::operator()(size_t idx) const noexcept
constexpr base_t & operator::ref_data() const
constexpr base_t * operator::data() const
constexpr const base_t & operator::const_ref_data() const
Referenced by NumRepr::reg_digs_t< UINT_T, B, L >::back, NumRepr::reg_digs_t< UINT_T, B, L >::empty, NumRepr::reg_digs_t< UINT_T, B, L >::front, NumRepr::reg_digs_t< UINT_T, B, L >::max_size, NumRepr::reg_digs_t< UINT_T, B, L >::size.
constexpr base_t operator::cpy_data() const
static constexpr auto operator::preincrement(base_t &arg) -> std::conditional_t< with_result_type, res_base_op_t< binop_e::add >, const base_t & > noexcept
<! TODO : ME HE QUEDADO REPASANDO POR AQUI 31/23/18/11/2022
< PREINCREMENT(OBJ) == ++OBJ SOLO QUE DEVUELVE CARRY TAMBIEN PREINCREMENT(OBJ) -> CONDICIONALMENTE BIEN RES_BASE_OP_T (con CARRY), BIEN BASE_T (sin CARRY) < result_content_low result_content_high carry borrow result_content_quotient result_content_remainder good_result
constexpr const nat_reg_digs_t & operator::operator++() noexcept
static constexpr auto operator::postincrement(base_t &arg) -> std::conditional< with_result_type, res_base_op_t< binop_e::add >, const base_t & > noexcept
constexpr const nat_reg_digs_t & operator::operator++(int) noexcept
constexpr auto operator::predecrement(base_t &arg) -> std::conditional< with_result_type, res_base_op_t< binop_e::sub >, const base_t & > noexcept
constexpr const nat_reg_digs_t & operator::operator--() noexcept
constexpr auto operator::postdecrement(base_t &arg) -> std::conditional< with_result_type, res_base_op_t< binop_e::sub >, const base_t & > noexcept
constexpr const nat_reg_digs_t & operator::operator--(int) noexcept
static constexpr const base_t & operator::mC_Bm1(base_t &arg) noexcept
static constexpr const base_t & operator::mC_B(base_t &arg) noexcept
static constexpr base_t operator::C_Bm1(const base_t &arg) noexcept
static constexpr base_t operator::C_B(const base_t &arg) noexcept
constexpr const nat_reg_digs_t & operator::mC_B() noexcept
constexpr const nat_reg_digs_t & operator::mC_Bm1() noexcept
constexpr nat_reg_digs_t operator::C_Bm1() const noexcept
constexpr nat_reg_digs_t operator::C_B() const noexcept
constexpr nat_reg_digs_t operator::operator!() const noexcept
constexpr nat_reg_digs_t operator::operator-() const noexcept
static constexpr base_t operator::operator<<(const base_t &larg, size_t n) noexcept
BEGIN : OPERATORS >> >>= << <<= REM_B^n M_REM_B^n MER_B_N M_MER_B_N.
MULTIPLY BY THE BASE B (10) << <<= DIVIDE BY THE BASE B (10) >> >>= REMAINDER BY THE BASE B (10) REM_B_N M_REM_B_N MULTIPLICATIVE CARRY BY THE BASE B (10) MER_B_N M_MER_B_N
static constexpr const base_t & operator::operator<<=(base_t &larg, size_t n) noexcept
static constexpr const base_t & operator::operator>>=(base_t &larg, size_t n) noexcept
static constexpr base_t operator::operator>>(const base_t &larg, size_t n) noexcept
static constexpr base_t operator::rem_B(const base_t &larg, size_t n) noexcept
static constexpr const base_t & operator::m_rem_B(base_t &larg, size_t n) noexcept
static constexpr base_t operator::mer_B(const base_t &larg, size_t n) noexcept
static constexpr const base_t & operator::m_mer_B(base_t &larg, size_t n) noexcept
constexpr nat_reg_digs_t operator::operator<<(size_t n) const noexcept
constexpr const nat_reg_digs_t & operator::operator<<=(size_t n) noexcept
constexpr nat_reg_digs_t operator::operator>>(size_t n) const noexcept
constexpr const nat_reg_digs_t & operator::operator>>=(size_t n) noexcept
constexpr nat_reg_digs_t operator::rem_B(size_t n) const noexcept
constexpr const nat_reg_digs_t & operator::m_rem_B(size_t n) noexcept
constexpr nat_reg_digs_t operator::mer_B(size_t n) const noexcept
constexpr const nat_reg_digs_t & operator::m_mer_B(size_t n) noexcept
static constexpr const base_t & operator::operator|=(base_t &larg, const base_t &rarg) noexcept
END : OPERATORS >> >>= << <<= REM_B^n M_REM_B^n MER_B_N M_MER_B_N.
BEGIN : OPERATORS | & |= &=
static constexpr base_t operator::operator|(const base_t &larg, const base_t &rarg) noexcept
static constexpr const base_t & operator::operator&=(base_t &larg, const base_t &rarg) noexcept
static constexpr base_t operator::operator&(base_t &larg, const base_t &rarg) noexcept
constexpr const nat_reg_digs_t & operator::operator|=(const nat_reg_digs_t &arg) noexcept
constexpr nat_reg_digs_t operator::operator|(const nat_reg_digs_t &arg) noexcept
constexpr const nat_reg_digs_t & operator::operator&=(const nat_reg_digs_t &arg) noexcept
constexpr nat_reg_digs_t operator::operator&(const nat_reg_digs_t &arg) noexcept
static constexpr auto operator::m_add(base_t &larg, const dig_t &rarg) -> typename std::conditional_t< with_result_type, res_base_op_t< binop_e::add >, base_t const & > noexcept
END : OPERATORS | & |= &=.
OPERACIONES BINARIAS CON/SIN TIPO RESULTADO OPERACIONES BINARIAS BASE_T @ DIG_T OPERATOR BASE_T += DIG_T CON NOMBRE M_ADDITION
static constexpr const base_t & operator::m_sub(base_t &larg, const dig_t &rarg) noexcept
OPERATOR BASE_T -= DIG_T CON NOMBRE M_SUB.
static constexpr base_t operator::add(const base_t &larg, const dig_t &rarg) noexcept
static constexpr base_t operator::sub(const base_t &larg, const dig_t &rarg) noexcept
constexpr const nat_reg_digs_t & operator::operator+=(const dig_t &rarg) noexcept
constexpr const nat_reg_digs_t & operator::operator-=(const dig_t &rarg) noexcept
constexpr nat_reg_digs_t operator::operator+(const dig_t &rarg) noexcept
constexpr nat_reg_digs_t operator::operator-(const dig_t &rarg) noexcept
constexpr auto operator::mult(dig_t arg) const -> std::conditional_t< with_result_type, res_base_op_t< binop_e::mult >, const base_t & > noexcept
OPERACIONES '@'(REG_DIGS_T,DIG_T)->RESULT_TYPE<'@'> '@' = MULT
static constexpr auto operator::fediv(const base_t &larg, const dig_t &rarg) -> res_base_op_t< binop_e::fediv > noexcept
'@' = FULL_EUCLID_DIV(BASE_T,DIG_T) -> (REM,COC,GOOD)
constexpr auto NumRepr::operator-(dig_t arg) const noexcept
constexpr auto NumRepr::operator*(dig_t arg) const noexcept
TO DO TODAY 20:28-10-11-2022 ARITHMETIC OPERATION : COMPLETE EUCLIDEAN DIVISION BY A BASE_N_T<1>
static constexpr auto NumRepr::fediv(const base_t &larg, const base_N_t< 1 > &rarg) -> res_base_op_t< binop_e::fediv > noexcept
static constexpr base_N_t< 3 > NumRepr::aprox_divB(const base_N_t< 3 > &arg) noexcept
static constexpr base_N_t< 2 > NumRepr::aprox_divB_not0(const base_N_t< 2 > &arg) noexcept
TODO 15-11-2022 HECHO DESPUES DE LA HORA 20:00-14-11-2022 PERO EL MISMO DIA FUNCION DE RECURSION PARA LA DIVISION
static constexpr std::array< SIG_UINT_T, 2 > NumRepr::aprox_coc(const base_t &dndo, const base_t &dsor, const base_N_t< 3 > &rem, const base_N_t< 2 > &coc, SIG_UINT_T rem_calculado, SIG_UINT_T coc_calculado) noexcept
static constexpr std::array< SIG_UINT_T, 2 > NumRepr::aprox_decr_coc(const base_t &dndo, const base_t &dsor, const base_N_t< 3 > &rem, const base_N_t< 2 > &coc, SIG_UINT_T rem_calculado, SIG_UINT_T coc_calculado) noexcept
static constexpr std::array< SIG_UINT_T, 2 > NumRepr::aprox_incr_coc(const base_t &dndo, const base_t &dsor, const base_N_t< 3 > &rem, const base_N_t< 2 > &coc, SIG_UINT_T rem_calculado, SIG_UINT_T coc_calculado) noexcept
TODO 20:00-14-11-2022.
static constexpr auto NumRepr::fediv(const base_t &larg, const base_N_t< 2 > &rarg) -> res_base_op_t< binop_e::fediv > noexcept
constexpr nat_reg_digs_t NumRepr::operator/(dig_t arg) const noexcept
DIVISION BY A DIGIT.
References NumRepr::fediv.
constexpr nat_reg_digs_t NumRepr::operator%(dig_t arg) const noexcept
REMAINDER BY A DIGIT.
References NumRepr::fediv.
constexpr const nat_reg_digs_t & NumRepr::operator+=(const base_N_t< N > &arg) noexcept
constexpr const nat_reg_digs_t & NumRepr::operator+=(const nat_reg_N_digs_t< N > &arg) noexcept
constexpr const nat_reg_digs_t & NumRepr::operator-=(const base_N_t< N > &arg) noexcept
constexpr const nat_reg_digs_t & NumRepr::operator-=(const nat_reg_N_digs_t< N > &arg) noexcept
constexpr const nat_reg_digs_t & NumRepr::operator*=(const base_N_t< N > &arg) noexcept
constexpr const nat_reg_digs_t & NumRepr::operator*=(const nat_reg_N_digs_t< N > &arg) noexcept
constexpr nat_reg_digs_t NumRepr::operator+(const base_N_t< N > &arg) const noexcept
TO DO.
TO DO
constexpr nat_reg_digs_t NumRepr::operator-(const base_N_t< N > &arg) const noexcept
constexpr nat_reg_digs_t NumRepr::operator*(const base_N_t< N > &arg) const noexcept
constexpr nat_reg_digs_t NumRepr::operator+(const nat_reg_N_digs_t< N > &arg) const noexcept
constexpr nat_reg_digs_t NumRepr::operator-(const nat_reg_N_digs_t< N > &arg) const noexcept
constexpr nat_reg_digs_t NumRepr::operator*(const nat_reg_N_digs_t< N > &arg) const noexcept
static constexpr size_t NumRepr::cuenta_0s_desde_IZDA(const reg_ints_t< L > &arg) noexcept
static constexpr size_t NumRepr::cuenta_0s_desde_DRCHA(const reg_ints_t< L > &arg) noexcept
constexpr nat_reg_digs_t NumRepr::operator/(const nat_reg_digs_t &arg) const noexcept
References NumRepr::rem.
constexpr nat_reg_digs_t NumRepr::operator%(const nat_reg_digs_t &arg) const noexcept
std::istream & operator>>(std::istream &is, nat_reg_digs_t< Int_Type, Base, Length > &arg)
TODO ESTA VERSION + VERSION CON TRATAMIENTO DE ERRORES EN RUNTIME
std::ostream & operator<<(std::ostream &os, const nat_reg_digs_t< Int_Type, Base, Long > &arg)