NumRepr::nat_rat_fixed_reg_t
using NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_t = dig_t<UINT_T,B>
using NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::base_NEXNF_t = std::array<dig_t<UINT_T,B>,NE+NF>
using NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::base_t = base_NEXNF_t<LE,LF>
using NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_NExNF_digs_t = pfx_rat_reg_digs_t<UINT_T,B,NE,NF>
using NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::SIG_UINT_T = typename type_traits::sig_UInt_for_UInt_t<UINT_T>
using NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::SIG_SINT_T = typename type_traits::sig_SInt_for_UInt_t<UINT_T>
using NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::nat_reg_NExNF_digs_t = nat_reg_digs_t<UINT_T,B,NE+NF>
using NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::nat_reg_digs_t = nat_reg_digs_t<UINT_T,B,LE+LF>
using NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::reg_ints_t = typename std::array<UINT_T,NE+NF>
using NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::reg_suints_t = typename std::array<SIG_UINT_T,NE+NF>
using NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::reg_ssints_t = typename std::array<SIG_SINT_T,NE+NF>
base_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::copy_arg_N, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::get, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::IntPart, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_rem_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::mC_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::mC_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::move_arg_N, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::mult, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator!=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator&=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator(), NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator++, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator+=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator--, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator-=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator==, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator>, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator>=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator[], NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator|=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::put, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::rem_B.
static constexpr dig_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0() noexcept
References NumRepr::dig_t< UINT_T, B >::dig_0.
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::add, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::copy_arg_N, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_rem_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::mC_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::move_arg_N, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::mult, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::normalize, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator++, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator+=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator--, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator-=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<<, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<<=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator>>, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator>>=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator[], NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::subst.
static constexpr dig_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_1() noexcept
References NumRepr::dig_t< UINT_T, B >::dig_1.
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::mC_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator++, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator+=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator-=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_pow_n_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_pow_n_B.
static constexpr dig_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_Bm1() noexcept
References NumRepr::dig_t< UINT_T, B >::dig_max.
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::mC_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator++, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator+=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator-=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::subst.
static constexpr dig_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_max() noexcept
References NumRepr::dig_t< UINT_T, B >::dig_max.
static constexpr dig_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_Bm2() noexcept
References NumRepr::dig_t< UINT_T, B >::dig_submax.
static constexpr dig_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_submax() noexcept
References NumRepr::dig_t< UINT_T, B >::dig_submax.
static constexpr UINT_T NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::ui_0() noexcept
References NumRepr::dig_t< UINT_T, B >::ui_0.
static constexpr UINT_T NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::ui_1() noexcept
References NumRepr::dig_t< UINT_T, B >::ui_1.
static constexpr UINT_T NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::ui_Bm1() noexcept
References NumRepr::dig_t< UINT_T, B >::ui_Bm1.
static constexpr SIG_UINT_T NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::sui_B() noexcept
References NumRepr::dig_t< UINT_T, B >::sui_B.
static constexpr SIG_UINT_T NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::sui_Bp1() noexcept
References NumRepr::dig_t< UINT_T, B >::sui_B.
static constexpr UINT_T NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::ui_submax() noexcept
References NumRepr::dig_t< UINT_T, B >::ui_submax.
static constexpr UINT_T NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::ui_max() noexcept
References NumRepr::dig_t< UINT_T, B >::ui_max.
static constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_0() noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_pow_n_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::rem_B.
static constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_1() noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_0.
static constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_Bm1() noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_0.
static constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_B() noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_0.
static constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_pow_n_B() noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_0.
static constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_pow_n_B_m1() noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
static constexpr reg_ints_t< LE+LF > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_0() noexcept
ARRAYS DE ENTEROS QUE SON DE AYUDA.
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0.
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_pow_n_B.
static constexpr reg_ints_t< LE+LF > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_1() noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_0.
static constexpr reg_ints_t< LE+LF > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_Bm1() noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_0.
static constexpr reg_ints_t< LE+LF > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_B() noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_0.
static constexpr reg_ints_t< LE+LF > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_pow_n_B() noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_0.
static constexpr reg_ints_t< LE+LF > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regi_pow_n_B_m1() noexcept
static constexpr base_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::normalize(Ints_type ... digits_pow_i) noexcept
END : CONSTRUCTOR COPIA/MOVIMIENTO DESDE UN ARRAY DE DIGITOS.
FUNCION DE NORMALIZACION A LA BASE B DE UN ARGUMENTOS EN UN PACK DE ENTEROS CUALQUIERA INTERNA
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0.
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
static constexpr std::size_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::cuenta_0s_desde_IZDA(const reg_ints_t< LE+LF > &arg) noexcept
static constexpr std::size_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::cuenta_0s_desde_DRCHA(const reg_ints_t< LE+LF > &arg) noexcept
constexpr NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t() noexcept
CONSTRUCTOR POR DEFECTO pfx_rat_reg_digs_t<10,3,2> var(); var == nat#0:0:0:s:0:0#B10
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0.
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::add, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::C_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::C_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::concat, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::concat_inv, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::mC_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::mC_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::mult, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator!, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator&, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator*, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator*=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator+, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator++, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator+=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator-, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator--, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator-=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<<, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<<=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<=>, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator>>, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator>>=, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator|, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_pow_n_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_pow_n_B_m1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::rem_B, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::rev_subreg_digs, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::rev_subreg_digs_pe, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::rev_subreg_digs_pf, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::subreg_digs, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::subreg_digs_pe, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::subreg_digs_pf, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::subst.
constexpr NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t(const std::initializer_list< dig_t > &arg) noexcept
CONSTRUCTOR POR LISTA DE DIGITOS pfx_rat_reg_digs_t<10,3,2> var{dig_t(1),dig_t(3),dig_t(2),dig_t(5),dig_t(6)}; var == nat#1:3:2:s:5:6#B10
constexpr NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t(const Ts &... args) noexcept
CONSTRUCTOR POR ARGUMENTOS DIGITOS SIN LIMITE: DEDUCE EL TIPO pfx_rat_reg_digs_t<10,3,2> var(dig_t(1),dig_t(3),dig_t(2),dig_t(5),dig_t(6)); var == nat#1:3:2:5:6#B10
void NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::copy_arg_N(const base_NEXNF_t< NE, NF > &arg)
BEGIN : CONSTRUCTOR COPIA/MOVIMIENTO DESDE UN ARRAY DE DIGITOS.
FUNCION DELEGADA PARA COPIA DE UN ARRAY DE DISTINTO TAMANO O TAMANO CUALQUIERA "N" INTERNO
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
void NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::move_arg_N(base_N_t< NE, NF > &&arg)
FUNCION DELEGADA PARA MOVER DE UN ARRAY DE DISTINTO TAMANO O TAMANO CUALQUIERA "N" INTERNO
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t(const base_NExNF_t< NE, NF > &arg) noexcept
CONSTRUCTOR COPIA REFERENCIA DESDE UN ARRAY DE DIGITOS INTERNO
constexpr NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t(const base_NExNF_t< NE, NF > &&arg) noexcept
CONSTRUCTOR MOVIMIENTO DESDE UN ARRAY DE DIGITOS INTERNO
constexpr NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t(Ints_type ... dig_pow_i) noexcept
CONSTRUCTOR COPIA DESDE ARGUMENTOS ENTEROS SIN LIMITE : DEDUCE EL TIPO pfx_rat_reg_digs_t<10,3,2> var{1,3,2,5,6}; var == nat#1:3:2:s:5:6#B10
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::normalize.
constexpr NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t(const nat_reg_NExNF_digs_t< NE, NF > &arg) noexcept
CONSTRUCTOR COPIA pfx_rat_reg_digs_t<10,3,2> var{1,3,2,5,6}; pfx_rat_reg_digs_t<10,3,2> var2(var);
constexpr NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t(nat_reg_NExNF_digs_t< NE, NF > &&arg) noexcept
CONSTRUCTOR MOVIMIENTO pfx_rat_reg_digs_t<10,3,2> var{1,3,2,5,6}; pfx_rat_reg_digs_t<10,3,2> var2(std::move(var)); var queda no sabemos su valor
constexpr pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator=(nat_reg_NExNF_digs_t< NE, NF > &arg) noexcept
OPERACION ASIGNACION POR COPIA EN LA QUE SE PUEDE COPIAR reg_N_digs_t == std::array<dig_t,N>; pfx_rat_reg_digs_t<21,5> var{}; pfx_rat_reg_digs_t var2{}; var2 = var; var2 == var
constexpr pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator=(nat_reg_NExNF_digs_t< NE, NF > &&arg) noexcept
OPERACION ASIGNACION POR MOVIMIENTO reg_N_digs_t == std::array<dig_t,N>; pfx_rat_reg_digs_t<21,5> var{}; pfx_rat_reg_digs_t var2{}; var2 = std::move(var); var2 == antigua var; var actual no sabemos su valor;
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator=(const nat_reg_N_digs_t< NE, NF > &arg) noexcept
OPERACION ASIGNACION POR COPIA EN LA QUE NO SE PUEDE MODIFICAR EL ARGUMENTO.
constexpr pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator=(const base_NEXNF_t< NE, NF > &arg) noexcept
OPERACION ASIGNACION POR COPIA DESDE BASE_N_T.
constexpr pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator=(const dig_t &arg) noexcept
OPERACION COPIA DESDE UN DIGITO (CONVERSION) dig_t<13> a{3}; pfx_rat_reg_digs_t<13,16> A{}; A = a; A = nat#0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:3#B13
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator=(Int_Type arg) noexcept
OPERACION COPIA DESDE UN ENTERO (CONVERSION A LA BASE B) pfx_rat_reg_digs_t<16,4> var{}; var = 1324; 1324/%16 = 82|12 82/%16 = 5|2 => var == nat#5:2:12#B16
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr nat_reg_NExNF_digs_t< LE+NE, LF+NF > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::concat(const nat_reg_NExNF_digs_t< NE, NF > &arg) const noexcept
FORMACION DE UN REG_M_DIGS_T<M> DESDE EL THIS REG_DIGS_T (L) Y REG_N_DIGS_T<N> EN SUS DOS FORMAS: (*THIS)SEGUIDO(ARG) Y (ARG)SEGUIDO(*THIS) : OPERACIONES DE CONCATENACION A SU VEZ PUEDEN SER POR COPIA Y POR MOVIMIENTO CONCAT : CONCATENACION pfx_rat_reg_digs_t<23,7> var1{ dig_t(1), dig_t(2), dig_t(3), dig_t(4), dig_t(5), dig_t(6), dig_t(7) } pfx_rat_reg_digs_t<23,3> var2{ dig_t(22), dig_t(21), dig_t(20) } var1.concat(var2) == nat#1:2:3:4:5:6:7:22:21:20#B23
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr reg_N_digs_t< LE+LF+1 > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::concat(const dig_t &arg) const noexcept
CONCAT : CONCATENACION pfx_rat_reg_digs_t<23,7> var1{ dig_t(1), dig_t(2), dig_t(3), dig_t(4), dig_t(5), dig_t(6), dig_t(7) }; dig_t<23> var2{22}; var1.concat(var2) == nat#1:2:3:4:5:6:7:20#B23
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr nat_reg_NExNF_digs_t< LE+NE, LF+NF > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::concat_inv(const nat_reg_NExNF_digs_t< NE, NF > &arg) const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr reg_N_digs_t< LE+LF+1 > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::concat_inv(const dig_t &arg) const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr nat_reg_NExNF_digs_t< LE+NE, LF+NF > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::concat(nat_reg_NExNF_digs_t< NE, NF > &&arg) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr reg_N_digs_t< LE+LF+1 > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::concat(dig_t &&arg) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr nat_reg_NExNF_digs_t< LE+NE, LF+NF > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::concat_inv(nat_reg_NExNF_digs_t< NE, NF > &&arg) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr reg_N_digs_t< LE+LF+1 > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::concat_inv(dig_t &&arg) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr reg_N_digs_t< iend-ibegin > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::subreg_digs() const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr reg_N_digs_t< iend-ibegin > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::rev_subreg_digs() const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr reg_N_digs_t< iend-ibegin > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::subreg_digs_pe() const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr reg_N_digs_t< iend-ibegin > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::rev_subreg_digs_pe() const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr reg_N_digs_t< iend-ibegin > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::subreg_digs_pf() const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr reg_N_digs_t< iend-ibegin > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::rev_subreg_digs_pf() const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr Int_Type NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::IntPart() const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr bool NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator==(const nat_reg_NExNF_digs_t< NE, NF > &arg) const noexcept
pfx_rat_reg_digs_t<23,12> A; A = ... pfx_rat_reg_digs_t<23,10> B; B = ... A == B => true or false
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr bool NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator==(const pfx_rat_reg_digs_t< NE, NF > &arg) const noexcept
constexpr bool NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator!=(const nat_reg_NExNF_digs_t< NE, NF > &arg) const noexcept
pfx_rat_reg_digs_t<23,12> A; A = ... pfx_rat_reg_digs_t<23,10> B; B = ... A != B => true or false
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr bool NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator!=(const pfx_rat_reg_digs_t< NE, NF > &arg) const noexcept
constexpr bool NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<=(const nat_reg_NExNF_digs_t< NE, NF > &arg) const noexcept
pfx_rat_reg_digs_t<23,12> A; A = ... pfx_rat_reg_digs_t<23,10> B; B = ... A <= B => true or false
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr bool NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<=(const pfx_rat_reg_digs_t< NE, NF > &arg) const noexcept
constexpr bool NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator>=(const nat_reg_NExNF_digs_t< NE, NF > &arg) const noexcept
pfx_rat_reg_digs_t<23,12> A; A = ... pfx_rat_reg_digs_t<23,10> B; B = ... A >= B => true or false
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr bool NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator>=(const pfx_rat_reg_digs_t< NE, NF > &arg) const noexcept
constexpr bool NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<(const nat_reg_NExNF_digs_t< NE, NF > &arg) const noexcept
pfx_rat_reg_digs_t<23,12> A; A = ... pfx_rat_reg_digs_t<23,10> B; B = ... A < B => true or false
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr bool NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<(const pfx_rat_reg_digs_t< NE, NF > &arg) const noexcept
constexpr bool NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator>(const nat_reg_NExNF_digs_t< NE, NF > &arg) const noexcept
pfx_rat_reg_digs_t<23,12> A; A = ... pfx_rat_reg_digs_t<23,10> B; B = ... A > B => true or false
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr std::weak_ordering NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<=>(const nat_reg_NExNF_digs_t< NE, NF > &arg) const noexcept
CONSTRUCTOR COMPARACION OPERADOR SPACESHIP C++20 Comparaciones con un array estandar de otra longitud La salida devuelta es greater,less,equivalent
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr std::strong_ordering NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<=>(const pfx_rat_reg_digs_t< NE, NF > &arg) const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr const dig_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::get() const noexcept
pfx_rat_reg_digs_t A{}; I en [LE-1,-LF] A.get<LE-1>() [devuelve el digito de peso B^(LE-1)] .......... A.get<2>() [devuelve el digito de peso B^2] A.get<1>() [devuelve el digito de peso B^1] A.get<0>() [devuelve el digito de peso (B^0)==1] A.get<-1>() [devuelve el digito de peso B^-1] A.get<-2>() [devuelve el digito de peso B^-2] ........... A.get<-LF>() [devuelve el digito de peso B^-LF] MSB == MSB_E == LE-1 LSB_E == LF MSB_F == LF-1 LSB_F == 0 == LSB
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr void NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::put(const dig_t &arg) noexcept
pfx_rat_reg_digs_t A{}; A.put<2>(B-1-A.get<2>()) [pone un valor en un digito por su indice]
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr void NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::put(dig_t &&arg) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr const dig_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator[](std::int32_t idx) const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr dig_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator[](std::int32_t idx) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr UINT_T NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator()(std::int32_t idx) const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator++() noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator++(int) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator--() noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator--(int) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::mC_Bm1() noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::mC_B() noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::C_Bm1() const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::C_B() const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator!() const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator-() const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator+=(dig_t arg) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator-=(dig_t arg) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr std::array< pfx_rat_reg_digs_t, 2 > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::mult(dig_t arg) const noexcept
OPERACIONES '@'(REG_DIGS_T,DIG_T)->STD::ARRAY<REG_DIGS_T,2> '@' = MULT
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr std::array< pfx_rat_reg_digs_t, 2 > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::add(dig_t arg) const noexcept
'@' = '+'
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr std::array< pfx_rat_reg_digs_t, 2 > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::subst(dig_t arg) const noexcept
TO DO REPASAR '@' = '-'
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr auto NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator+(dig_t arg) const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr auto NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator-(dig_t arg) const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr auto NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator*(dig_t arg) const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<<(std::size_t n) const noexcept
BEGIN : OPERATORS >> >>= << <<= MULTIPLY BY THE BASE B (10)
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator<<=(std::size_t n) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator>>(std::size_t n) const noexcept
DIVIDE BY THE BASE B (/10_B)
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator>>=(std::size_t n) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::rem_B(std::size_t n) const noexcept
END : OPERATORS >> >>= << <<=.
BEGIN : "OPERATORS" REM_B^n AND M_REM_B^n REMAINDER BY THE BASE B (%10_B)
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::regd_0.
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_rem_B(std::size_t n) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator|=(const pfx_rat_reg_digs_t &arg) noexcept
BEGIN : OPERATORS | & |= &=.
REMAINDER BY THE BASE B (%10_B) END : "OPERATORS" REM_B^n AND M_REM_B^n
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator|(const pfx_rat_reg_digs_t &arg) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator&=(const pfx_rat_reg_digs_t &arg) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::m_dc.
constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator&(const pfx_rat_reg_digs_t &arg) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr std::pair< dig_t, pfx_rat_reg_digs_t > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator+(const pfx_rat_reg_digs_t &arg) const noexcept
END : OPERATORS | & |= &=.
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr std::pair< dig_t, pfx_rat_reg_digs_t > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator-(const pfx_rat_reg_digs_t &arg) const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr std::array< pfx_rat_reg_digs_t, 2 > NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator*(const pfx_rat_reg_digs_t &arg) const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator+(const base_t &arg) const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator-(const base_t &arg) const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr pfx_rat_reg_digs_t NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator*(const base_t &arg) const noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator+=(const base_t &arg) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator-=(const base_t &arg) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator*=(const base_t &arg) noexcept
References NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::pfx_rat_reg_digs_t.
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator+=(const pfx_rat_reg_digs_t &arg) noexcept
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator-=(const pfx_rat_reg_digs_t &arg) noexcept
constexpr const pfx_rat_reg_digs_t & NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::operator*=(const pfx_rat_reg_digs_t &arg) noexcept