NumRepr::reg_digs_t
using NumRepr::reg_digs_t< UINT_T, B, L >::dig_t = dig_t<UINT_T,B>
using NumRepr::reg_digs_t< UINT_T, B, L >::base_N_t = std::array<dig_t,N>
using NumRepr::reg_digs_t< UINT_T, B, L >::base_t = base_N_t<L>
using NumRepr::reg_digs_t< UINT_T, B, L >::reg_N_digs_t = reg_digs_t<UINT_T,B,N>
using NumRepr::reg_digs_t< UINT_T, B, L >::SIG_UINT_T = typename type_traits::sig_UInt_for_UInt_t<UINT_T>
using NumRepr::reg_digs_t< UINT_T, B, L >::SIG_SINT_T = typename type_traits::sig_SInt_for_UInt_t<UINT_T>
using NumRepr::reg_digs_t< UINT_T, B, L >::res_base_N_op_t = typename auxiliary_types::result_operation_t<base_N_t<N>,op,N>
using NumRepr::reg_digs_t< UINT_T, B, L >::res_base_op_t = typename auxiliary_types::result_operation_t<base_t,op,L>
const base_t *const NumRepr::reg_digs_t< UINT_T, B, L >::const_base_this() const noexcept
devolucion de punteros a la clase base
base_t * NumRepr::reg_digs_t< UINT_T, B, L >::base_this() noexcept
base_t & NumRepr::reg_digs_t< UINT_T, B, L >::r_base_cthis() noexcept
devolucion de referencias a la clase base
const base_t & NumRepr::reg_digs_t< UINT_T, B, L >::cr_base_cthis() const noexcept
devolucion de copia de la clase base
base_t NumRepr::reg_digs_t< UINT_T, B, L >::cp_base_cthis() const noexcept
reg_digs_t & NumRepr::reg_digs_t< UINT_T, B, L >::r_cthis() noexcept
devolucion de referencias de la clase actual
const reg_digs_t & NumRepr::reg_digs_t< UINT_T, B, L >::cr_cthis() const noexcept
reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::cp_cthis() const noexcept
devolucion de copia de la clase actual
dig_t NumRepr::reg_digs_t< UINT_T, B, L >::cp_cthis_at(size_t k) const noexcept
devoluciones por referencias y por copia de los elementos
dig_t & NumRepr::reg_digs_t< UINT_T, B, L >::r_cthis_at(size_t k) noexcept
const dig_t & NumRepr::reg_digs_t< UINT_T, B, L >::cr_cthis_at(size_t k) const noexcept
constexpr decltype(auto) NumRepr::reg_digs_t< UINT_T, B, L >::begin() noexcept
En este bloque hacemos esta clase wrapper como si fuese una clase derivada de base_t Para esto replicamos y sobrecargamos cada una de las funciones por defecto de std::array Nota: lo anterior se escribio cuando no era clase derivada sino un wrapper.
constexpr decltype(auto) NumRepr::reg_digs_t< UINT_T, B, L >::cbegin() const noexcept
constexpr decltype(auto) NumRepr::reg_digs_t< UINT_T, B, L >::end() noexcept
constexpr decltype(auto) NumRepr::reg_digs_t< UINT_T, B, L >::cend() const noexcept
constexpr decltype(auto) NumRepr::reg_digs_t< UINT_T, B, L >::rbegin() noexcept
constexpr decltype(auto) NumRepr::reg_digs_t< UINT_T, B, L >::crbegin() const noexcept
constexpr decltype(auto) NumRepr::reg_digs_t< UINT_T, B, L >::rend() noexcept
constexpr decltype(auto) NumRepr::reg_digs_t< UINT_T, B, L >::crend() const noexcept
constexpr size_t NumRepr::reg_digs_t< UINT_T, B, L >::size() const noexcept
constexpr size_t NumRepr::reg_digs_t< UINT_T, B, L >::max_size() const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::empty() const noexcept
constexpr dig_t NumRepr::reg_digs_t< UINT_T, B, L >::front() noexcept
constexpr dig_t const & NumRepr::reg_digs_t< UINT_T, B, L >::front() const noexcept
constexpr dig_t NumRepr::reg_digs_t< UINT_T, B, L >::back() noexcept
constexpr dig_t const & NumRepr::reg_digs_t< UINT_T, B, L >::back() const noexcept
constexpr void NumRepr::reg_digs_t< UINT_T, B, L >::fill(const dig_t &value) noexcept
constexpr void NumRepr::reg_digs_t< UINT_T, B, L >::swap(base_t &other) noexcept
References NumRepr::other.
constexpr void NumRepr::reg_digs_t< UINT_T, B, L >::reverse() noexcept
consteval NumRepr::reg_digs_t< UINT_T, B, L >::reg_digs_t() noexcept
Constructores de reg_digs_t.
Constructor por defecto (rellena de dig_t(0) todo el array)
constexpr NumRepr::reg_digs_t< UINT_T, B, L >::reg_digs_t(const std::initializer_list< dig_t > &arg) noexcept
Constructor por lista de digitos utilizando la función make_base_t.
constexpr NumRepr::reg_digs_t< UINT_T, B, L >::reg_digs_t(const Ts &... args) noexcept
Constructor por argumentos tipo dig_t: deduce el tipo.
constexpr NumRepr::reg_digs_t< UINT_T, B, L >::reg_digs_t(const base_t &rarg) noexcept
CONSTRUCTOR COPIA DESDE EL TIPO BASE.
constexpr NumRepr::reg_digs_t< UINT_T, B, L >::reg_digs_t(base_t &&rarg) noexcept
CONSTRUCTOR MOVIMIENTO DESDE EL TIPO BASE.
constexpr NumRepr::reg_digs_t< UINT_T, B, L >::reg_digs_t(const base_N_t< N > &arg) noexcept
Constructor copia desde un array cualquiera de dígitos dig_t (usando copy_arg_N<N>)
constexpr NumRepr::reg_digs_t< UINT_T, B, L >::reg_digs_t(const base_N_t< N > &&arg) noexcept
Constructor por movimiento desde un array cualquiera de dígitos dig_t (usando move_arg_N<N>)
constexpr NumRepr::reg_digs_t< UINT_T, B, L >::reg_digs_t(Ints_type ... dig_pow_i) noexcept
<summary="Constructor copia desde una sucesión de objetos enteros variádica, normalizándolos">
constexpr const reg_digs_t & NumRepr::reg_digs_t< UINT_T, B, L >::operator=(const reg_N_digs_t< N > &arg) noexcept
Sobrecarga del operador copia.
OPERACION ASIGNACION POR COPIA REFERENCIA CONST NO COPIABLE DESDE REG_N_DIGS_T EN LA IZQUIERDA
constexpr reg_digs_t & NumRepr::reg_digs_t< UINT_T, B, L >::operator=(reg_N_digs_t< N > &arg) noexcept
OPERACION ASIGNACION POR COPIA REFERENCIA DESDE REG_N_DIGS_T EN LA IZQUIERDA
constexpr const base_t & NumRepr::reg_digs_t< UINT_T, B, L >::operator=(reg_N_digs_t< N > &&arg) noexcept
OPERACION ASIGNACION POR MOVIMIENTO DESDE REGS_N_DIGS_T EN LA QUE NO SE PUEDE COPIAR
constexpr reg_digs_t & NumRepr::reg_digs_t< UINT_T, B, L >::operator=(const dig_t &arg) noexcept
OPERACION COPIA DESDE UN DIGITO (CONVERSION)
References NumRepr::reg_digs_t< UINT_T, B, L >::set_0.
constexpr const reg_digs_t & NumRepr::reg_digs_t< UINT_T, B, L >::operator=(Int_Type arg) noexcept
OPERACION COPIA DESDE UN ENTERO (CONVERSION A LA BASE B) A UN REG_DIGS_T
References NumRepr::type_traits::maxbase.
constexpr NumRepr::reg_digs_t< UINT_T, B, L >::operator Int_Type() const noexcept
SE PODRÍA HACER PARA UINT128_T.
Algunas Conversiones
References NumRepr::type_traits::maxbase.
constexpr const dig_t *const NumRepr::reg_digs_t< UINT_T, B, L >::data() const noexcept
<summary=" sobrecarga de las funciones miembro : "> constexpr const dig_t* data() const noexcept;
constexpr decltype(auto) NumRepr::reg_digs_t< UINT_T, B, L >::cpy_data() const noexcept
constexpr const dig_t & NumRepr::reg_digs_t< UINT_T, B, L >::operator[](size_t ix) const noexcept
<summary="Sobrecarga del const dig_t & operator[](size_t) const">
constexpr dig_t & NumRepr::reg_digs_t< UINT_T, B, L >::operator[](size_t ix) noexcept
<summary="Sobrecarga del dig_t & operator[](size_t)">
constexpr void NumRepr::reg_digs_t< UINT_T, B, L >::set_0() noexcept
Funciones que ponen a constantes (constexpr) los objetos base_t.
size_t <nontypeparam name="N"></nontypeparam> this
Referenced by NumRepr::m_incr, NumRepr::reg_digs_t< UINT_T, B, L >::operator=.
constexpr void NumRepr::reg_digs_t< UINT_T, B, L >::set_1() noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_1.
constexpr void NumRepr::reg_digs_t< UINT_T, B, L >::set_Bm1() noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_Bm1.
constexpr void NumRepr::reg_digs_t< UINT_T, B, L >::set_dig(dig_t d) noexcept
constexpr void NumRepr::reg_digs_t< UINT_T, B, L >::set_fill_dig(dig_t d) noexcept
constexpr void NumRepr::reg_digs_t< UINT_T, B, L >::set_fill_1() noexcept
constexpr void NumRepr::reg_digs_t< UINT_T, B, L >::set_fill_Bm1() noexcept
constexpr void NumRepr::reg_digs_t< UINT_T, B, L >::set_interval_0() noexcept
"Funciones que ponen a constantes(constexpr) los objetos un subintervalo o subrango de base_t cualquiera"
size_t <nontypeparam name="N_i"></nontypeparam> <nontypeparam name="N_pf"></nontypeparam> this OPERACION DE PONER A VALOR DIG_0 DEL ARRAY DESDE [N_0 , N_1) EN BASE_N_T<N>
constexpr void NumRepr::reg_digs_t< UINT_T, B, L >::set_interval_Bm1() noexcept
OPERACION DE PONER A VALOR DIG_Bm1 DEL ARRAY DESDE [N_0 , N_1) EN BASE_N_T<N>
constexpr void NumRepr::reg_digs_t< UINT_T, B, L >::set_interval_dig(dig_t dig) noexcept
OPERACION DE PONER A VALOR DIG DEL ARRAY DESDE [N_0 , N_1) EN BASE_T summary="Funciones comparativas con constantes tipo constexpr"> param name="this"> returns="bool">
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::is_0() const noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_sub, NumRepr::nat_reg_digs_t< UINT_T, B, L >::mult, NumRepr::nat_reg_digs_t< UINT_T, B, L >::predecrement.
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::is_1() const noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::mult.
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::is_Bm1() const noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_add, NumRepr::nat_reg_digs_t< UINT_T, B, L >::preincrement.
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::is_B() const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::is_Bp1() const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::is_B_pow_m1() const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::is_B_pow() const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::is_any_B_pow() const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::is_filled_of_1() const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::is_filled_of_Bm1() const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::is_filled_of(dig_t d) const
constexpr reg_N_digs_t<(ibegin< iend)?(iend-ibegin):(ibegin-iend)> NumRepr::reg_digs_t< UINT_T, B, L >::subregister() const noexcept
TAKE A SUBREGISTER OF A REGISTER OF DIGITS.
constexpr const reg_digs_t & NumRepr::reg_digs_t< UINT_T, B, L >::mC_Bm1() noexcept
OPERADORES ARITMETICOS C_B() C_Bm1() mC_B() mC_Bm1() operator!() operator-()
References NumRepr::reg_digs_t< UINT_T, B, L >::mC_Bm1.
Referenced by NumRepr::reg_digs_t< UINT_T, B, L >::mC_B, NumRepr::reg_digs_t< UINT_T, B, L >::mC_Bm1.
constexpr const reg_digs_t & NumRepr::reg_digs_t< UINT_T, B, L >::mC_B() noexcept
References NumRepr::reg_digs_t< UINT_T, B, L >::mC_Bm1.
constexpr reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::C_Bm1() const noexcept
Referenced by NumRepr::m_sum.
constexpr reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::C_B() const noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_sub.
constexpr reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::operator!() const noexcept
A partir de aquí no he hecho las sustituciones de const reg_digs_t & cthis{*this}; / reg_digs_t & cthis{*this}; / reg_digs_t cthis{*this}; Por las correspondientes funciones cr_cthis() / r_cthis() / cp_cthis()
constexpr reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::operator-() const noexcept
constexpr reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::operator<<(size_t n) const noexcept
OPERATORS >> >>= << <<= REM_B^n M_REM_B^n MER_B_N M_MER_B_N.
MULTIPLY BY THE BASE B (10) << <<= DIVIDE BY THE BASE B (10) >> >>= REMAINDER BY THE BASE B (10) REM_B_N M_REM_B_N MULTIPLICATIVE CARRY BY THE BASE B (10) MER_B_N M_MER_B_N
constexpr const reg_digs_t & NumRepr::reg_digs_t< UINT_T, B, L >::operator<<=(size_t n) noexcept
TODO TO DO VOY POR AQUI CON EL TEMA DE LOS CTHIS.
constexpr const reg_digs_t & NumRepr::reg_digs_t< UINT_T, B, L >::operator>>=(size_t n) noexcept
constexpr reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::operator>>(size_t n) const noexcept
constexpr reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::rem_B(size_t n) const noexcept
constexpr const reg_digs_t & NumRepr::reg_digs_t< UINT_T, B, L >::m_rem_B(size_t n) noexcept
constexpr reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::mer_B(size_t n) const noexcept
constexpr const reg_digs_t & NumRepr::reg_digs_t< UINT_T, B, L >::m_mer_B(size_t n) noexcept
constexpr const reg_digs_t & NumRepr::reg_digs_t< UINT_T, B, L >::operator|=(const base_t &rarg) const noexcept
constexpr reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::operator|(const reg_digs_t &rarg) const noexcept
constexpr const reg_digs_t & NumRepr::reg_digs_t< UINT_T, B, L >::operator&=(const reg_digs_t &rarg) noexcept
constexpr reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::operator&(const reg_digs_t &rarg) noexcept
constexpr int64_t NumRepr::reg_digs_t< UINT_T, B, L >::index_of_MSDig() const noexcept
NOS DEVUELVE EL ÍNDICE DEL DÍGITO NO 0 DE POTENCIA DE B MAS GRANDE NOS DEVUELVE 0 SI ES UN DÍGITO NO 0 NOS DEVUELVE -1 SI ES EL DÍGITO 0 CUALQUIER OTRO CASO NOS DARÁ MAYOR QUE 0
Referenced by NumRepr::fediv.
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::operator==(const dig_t &rarg) const noexcept
COMPARACIONES ENTRE BASE_T Y DIG_T EN FORMA BASE_T @ DIG_T.
SOBRECARGA DE LOS OPERADORES DE COMPARACION Y ORDEN
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::operator!=(const dig_t &rarg) const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::operator>(const dig_t &rarg) const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::operator<(const dig_t &rarg) const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::operator>=(const dig_t &rarg) const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::operator<=(const dig_t &rarg) const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::operator==(const reg_N_digs_t< M > &rarg) const noexcept
COMPARACIONES ENTRE REG_DIGS_T Y REG_N_DIGS_T HETEROGENEOS EN GENERAL EN FORMA REG_DIGS_T @ REG_N_DIGS_T<M>
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::operator!=(const reg_N_digs_t< M > &rarg) const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::operator>(const reg_N_digs_t< M > &rarg) const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::operator<(const reg_N_digs_t< M > &rarg) const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::operator>=(const reg_N_digs_t< M > &rarg) const noexcept
constexpr bool NumRepr::reg_digs_t< UINT_T, B, L >::operator<=(const reg_N_digs_t< M > &rarg) const noexcept
constexpr std::strong_ordering NumRepr::reg_digs_t< UINT_T, B, L >::operator<=>(const reg_N_digs_t< M > &arg) const noexcept
OPERADOR COMPARACION SPACESHIP C++20.
constexpr std::weak_ordering NumRepr::reg_digs_t< UINT_T, B, L >::operator<=>(const dig_t &arg) const noexcept
OPERADOR COMPARACION SPACESHIP C++20.
static consteval dig_t NumRepr::reg_digs_t< UINT_T, B, L >::dig_0() noexcept
References NumRepr::dig_t< UINT_T, B >::dig_0.
static consteval dig_t NumRepr::reg_digs_t< UINT_T, B, L >::dig_1() noexcept
References NumRepr::dig_t< UINT_T, B >::dig_1.
static consteval dig_t NumRepr::reg_digs_t< UINT_T, B, L >::dig_Bm1() noexcept
References NumRepr::dig_t< UINT_T, B >::dig_Bm1.
static consteval dig_t NumRepr::reg_digs_t< UINT_T, B, L >::dig_Bm2() noexcept
References NumRepr::dig_t< UINT_T, B >::dig_Bm2.
static consteval UINT_T NumRepr::reg_digs_t< UINT_T, B, L >::ui_0() noexcept
References NumRepr::dig_t< UINT_T, B >::ui_0.
static consteval UINT_T NumRepr::reg_digs_t< UINT_T, B, L >::ui_1() noexcept
References NumRepr::dig_t< UINT_T, B >::ui_1.
static consteval UINT_T NumRepr::reg_digs_t< UINT_T, B, L >::ui_Bm1() noexcept
static consteval UINT_T NumRepr::reg_digs_t< UINT_T, B, L >::ui_B() noexcept
static consteval SIG_UINT_T NumRepr::reg_digs_t< UINT_T, B, L >::sui_0() noexcept
References NumRepr::dig_t< UINT_T, B >::sui_0.
static consteval SIG_UINT_T NumRepr::reg_digs_t< UINT_T, B, L >::sui_1() noexcept
References NumRepr::dig_t< UINT_T, B >::sui_1.
static consteval SIG_UINT_T NumRepr::reg_digs_t< UINT_T, B, L >::sui_Bm1() noexcept
References NumRepr::dig_t< UINT_T, B >::sui_B.
static consteval SIG_UINT_T NumRepr::reg_digs_t< UINT_T, B, L >::sui_B() noexcept
References NumRepr::dig_t< UINT_T, B >::sui_B.
static consteval SIG_UINT_T NumRepr::reg_digs_t< UINT_T, B, L >::sui_Bp1() noexcept
References NumRepr::dig_t< UINT_T, B >::sui_B.
static consteval SIG_SINT_T NumRepr::reg_digs_t< UINT_T, B, L >::ssi_0() noexcept
References NumRepr::dig_t< UINT_T, B >::ssi_0.
static consteval SIG_SINT_T NumRepr::reg_digs_t< UINT_T, B, L >::ssi_1() noexcept
References NumRepr::dig_t< UINT_T, B >::ssi_1.
static consteval SIG_SINT_T NumRepr::reg_digs_t< UINT_T, B, L >::ssi_Bm1() noexcept
References NumRepr::dig_t< UINT_T, B >::ssi_B.
static consteval SIG_SINT_T NumRepr::reg_digs_t< UINT_T, B, L >::ssi_B() noexcept
References NumRepr::dig_t< UINT_T, B >::ssi_B.
static consteval SIG_SINT_T NumRepr::reg_digs_t< UINT_T, B, L >::ssi_Bp1() noexcept
References NumRepr::dig_t< UINT_T, B >::ssi_B.
static consteval base_N_t< N > NumRepr::reg_digs_t< UINT_T, B, L >::regd_base_N_0() noexcept
PARA EL TIPO-TEMPLATE BASE_N_T OBTENEMOS CONSTANTES INMEDIATAS TENEMOS CUIDADO DE CREAR UN RVALUE TEMPORAL.
static consteval base_N_t< N > NumRepr::reg_digs_t< UINT_T, B, L >::regd_base_N_1() noexcept
static consteval base_N_t< N > NumRepr::reg_digs_t< UINT_T, B, L >::regd_base_N_Bm1() noexcept
static consteval base_N_t< N > NumRepr::reg_digs_t< UINT_T, B, L >::regd_base_N_B() noexcept
static consteval base_N_t< N > NumRepr::reg_digs_t< UINT_T, B, L >::regd_base_N_pow_n_B() noexcept
static consteval base_N_t< N > NumRepr::reg_digs_t< UINT_T, B, L >::regd_base_N_pow_n_B_m1() noexcept
static consteval base_t NumRepr::reg_digs_t< UINT_T, B, L >::regd_base_0() noexcept
IDEM QUE ANTES PERO CON EL TIPO BASE_T ESPECIALIZANDO AL TIPO BASE_N_T<L> DONDE BASE_T == BASE_N_T<L> TENEMOS CUIDADO DE CREAR UN RVALUE TEMPORAL.
static consteval base_t NumRepr::reg_digs_t< UINT_T, B, L >::regd_base_1() noexcept
static consteval base_t NumRepr::reg_digs_t< UINT_T, B, L >::regd_base_Bm1() noexcept
static consteval base_t NumRepr::reg_digs_t< UINT_T, B, L >::regd_base_B() noexcept
static consteval base_t NumRepr::reg_digs_t< UINT_T, B, L >::regd_base_pow_n_B() noexcept
static consteval base_t NumRepr::reg_digs_t< UINT_T, B, L >::regd_base_pow_n_B_m1() noexcept
static consteval reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::regd_0() noexcept
IDEM QUE ANTES PERO CON LA CLASE DERIVADA, LA ACTUAL TENEMOS CUIDADO DE CREAR UN RVALUE TEMPORAL.
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_0.
static consteval reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::regd_1() noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_1.
static consteval reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::regd_Bm1() noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_Bm1.
static consteval reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::regd_B() noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_B.
static consteval reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::regd_pow_n_B() noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_pow_n_B.
static consteval reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::regd_pow_n_B_m1() noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_pow_n_B_m1.
static constexpr base_t NumRepr::reg_digs_t< UINT_T, B, L >::normalize(Ints_type ... digits_pow_i) noexcept
<summary="Funcion de normalizacion a dig_t (dígitos base B) que construye un objeto de tipo "> <summary="base_t desde una sucesion variadica de enteros cualquiera"> <function name="normalize"></function> Ints_type ... digits_pow_i <returns="base_t">
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t.
static constexpr reg_digs_t NumRepr::reg_digs_t< UINT_T, B, L >::cat(const reg_digs_t &arg) noexcept
STATIC REG_DIGS_T CAT(REG_DIGS_T)
STATIC FUNCTIONS : CONCATENATE REGISTERS AND DIGITS reg_digs_t<1> cat(dig_t) reg_digs_t<1+1> cat(dig_t,dig_t) reg_digs_t cat(reg_digs_t) <M> reg_N_digs_t<L+M> cat(reg_digs_t,reg_N_digs_t<M>) reg_N_digs_t<L+1> cat(reg_digs_t,dig_t) reg_N_digs_t<1+L> cat(dig_t,reg_digs_t) reg_N_digs_t<sizeof...(dig_pack)> cat(dig_t ... dig_pack) VARIADIC PACK
static constexpr reg_N_digs_t< L+M > NumRepr::reg_digs_t< UINT_T, B, L >::cat(const reg_digs_t &larg, const reg_N_digs_t< M > &rarg) noexcept
STATIC <M> REG_N_DIGS_T<L+M> CAT(REG_DIGS_T,REG_N_DIGS_T<M>)
static constexpr reg_N_digs_t< L+1 > NumRepr::reg_digs_t< UINT_T, B, L >::cat(const reg_digs_t &larg, dig_t rarg) noexcept
STATIC REG_DIGS_T<L+1> CAT(REG_DIGS_T,DIG_T)
static constexpr reg_N_digs_t< 1+L > NumRepr::reg_digs_t< UINT_T, B, L >::cat(dig_t larg, const reg_digs_t &rarg) noexcept
REG_N_DIGS_T<1+L> CAT(DIG_T,REG_DIGS_T)
static constexpr reg_N_digs_t< 1 > NumRepr::reg_digs_t< UINT_T, B, L >::cat(dig_t larg) noexcept
STATIC REG_N_DIGS_T<1> CAT(DIG_T)
static constexpr reg_N_digs_t< 2 > NumRepr::reg_digs_t< UINT_T, B, L >::cat(dig_t larg, dig_t rarg) noexcept
STATIC REG_N_DIGS_T<1+1> CAT(DIG_T,DIG_T)
static constexpr reg_N_digs_t< 1+(sizeof ...(Ts))> NumRepr::reg_digs_t< UINT_T, B, L >::cat(T0 dig0, Ts ... dig_pack) noexcept
STATIC REG_N_DIGS_T<SIZEOF...(DIG_PACK)> CAT(DIG_T,DIG_T ... DIG_PACK) VARIADIC
static constexpr reg_N_digs_t< L+1+(sizeof ...(Ts))> NumRepr::reg_digs_t< UINT_T, B, L >::cat(reg_digs_t larg, T dig, Ts ... dig_pack) noexcept
STATIC REG_N_DIGS_T<L+1+(SIZEOF...(DIG_PACK))> CAT(REG_DIGS_T,DIG_T,DIG_T ... DIG_PACK) VARIADIC
static constexpr reg_N_digs_t< L+1+(sizeof ...(Ts))> NumRepr::reg_digs_t< UINT_T, B, L >::cat(T dig, Ts ... dig_pack, reg_digs_t rarg) noexcept
STATIC REG_N_DIGS_T<L+1+(SIZEOF...(DIG_PACK))> CAT(DIG_T,DIG_T ... DIG_PACK,REG_DIGS_T) VARIADIC
static constexpr reg_N_digs_t< N+(...+(N_pack))> NumRepr::reg_digs_t< UINT_T, B, L >::cat(reg_N_digs_t< N > larg, reg_N_digs_t< N_pack > ... rarg_pack) noexcept
STATIC REG_N_DIGS_T<SIZE_T N,SIZE_T ... N_PACK> CAT(REG_N_DIGS_T<N> LARG, REG_N_DIGS_T<N_PACK> ... RARG_PACK ) VARIADIC PACK
static bool NumRepr::reg_digs_t< UINT_T, B, L >::is_type_template_string_id(std::string in) noexcept
el parser/lexer del reg_digs_t
Funciones de ayuda para
static std::string NumRepr::reg_digs_t< UINT_T, B, L >::to_type_template_string_id() noexcept
static size_t NumRepr::reg_digs_t< UINT_T, B, L >::size_of_type_template_string_id() noexcept
static bool NumRepr::reg_digs_t< UINT_T, B, L >::get_type_template_string_id_token(std::istream &is)
FUNCION GENERICA QUE CONSIGUE EL TOKEN TYPE PARA LA OBTENCION DEL OBJETO CORRESPONDIENTE POR TECLADO
static constexpr base_t NumRepr::reg_digs_t< UINT_T, B, L >::make_base_t(const std::initializer_list< dig_t > &larg)
Funcion miembro para generar un objeto tipo base_t y devolverlo desde un std::initializer_list<dig_t>
<function name="make_base_t"></function> const std::initializer_list<dig_t>& larg <returns="rarg : base_t">
constexpr void NumRepr::reg_digs_t< UINT_T, B, L >::copy_arg_N(const base_N_t< N > &arg) noexcept
Constructor por Copia/Movimiento desde una sucesión variadica de dígitos dig_t.
Función miembro (delegada) para copiar un objeto tipo base_t desde una referencia constante a un array cualquiera de dig_t <function name="copy_arg_N"></function> const base_N_t<N> & arg <returns="void">
constexpr void NumRepr::reg_digs_t< UINT_T, B, L >::move_arg_N(base_N_t< N > &&arg) noexcept
Función miembro (delegada) para mover un objeto tipo base_t desde una referencia derecha a un array cualquiera de dig_t.
<function name="copy_arg_N"></function> const base_N_t<N> & arg <returns="void">
constexpr dig_t * NumRepr::reg_digs_t< UINT_T, B, L >::data() noexcept
<summary=" sobrecarga de las funciones miembro : "> constexpr dig_t* data() noexcept;