details::cp_delete
static void details::cp_delete< aT, T, B >::destruye_lista_de_variables(aT *var_list)
Referenced by details::cp_delete< 2u >::contruye_lista_de_variables, details::cp_delete< aT, T, B >::operator(), details::cp_delete< aT, T, std::numeric_limits< uchint >::max()>::operator().
void details::cp_delete< aT, T, B >::operator()(aT **var_list_list)
References details::cp_delete< aT, T, B >::destruye_lista_de_variables.