details::cp_new
static aT * details::cp_new< aT, T, num_vars, B >::contruye_lista_de_variables(aT *var_list)
Referenced by details::cp_new< aT, T, num_vars, B >::operator(), details::cp_new< aT, T, std::numeric_limits< uchint >::max()>::operator(), details::cp_new< 2 >::operator().
void details::cp_new< aT, T, num_vars, B >::operator()(aT **var_list_list)
References details::cp_new< aT, T, num_vars, B >::contruye_lista_de_variables.