NumRepr::nat_reg_digs_t
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::SIG_UINT_T = typename type_traits::sig_UInt_for_UInt_t<UINT_T>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::SIG_SINT_T = typename type_traits::sig_SInt_for_UInt_t<UINT_T>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_t = dig_t<UINT_T,B>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::base_N_t = std::array<dig_t,N>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::base_t = base_N_t<L>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::res_base_N_op_t = typename auxiliary_types::result_operation_t<base_N_t<N>,op,N>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::res_base_op_t = typename auxiliary_types::result_operation_t<base_t,op,L>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_N_digs_t = nat_reg_digs_t<UINT_T,B,N>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::res_N_op_t = typename auxiliary_types::result_operation_t<nat_reg_N_digs_t<N>,op,N>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::res_op_t = typename auxiliary_types::result_operation_t<nat_reg_digs_t,op,L>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::reg_ints_t = typename std::array<UINT_T,N>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::reg_suints_t = typename std::array<SIG_UINT_T,N>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::reg_ssints_t = typename std::array<SIG_SINT_T,N>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::SIG_UINT_T = typename type_traits::sig_UInt_for_UInt_t<UINT_T>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::SIG_SINT_T = typename type_traits::sig_SInt_for_UInt_t<UINT_T>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_t = dig_t<UINT_T,B>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::base_N_t = std::array<dig_t,N>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::base_t = base_N_t<L>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::res_base_N_op_t = typename auxiliary_types::result_operation_t<base_N_t<N>,op,N>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::res_base_op_t = typename auxiliary_types::result_operation_t<base_t,op,L>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_N_digs_t = nat_reg_digs_t<UINT_T,B,N>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::res_N_op_t = typename auxiliary_types::result_operation_t<nat_reg_N_digs_t<N>,op,N>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::res_op_t = typename auxiliary_types::result_operation_t<nat_reg_digs_t,op,L>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::reg_ints_t = typename std::array<UINT_T,N>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::reg_suints_t = typename std::array<SIG_UINT_T,N>
using NumRepr::nat_reg_digs_t< UINT_T, B, L >::reg_ssints_t = typename std::array<SIG_SINT_T,N>
base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_dc
static consteval dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_0() noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_add, NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_sub, NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_0, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_pow_n_B_m1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_0.
static consteval dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1() noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_add, NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_sub, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator+=, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator-=, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_B, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_pow_n_B, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_B, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_pow_n_B.
static consteval dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_Bm1() noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_add, NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_sub, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_Bm1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_pow_n_B_m1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_Bm1.
static consteval dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_max() noexcept
static consteval dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_Bm2() noexcept
static consteval dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_submax() noexcept
static consteval UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::ui_0() noexcept
static consteval UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::ui_1() noexcept
static consteval UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::ui_Bm1() noexcept
static consteval UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::ui_B() noexcept
static consteval UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::ui_submax() noexcept
static consteval UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::ui_max() noexcept
static consteval SIG_UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::sui_0() noexcept
static consteval SIG_UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::sui_1() noexcept
static consteval SIG_UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::sui_Bm1() noexcept
static consteval SIG_UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::sui_B() noexcept
static consteval SIG_UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::sui_Bp1() noexcept
static consteval base_N_t< N > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_0() noexcept
PARA EL TIPO-TEMPLATE BASE_N_T OBTENEMOS CONSTANTES INMEDIATAS TENEMOS CUIDADO DE CREAR UN RVALUE TEMPORAL
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_0.
static consteval base_N_t< N > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1.
static consteval base_N_t< N > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_Bm1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_Bm1.
static consteval base_N_t< N > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_B() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1.
static consteval base_N_t< N > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_pow_n_B() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1.
static consteval base_N_t< N > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_pow_n_B_m1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_0, NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_Bm1.
static consteval base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_0() noexcept
IDEM QUE ANTES PERO CON EL TIPO BASE_T ESPECIALIZANDO AL TIPO BASE_N_T<L> DONDE BASE_T == BASE_N_T<L> TENEMOS CUIDADO DE CREAR UN RVALUE TEMPORAL
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_0.
static consteval base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_1() noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_1.
static consteval base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_Bm1() noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_Bm1.
static consteval base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_B() noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_B.
static consteval base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_pow_n_B() noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_pow_n_B.
static consteval base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_pow_n_B_m1() noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_pow_n_B_m1.
static consteval nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_0() noexcept
FUNCIONES INMEDIATAS QUE NOS DAN CONSTANTES DEL TIPO DE LA ACTUAL CLASE SE HACE CREANDO UNA VARIABLE RVALUE TEMPORAL CON LA FUNCION HOMOLOGA PARA BASE_T
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_0.
Referenced by NumRepr::operator>>.
static consteval nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_1.
static consteval nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_Bm1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_Bm1.
static consteval nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_B() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_B.
static consteval nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_pow_n_B() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_pow_n_B.
static consteval nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_pow_n_B_m1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_pow_n_B_m1.
static consteval reg_ints_t< L > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_0() noexcept
ARRAYS DE ENTEROS (CONSTANTES EN TIEMPO DE COMPILACION INMEDIATAS)
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_0.
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_B, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_Bm1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_pow_n_B.
static consteval reg_ints_t< L > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_0.
static consteval reg_ints_t< L > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_Bm1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_Bm1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_0.
static consteval reg_ints_t< L > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_B() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_0.
static consteval reg_ints_t< L > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_pow_n_B() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_0.
static consteval reg_ints_t< L > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_pow_n_B_m1() noexcept
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::assign(base_t &larg, Int_Type arg) noexcept
OPERACION COPIA DESDE UN ENTERO (CONVERSION A LA BASE B) A UN BASE_T.
References NumRepr::type_traits::maxbase.
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=.
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator==(const base_N_t< N > &larg, const dig_t &rarg)
COMPARACIONES ENTRE BASE_N_T Y DIG_T EN FORMA BASE_N_T<N> @ DIG_T STATIC
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator!=(const base_N_t< N > &larg, const dig_t &rarg)
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>(const base_N_t< N > &larg, const dig_t &rarg)
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<(const base_N_t< N > &larg, const dig_t &rarg)
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>=(const base_N_t< N > &larg, const dig_t &rarg)
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<=(const base_N_t< N > &larg, const dig_t &rarg)
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator==(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
COMPARACIONES ENTRE BASE_N_T Y BASE_N_T HETEROGENEOS EN GENERAL EN FORMA BASE_N_T<N> @ BASE_N_T<M> STATIC
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator!=(const base_N_t< N > &larg, const base_N_t< M > &rarg)
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>=(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<=(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
static constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_add(base_t &larg, const dig_t &rarg) -> typename std::conditional_t< with_result_type, res_base_op_t< binop_e::add >, base_t const & > noexcept
END : OPERATORS | & |= &=.
OPERACIONES BINARIAS CON/SIN TIPO RESULTADO OPERACIONES BINARIAS BASE_T @ DIG_T OPERATOR BASE_T += DIG_T CON NOMBRE M_ADDITION
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_0, NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_Bm1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_Bm1.
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_sub(base_t &larg, const dig_t &rarg) noexcept
OPERATOR BASE_T -= DIG_T CON NOMBRE M_SUB.
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_0, NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_Bm1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_0.
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::add(const base_t &larg, const dig_t &rarg) noexcept
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::sub(const base_t &larg, const dig_t &rarg) noexcept
static consteval dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_0() noexcept
static consteval dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1() noexcept
static consteval dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_Bm1() noexcept
static consteval dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_max() noexcept
static consteval dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_Bm2() noexcept
static consteval dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_submax() noexcept
static consteval UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::ui_0() noexcept
static consteval UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::ui_1() noexcept
static consteval UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::ui_Bm1() noexcept
static consteval UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::ui_B() noexcept
static consteval UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::ui_submax() noexcept
static consteval UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::ui_max() noexcept
static consteval SIG_UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::sui_0() noexcept
static consteval SIG_UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::sui_1() noexcept
static consteval SIG_UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::sui_Bm1() noexcept
static consteval SIG_UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::sui_B() noexcept
static consteval SIG_UINT_T NumRepr::nat_reg_digs_t< UINT_T, B, L >::sui_Bp1() noexcept
static consteval base_N_t< N > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_0() noexcept
PARA EL TIPO-TEMPLATE BASE_N_T OBTENEMOS CONSTANTES INMEDIATAS TENEMOS CUIDADO DE CREAR UN RVALUE TEMPORAL
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_0.
static consteval base_N_t< N > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1.
static consteval base_N_t< N > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_Bm1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_Bm1.
static consteval base_N_t< N > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_B() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1.
static consteval base_N_t< N > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_pow_n_B() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1.
static consteval base_N_t< N > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_N_pow_n_B_m1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_0, NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_Bm1.
static consteval base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_0() noexcept
IDEM QUE ANTES PERO CON EL TIPO BASE_T ESPECIALIZANDO AL TIPO BASE_N_T<L> DONDE BASE_T == BASE_N_T<L> TENEMOS CUIDADO DE CREAR UN RVALUE TEMPORAL
static consteval base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_1() noexcept
static consteval base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_Bm1() noexcept
static consteval base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_B() noexcept
static consteval base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_pow_n_B() noexcept
static consteval base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_pow_n_B_m1() noexcept
static consteval nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_0() noexcept
FUNCIONES INMEDIATAS QUE NOS DAN CONSTANTES DEL TIPO DE LA ACTUAL CLASE SE HACE CREANDO UNA VARIABLE RVALUE TEMPORAL CON LA FUNCION HOMOLOGA PARA BASE_T
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_0.
static consteval nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_1.
static consteval nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_Bm1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_Bm1.
static consteval nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_B() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_B.
static consteval nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_pow_n_B() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_pow_n_B.
static consteval nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_pow_n_B_m1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::regd_base_pow_n_B_m1.
static consteval reg_ints_t< L > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_0() noexcept
ARRAYS DE ENTEROS (CONSTANTES EN TIEMPO DE COMPILACION INMEDIATAS)
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_0.
static consteval reg_ints_t< L > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_0.
static consteval reg_ints_t< L > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_Bm1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_Bm1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_0.
static consteval reg_ints_t< L > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_B() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_0.
static consteval reg_ints_t< L > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_pow_n_B() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_0.
static consteval reg_ints_t< L > NumRepr::nat_reg_digs_t< UINT_T, B, L >::regi_pow_n_B_m1() noexcept
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::assign(base_t &larg, Int_Type arg) noexcept
OPERACION COPIA DESDE UN ENTERO (CONVERSION A LA BASE B) A UN BASE_T.
References NumRepr::type_traits::maxbase.
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator==(const base_N_t< N > &larg, const dig_t &rarg)
COMPARACIONES ENTRE BASE_N_T Y DIG_T EN FORMA BASE_N_T<N> @ DIG_T STATIC
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator!=(const base_N_t< N > &larg, const dig_t &rarg)
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>(const base_N_t< N > &larg, const dig_t &rarg)
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<(const base_N_t< N > &larg, const dig_t &rarg)
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>=(const base_N_t< N > &larg, const dig_t &rarg)
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<=(const base_N_t< N > &larg, const dig_t &rarg)
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator==(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
COMPARACIONES ENTRE BASE_N_T Y BASE_N_T HETEROGENEOS EN GENERAL EN FORMA BASE_N_T<N> @ BASE_N_T<M> STATIC
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator!=(const base_N_t< N > &larg, const base_N_t< M > &rarg)
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>=(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<=(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
static constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_add(base_t &larg, const dig_t &rarg) -> typename std::conditional_t< with_result_type, res_base_op_t< binop_e::add >, base_t const & > noexcept
END : OPERATORS | & |= &=.
OPERACIONES BINARIAS CON/SIN TIPO RESULTADO OPERACIONES BINARIAS BASE_T @ DIG_T OPERATOR BASE_T += DIG_T CON NOMBRE M_ADDITION
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_0, NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_Bm1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_Bm1.
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_sub(base_t &larg, const dig_t &rarg) noexcept
OPERATOR BASE_T -= DIG_T CON NOMBRE M_SUB.
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_0, NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_Bm1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_0.
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::add(const base_t &larg, const dig_t &rarg) noexcept
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::sub(const base_t &larg, const dig_t &rarg) noexcept
static constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::fediv(const base_N_t< N > &larg, const base_N_t< 1 > &rarg) -> res_base_N_op_t< binop_e::fediv > noexcept
consteval NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t() noexcept
CONSTRUCTOR POR DEFECTO.
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_0.
constexpr NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t(const std::initializer_list< dig_t > &arg) noexcept
CONSTRUCTOR POR LISTA DE DIGITOS.
constexpr NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t(const Ts &... args) noexcept
CONSTRUCTOR POR ARGUMENTOS DIGITOS SIN LIMITE: DEDUCE EL TIPO.
constexpr NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t(const base_N_t< N > &arg) noexcept
CONSTRUCTOR COPIA DESDE UN ARRAY DE DIGITOS.
constexpr NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t(const base_N_t< N > &&arg) noexcept
CONSTRUCTOR MOVIMIENTO DESDE UN ARRAY DE DIGITOS.
constexpr NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t(Ints_type ... dig_pow_i) noexcept
CONSTRUCTOR COPIA DESDE ARGUMENTOS ENTEROS SIN LIMITE : DEDUCE EL TIPO.
constexpr NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t(const nat_reg_N_digs_t< N > &arg) noexcept
CONSTRUCTOR COPIA POR REFERENCIA CONSTANTE.
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t(nat_reg_N_digs_t< N > &&arg) noexcept
CONSTRUCTOR POR MOVIMIENTO.
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=(const base_N_t< N > &arg) noexcept
OPERACION ASIGNACION POR COPIA REFERENCIA CONST NO COPIABLE DESDE BASE_N_T.
constexpr nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=(base_N_t< N > &arg) noexcept
OPERACION ASIGNACION POR COPIA REFERENCIA DESDE BASE_N_T.
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=(base_N_t< N > &&arg) noexcept
OPERACION ASIGNACION POR COPIA MOVIMIENTO DESDE BASE_N_T.
constexpr nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=(const nat_reg_N_digs_t< N > &arg) noexcept
OPERACION ASIGNACION POR COPIA REFERENCIA EN LA QUE SE PUEDE COPIAR.
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=(nat_reg_N_digs_t< N > &&arg) noexcept
OPERACION ASIGNACION POR MOVIMIENTO.
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=(const nat_reg_N_digs_t< N > &arg) noexcept
OPERACION ASIGNACION POR COPIA EN LA QUE NO SE PUEDE COPIAR.
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_0() noexcept
OPERACION DE LIMPIEZA A CERO DEL NAT_REG_DIGS_T.
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_0.
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=, NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_0.
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_Bm1() noexcept
OPERACION DE LIMPIEZA A B-1 DEL NAT_REG_DIGS_T.
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_Bm1.
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_Bm1.
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_dig(dig_t arg) noexcept
OPERACION DE LIMPIEZA A VALOR DIG_T DEL NAT_REG_DIGS_T.
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_0() noexcept
OPERACION DE PONER A VALOR DIG_0 EN [N_0 , N_1) DEL NAT_REG_DIGS_T.
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_Bm1() noexcept
OPERACION DE PONER A VALOR DIG_Bm1 EN [N_0 , N_1) DEL NAT_REG_DIGS_T.
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_dig(dig_t dig) noexcept
OPERACION DE PONER A VALOR DIG EN [N_0 , N_1) DEL NAT_REG_DIGS_T.
constexpr nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=(const dig_t &arg) noexcept
OPERACION COPIA DESDE UN DIGITO (CONVERSION)
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_0.
constexpr nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=(Int_Type arg) noexcept
OPERACION COPIA DESDE UN ENTERO (CONVERSION A LA BASE B)
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::assign.
constexpr nat_reg_N_digs_t< N+L > NumRepr::nat_reg_digs_t< UINT_T, B, L >::cat(const nat_reg_N_digs_t< N > &arg) const noexcept
SUBREPR => SUB REPRESENTACION.
FORMACION DE UN REG_M_DIGS_T<M> DESDE EL THIS REG_DIGS_T (L) Y REG_N_DIGS_T<N> EN SUS DOS FORMAS: (*THIS)SEGUIDO(ARG) Y (ARG)SEGUIDO(*THIS) : OPERACIONES DE CONCATENACION FORMACION DE UN REG_M_DIGS_T<M> DESDE EL THIS REG_DIGS_T (L) Y REG_N_DIGS_T<N> EN SUS DOS FORMAS: (*THIS)SEGUIDO(ARG) Y (ARG)SEGUIDO(*THIS) : OPERACIONES DE CONCATENACION NAT_REG_N_T<L+M> NAT_REG_T::CAT(NAT_REG_N_T<M>) NAT_REG_N_T<L+M> NAT_REG_T::CAT_INV(NAT_REG_N_T<M>) NAT_REG_N_T<L+1> NAT_REG_T::CAT(DIG_T) NAT_REG_N_T<L+1> NAT_REG_T::CAT_INV(DIG_T)
constexpr nat_reg_N_digs_t< L+1 > NumRepr::nat_reg_digs_t< UINT_T, B, L >::cat(dig_t arg) const noexcept
constexpr nat_reg_N_digs_t< N+L > NumRepr::nat_reg_digs_t< UINT_T, B, L >::cat_inv(const nat_reg_N_digs_t< N > &arg) const noexcept
constexpr nat_reg_N_digs_t< L+1 > NumRepr::nat_reg_digs_t< UINT_T, B, L >::cat_inv(dig_t arg) const noexcept
constexpr nat_reg_N_digs_t< iend-ibegin > NumRepr::nat_reg_digs_t< UINT_T, B, L >::subrepr() const noexcept
constexpr NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator Int_Type() const noexcept
References NumRepr::type_traits::maxbase.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_0() const
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_0.
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_0, NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_sub.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_1() const
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_1.
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_1.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_Bm1() const
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_Bm1.
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_Bm1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_add.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_B() const
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_B.
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_B.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_Bp1() const
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_Bp1.
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_Bp1.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_B_pow_m1() const
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_B_pow() const
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_filled_of_1() const
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_filled_of_Bm1() const
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_filled_of() const
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator==(const base_N_t< N > &arg) const noexcept
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator==(const nat_reg_N_digs_t< N > &arg) const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator!=(const base_N_t< N > &arg) const noexcept
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator!=(const nat_reg_N_digs_t< N > &arg) const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<=(const base_N_t< N > &arg) const noexcept
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<=(const nat_reg_N_digs_t< N > &arg) const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>=(const base_N_t< N > &arg) const noexcept
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>=(const nat_reg_N_digs_t< N > &arg) const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<(const base_N_t< N > &arg) const noexcept
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<(const nat_reg_N_digs_t< N > &arg) const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>(const base_N_t< N > &arg) const noexcept
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>(const nat_reg_N_digs_t< N > &arg) const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr std::strong_ordering NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<=>(const nat_reg_N_digs_t< N > &arg) const noexcept
OPERADOR COMPARACION SPACESHIP C++20.
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr std::weak_ordering NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<=>(const base_N_t< N > &arg) const noexcept
OPERADOR COMPARACION SPACESHIP C++20.
constexpr std::weak_ordering NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<=>(const dig_t &arg) const noexcept
OPERADOR COMPARACION SPACESHIP C++20.
constexpr dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::get() const noexcept
constexpr dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::put(dig_t arg) noexcept
constexpr dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator[](size_t idx) const noexcept
constexpr dig_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator[](size_t idx) noexcept
constexpr Int_Type NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator()(size_t idx) const noexcept
constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data() const
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator!=, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<=, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<=>, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator==, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>=.
constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::cpy_data() const
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator++() noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator++(int) noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator--() noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator--(int) noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::mC_B() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::mC_B.
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::mC_B.
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::mC_Bm1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::mC_Bm1.
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::mC_Bm1.
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_Bm1() const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_Bm1.
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_Bm1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator!.
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_B() const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_B.
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_B, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator-.
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator!() const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_Bm1.
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator-() const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_B.
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<<(size_t n) const noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<<=(size_t n) noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>>(size_t n) const noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>>=(size_t n) noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::rem_B(size_t n) const noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_rem_B(size_t n) noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::mer_B(size_t n) const noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_mer_B(size_t n) noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator|=(const nat_reg_digs_t &arg) noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator|(const nat_reg_digs_t &arg) noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator&=(const nat_reg_digs_t &arg) noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator&(const nat_reg_digs_t &arg) noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator+=(const dig_t &rarg) noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator-=(const dig_t &rarg) noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator+(const dig_t &rarg) noexcept
References NumRepr::add.
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator-(const dig_t &rarg) noexcept
References NumRepr::sub.
consteval NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t() noexcept
CONSTRUCTOR POR DEFECTO.
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_0.
constexpr NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t(const std::initializer_list< dig_t > &arg) noexcept
CONSTRUCTOR POR LISTA DE DIGITOS.
constexpr NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t(const Ts &... args) noexcept
CONSTRUCTOR POR ARGUMENTOS DIGITOS SIN LIMITE: DEDUCE EL TIPO.
constexpr NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t(const base_N_t< N > &arg) noexcept
CONSTRUCTOR COPIA DESDE UN ARRAY DE DIGITOS.
constexpr NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t(const base_N_t< N > &&arg) noexcept
CONSTRUCTOR MOVIMIENTO DESDE UN ARRAY DE DIGITOS.
constexpr NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t(Ints_type ... dig_pow_i) noexcept
CONSTRUCTOR COPIA DESDE ARGUMENTOS ENTEROS SIN LIMITE : DEDUCE EL TIPO.
constexpr NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t(const nat_reg_N_digs_t< N > &arg) noexcept
CONSTRUCTOR COPIA POR REFERENCIA CONSTANTE.
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t(nat_reg_N_digs_t< N > &&arg) noexcept
CONSTRUCTOR POR MOVIMIENTO.
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=(const base_N_t< N > &arg) noexcept
OPERACION ASIGNACION POR COPIA REFERENCIA CONST NO COPIABLE DESDE BASE_N_T.
constexpr nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=(base_N_t< N > &arg) noexcept
OPERACION ASIGNACION POR COPIA REFERENCIA DESDE BASE_N_T.
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=(base_N_t< N > &&arg) noexcept
OPERACION ASIGNACION POR COPIA MOVIMIENTO DESDE BASE_N_T.
constexpr nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=(const nat_reg_N_digs_t< N > &arg) noexcept
OPERACION ASIGNACION POR COPIA REFERENCIA EN LA QUE SE PUEDE COPIAR.
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=(nat_reg_N_digs_t< N > &&arg) noexcept
OPERACION ASIGNACION POR MOVIMIENTO.
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=(const nat_reg_N_digs_t< N > &arg) noexcept
OPERACION ASIGNACION POR COPIA EN LA QUE NO SE PUEDE COPIAR.
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_0() noexcept
OPERACION DE LIMPIEZA A CERO DEL NAT_REG_DIGS_T.
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_0.
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_Bm1() noexcept
OPERACION DE LIMPIEZA A B-1 DEL NAT_REG_DIGS_T.
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_Bm1.
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_dig(dig_t arg) noexcept
OPERACION DE LIMPIEZA A VALOR DIG_T DEL NAT_REG_DIGS_T.
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_0() noexcept
OPERACION DE PONER A VALOR DIG_0 EN [N_0 , N_1) DEL NAT_REG_DIGS_T.
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_Bm1() noexcept
OPERACION DE PONER A VALOR DIG_Bm1 EN [N_0 , N_1) DEL NAT_REG_DIGS_T.
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_dig(dig_t dig) noexcept
OPERACION DE PONER A VALOR DIG EN [N_0 , N_1) DEL NAT_REG_DIGS_T.
constexpr nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=(const dig_t &arg) noexcept
OPERACION COPIA DESDE UN DIGITO (CONVERSION)
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_0.
constexpr nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=(Int_Type arg) noexcept
OPERACION COPIA DESDE UN ENTERO (CONVERSION A LA BASE B)
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::assign.
constexpr nat_reg_N_digs_t< N+L > NumRepr::nat_reg_digs_t< UINT_T, B, L >::cat(const nat_reg_N_digs_t< N > &arg) const noexcept
SUBREPR => SUB REPRESENTACION.
FORMACION DE UN REG_M_DIGS_T<M> DESDE EL THIS REG_DIGS_T (L) Y REG_N_DIGS_T<N> EN SUS DOS FORMAS: (*THIS)SEGUIDO(ARG) Y (ARG)SEGUIDO(*THIS) : OPERACIONES DE CONCATENACION FORMACION DE UN REG_M_DIGS_T<M> DESDE EL THIS REG_DIGS_T (L) Y REG_N_DIGS_T<N> EN SUS DOS FORMAS: (*THIS)SEGUIDO(ARG) Y (ARG)SEGUIDO(*THIS) : OPERACIONES DE CONCATENACION NAT_REG_N_T<L+M> NAT_REG_T::CAT(NAT_REG_N_T<M>) NAT_REG_N_T<L+M> NAT_REG_T::CAT_INV(NAT_REG_N_T<M>) NAT_REG_N_T<L+1> NAT_REG_T::CAT(DIG_T) NAT_REG_N_T<L+1> NAT_REG_T::CAT_INV(DIG_T)
constexpr nat_reg_N_digs_t< L+1 > NumRepr::nat_reg_digs_t< UINT_T, B, L >::cat(dig_t arg) const noexcept
constexpr nat_reg_N_digs_t< N+L > NumRepr::nat_reg_digs_t< UINT_T, B, L >::cat_inv(const nat_reg_N_digs_t< N > &arg) const noexcept
constexpr nat_reg_N_digs_t< L+1 > NumRepr::nat_reg_digs_t< UINT_T, B, L >::cat_inv(dig_t arg) const noexcept
constexpr nat_reg_N_digs_t< iend-ibegin > NumRepr::nat_reg_digs_t< UINT_T, B, L >::subrepr() const noexcept
constexpr NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator Int_Type() const noexcept
References NumRepr::type_traits::maxbase.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_0() const
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_0.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_1() const
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_1.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_Bm1() const
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_Bm1.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_B() const
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_B.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_Bp1() const
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_Bp1.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_B_pow_m1() const
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_B_pow() const
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_filled_of_1() const
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_filled_of_Bm1() const
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_filled_of() const
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator==(const base_N_t< N > &arg) const noexcept
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator==(const nat_reg_N_digs_t< N > &arg) const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator!=(const base_N_t< N > &arg) const noexcept
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator!=(const nat_reg_N_digs_t< N > &arg) const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<=(const base_N_t< N > &arg) const noexcept
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<=(const nat_reg_N_digs_t< N > &arg) const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>=(const base_N_t< N > &arg) const noexcept
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>=(const nat_reg_N_digs_t< N > &arg) const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<(const base_N_t< N > &arg) const noexcept
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<(const nat_reg_N_digs_t< N > &arg) const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>(const base_N_t< N > &arg) const noexcept
constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>(const nat_reg_N_digs_t< N > &arg) const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr std::strong_ordering NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<=>(const nat_reg_N_digs_t< N > &arg) const noexcept
OPERADOR COMPARACION SPACESHIP C++20.
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data.
constexpr std::weak_ordering NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<=>(const base_N_t< N > &arg) const noexcept
OPERADOR COMPARACION SPACESHIP C++20.
constexpr std::weak_ordering NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<=>(const dig_t &arg) const noexcept
OPERADOR COMPARACION SPACESHIP C++20.
constexpr dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::get() const noexcept
constexpr dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::put(dig_t arg) noexcept
constexpr dig_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator[](size_t idx) const noexcept
constexpr dig_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator[](size_t idx) noexcept
constexpr Int_Type NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator()(size_t idx) const noexcept
constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::const_ref_data() const
constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::cpy_data() const
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator++() noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator++(int) noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator--() noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator--(int) noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::mC_B() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::mC_B.
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::mC_Bm1() noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::mC_Bm1.
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_Bm1() const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_Bm1.
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_B() const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_B.
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator!() const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_Bm1.
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator-() const noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_B.
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<<(size_t n) const noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<<=(size_t n) noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>>(size_t n) const noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>>=(size_t n) noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::rem_B(size_t n) const noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_rem_B(size_t n) noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::mer_B(size_t n) const noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_mer_B(size_t n) noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator|=(const nat_reg_digs_t &arg) noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator|(const nat_reg_digs_t &arg) noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator&=(const nat_reg_digs_t &arg) noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator&(const nat_reg_digs_t &arg) noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator+=(const dig_t &rarg) noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator-=(const dig_t &rarg) noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator+(const dig_t &rarg) noexcept
References NumRepr::add.
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator-(const dig_t &rarg) noexcept
References NumRepr::sub.
constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator+(dig_t arg) const noexcept
constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator-(dig_t arg) const noexcept
constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator*(dig_t arg) const noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator/(dig_t arg) const noexcept
DIVISION BY A DIGIT.
References NumRepr::fediv.
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator%(dig_t arg) const noexcept
REMAINDER BY A DIGIT.
References NumRepr::fediv.
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator+=(const base_N_t< N > &arg) noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1.
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator+=(const nat_reg_N_digs_t< N > &arg) noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator-=(const base_N_t< N > &arg) noexcept
References NumRepr::nat_reg_digs_t< UINT_T, B, L >::dig_1.
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator-=(const nat_reg_N_digs_t< N > &arg) noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator*=(const base_N_t< N > &arg) noexcept
constexpr const nat_reg_digs_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator*=(const nat_reg_N_digs_t< N > &arg) noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator+(const base_N_t< N > &arg) const noexcept
TO DO.
TO DO
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator-(const base_N_t< N > &arg) const noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator*(const base_N_t< N > &arg) const noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator+(const nat_reg_N_digs_t< N > &arg) const noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator-(const nat_reg_N_digs_t< N > &arg) const noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator*(const nat_reg_N_digs_t< N > &arg) const noexcept
constexpr nat_reg_digs_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator%(const nat_reg_digs_t &arg) const noexcept
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::copy_arg_N(const base_N_t< N > &arg) noexcept
BEGIN : CONSTRUCTOR COPIA/MOVIMIENTO DESDE UN ARRAY DE DIGITOS FUNCION DELEGADA PARA COPIA DE UN ARRAY DEL MISMO TAMANO O UN TAMANO CUALQUIERA "N"
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::move_arg_N(base_N_t< N > &&arg) noexcept
FUNCION DELEGADA PARA MOVER DE UN ARRAY DEL MISMO TAMANO O UN TAMANO CUALQUIERA "N"
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::copy_arg_N(const nat_reg_n_digs_t< N > &arg) noexcept
FUNCION DELEGADA PARA COPIA DE UN NAT_REG_N_DIGS_T DEL MISMO TAMANO O UN TAMANO CUALQUIERA "N"
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::move_arg_N(nat_reg_n_digs_t< N > &&arg) noexcept
FUNCION DELEGADA PARA MOVER DE UN NAT_REG_N_DIGS_T DEL MISMO TAMANO O UN TAMANO CUALQUIERA "N"
constexpr base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::ref_data() const
constexpr base_t * NumRepr::nat_reg_digs_t< UINT_T, B, L >::data() const
constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::predecrement(base_t &arg) -> std::conditional< with_result_type, res_base_op_t< binop_e::sub >, const base_t & > noexcept
constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::postdecrement(base_t &arg) -> std::conditional< with_result_type, res_base_op_t< binop_e::sub >, const base_t & > noexcept
constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::mult(dig_t arg) const -> std::conditional_t< with_result_type, res_base_op_t< binop_e::mult >, const base_t & > noexcept
OPERACIONES '@'(REG_DIGS_T,DIG_T)->RESULT_TYPE<'@'> '@' = MULT
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::copy_arg_N(const base_N_t< N > &arg) noexcept
BEGIN : CONSTRUCTOR COPIA/MOVIMIENTO DESDE UN ARRAY DE DIGITOS FUNCION DELEGADA PARA COPIA DE UN ARRAY DEL MISMO TAMANO O UN TAMANO CUALQUIERA "N"
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::move_arg_N(base_N_t< N > &&arg) noexcept
FUNCION DELEGADA PARA MOVER DE UN ARRAY DEL MISMO TAMANO O UN TAMANO CUALQUIERA "N"
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::copy_arg_N(const nat_reg_n_digs_t< N > &arg) noexcept
FUNCION DELEGADA PARA COPIA DE UN NAT_REG_N_DIGS_T DEL MISMO TAMANO O UN TAMANO CUALQUIERA "N"
constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::move_arg_N(nat_reg_n_digs_t< N > &&arg) noexcept
FUNCION DELEGADA PARA MOVER DE UN NAT_REG_N_DIGS_T DEL MISMO TAMANO O UN TAMANO CUALQUIERA "N"
constexpr base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::ref_data() const
constexpr base_t * NumRepr::nat_reg_digs_t< UINT_T, B, L >::data() const
constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::predecrement(base_t &arg) -> std::conditional< with_result_type, res_base_op_t< binop_e::sub >, const base_t & > noexcept
constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::postdecrement(base_t &arg) -> std::conditional< with_result_type, res_base_op_t< binop_e::sub >, const base_t & > noexcept
constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::mult(dig_t arg) const -> std::conditional_t< with_result_type, res_base_op_t< binop_e::mult >, const base_t & > noexcept
OPERACIONES '@'(REG_DIGS_T,DIG_T)->RESULT_TYPE<'@'> '@' = MULT
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::normalize(Ints_type ... digits_pow_i) noexcept
END : CONSTRUCTOR COPIA/MOVIMIENTO DESDE UN ARRAY DE DIGITOS.
FUNCION DE NORMALIZACION A LA BASE B DE UN ARGUMENTOS EN UN PACK DE ENTEROS CUALQUIERA
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_0(base_N_t &arg) noexcept
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_1(base_N_t &arg) noexcept
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_Bm1(base_N_t &arg) noexcept
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_dig(base_N_t &larg, dig_t d) noexcept
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_fill_dig(base_N_t &larg, dig_t d) noexcept
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_fill_1(base_N_t &larg) noexcept
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_fill_Bm1(base_N_t &larg) noexcept
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_0(base_N_t< N > &larg) noexcept
OPERACION DE PONER A VALOR DIG_0 DEL ARRAY DESDE [N_0 , N_1) EN BASE_N_T<N>
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_Bm1(base_N_t< N > &larg) noexcept
OPERACION DE PONER A VALOR DIG_Bm1 DEL ARRAY DESDE [N_0 , N_1) EN BASE_N_T<N>
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_dig(base_N_t< N > &larg, dig_t dig) noexcept
OPERACION DE PONER A VALOR DIG DEL ARRAY DESDE [N_0 , N_1) EN BASE_N_T<N>
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_0(base_t &larg) noexcept
OPERACION DE PONER A VALOR DIG_0 DEL ARRAY DESDE [N_0 , N_1) EN BASE_T ESPECIALIZACION PARA N==L
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_Bm1(base_t &larg) noexcept
OPERACION DE PONER A VALOR DIG_Bm1 DEL ARRAY DESDE [N_0 , N_1) EN BASE_T ESPECIALIZACION PARA N==L
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_dig(base_t &larg, dig_t dig) noexcept
OPERACION DE PONER A VALOR DIG DEL ARRAY DESDE [N_0 , N_1) EN BASE_T ESPECIALIZACION PARA N==L
static constexpr base_N_t< N > NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(const base_N_t< N > &larg) noexcept
STATIC BASE_N_T<N> CONCAT(BASE_N_T<N>)
STATIC BASE_N_T<N> CONCAT(BASE_N_T<N>) STATIC BASE_N_T<N+M> CONCAT(BASE_N_T<N>,BASE_N_T<M>) STATIC BASE_N_T<N+1> CONCAT(BASE_N_T<N>,DIG_T) STATIC BASE_N_T<1+M> CONCAT(DIG_T,BASE_N_T<M>) STATIC BASE_N_T<1> CONCAT(DIG_T) STATIC BASE_N_T<1+1> CONCAT(DIG_T,DIG_T) STATIC BASE_N_T<SIZEOF...(DIG_PACK)> CONCAT(DIG_T ... DIG_PACK) VARIADIC PACK
static constexpr base_N_t< N+M > NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
STATIC BASE_N_T<N+M> CONCAT(BASE_N_T<N>,BASE_N_T<M>)
static constexpr base_N_t< N+1 > NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(const base_N_t< N > &larg, dig_t rarg) noexcept
STATIC BASE_N_T<N+1> CONCAT(BASE_N_T<N>,DIG_T)
static constexpr base_N_t< 1+M > NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(dig_t larg, const base_N_t< M > &rarg) noexcept
STATIC BASE_N_T<1+M> CONCAT(DIG_T,BASE_N_T<M>)
static constexpr base_N_t< 1 > NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(dig_t larg) noexcept
STATIC BASE_N_T<1> CONCAT(DIG_T)
static constexpr base_N_t< 2 > NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(dig_t larg, dig_t rarg) noexcept
STATIC BASE_N_T<1+1> CONCAT(DIG_T,DIG_T)
static constexpr base_N_t< 1+(sizeof ...(Ts))> NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(T0 dig0, Ts ... dig_pack) noexcept
STATIC BASE_N_T<SIZEOF...(DIG_PACK)> CONCAT(DIG_T,DIG_T ... DIG_PACK) VARIADIC.
static constexpr base_N_t< N+1+(sizeof ...(Ts))> NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(base_N_t< N > larg, T dig, Ts ... dig_pack) noexcept
STATIC BASE_N_T<N+1+(SIZEOF...(DIG_PACK))> CONCAT(BASE_N_T<N>,DIG_T,DIG_T ... DIG_PACK) VARIADIC.
static constexpr base_N_t< M+1+(sizeof ...(Ts))> NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(T dig, Ts ... dig_pack, base_N_t< M > rarg) noexcept
STATIC BASE_N_T<M+1+(SIZEOF...(DIG_PACK))> CONCAT(DIG_T,DIG_T ... DIG_PACK,BASE_N_T<M>) VARIADIC.
static constexpr base_N_t< N+(...+(N_pack))> NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(base_N_t< N > larg, base_N_t< N_pack... > ... rarg_pack) noexcept
STATIC BASE_N_T<SIZE_T N,SIZE_T ... N_PACK> CONCAT(BASE_N_T<N> LARG,BASE_N_T<N_PACK> ... RARG_PACK) VARIADIC.
static constexpr base_N_t< std::abs< size_t >(iend-ibegin)> NumRepr::nat_reg_digs_t< UINT_T, B, L >::subregister(const base_N_t< N > &arg) noexcept
TAKE A SUBREGISTER OF A REGISTER OF DIGITS.
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_0(const base_N_t< N > &arg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_1(const base_N_t< N > &arg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_Bm1(const base_N_t< N > &arg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_B(const base_N_t< N > &arg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_Bp1(const base_N_t< N > &arg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_B_pow_m1(const base_N_t< N > &arg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_B_pow(const base_N_t< N > &arg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_filled_of_1(const base_N_t< N > &arg)
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_filled_of_Bm1(const base_N_t< N > &arg)
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_filled_of(const base_N_t< N > &arg)
static constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::preincrement(base_t &arg) -> std::conditional_t< with_result_type, res_base_op_t< binop_e::add >, const base_t & > noexcept
<! TODO : ME HE QUEDADO REPASANDO POR AQUI 31/23/18/11/2022
< PREINCREMENT(OBJ) == ++OBJ SOLO QUE DEVUELVE CARRY TAMBIEN PREINCREMENT(OBJ) -> CONDICIONALMENTE BIEN RES_BASE_OP_T (con CARRY), BIEN BASE_T (sin CARRY) < result_content_low result_content_high carry borrow result_content_quotient result_content_remainder good_result
static constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::postincrement(base_t &arg) -> std::conditional< with_result_type, res_base_op_t< binop_e::add >, const base_t & > noexcept
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::mC_Bm1(base_t &arg) noexcept
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::mC_B(base_t &arg) noexcept
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_Bm1(const base_t &arg) noexcept
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_B(const base_t &arg) noexcept
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<<(const base_t &larg, size_t n) noexcept
BEGIN : OPERATORS >> >>= << <<= REM_B^n M_REM_B^n MER_B_N M_MER_B_N.
MULTIPLY BY THE BASE B (10) << <<= DIVIDE BY THE BASE B (10) >> >>= REMAINDER BY THE BASE B (10) REM_B_N M_REM_B_N MULTIPLICATIVE CARRY BY THE BASE B (10) MER_B_N M_MER_B_N
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<<=(base_t &larg, size_t n) noexcept
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>>=(base_t &larg, size_t n) noexcept
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>>(const base_t &larg, size_t n) noexcept
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::rem_B(const base_t &larg, size_t n) noexcept
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_rem_B(base_t &larg, size_t n) noexcept
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::mer_B(const base_t &larg, size_t n) noexcept
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_mer_B(base_t &larg, size_t n) noexcept
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator|=(base_t &larg, const base_t &rarg) noexcept
END : OPERATORS >> >>= << <<= REM_B^n M_REM_B^n MER_B_N M_MER_B_N.
BEGIN : OPERATORS | & |= &=
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator|(const base_t &larg, const base_t &rarg) noexcept
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator&=(base_t &larg, const base_t &rarg) noexcept
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator&(base_t &larg, const base_t &rarg) noexcept
static constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::fediv(const base_t &larg, const dig_t &rarg) -> res_base_op_t< binop_e::fediv > noexcept
'@' = FULL_EUCLID_DIV(BASE_T,DIG_T) -> (REM,COC,GOOD)
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::normalize(Ints_type ... digits_pow_i) noexcept
END : CONSTRUCTOR COPIA/MOVIMIENTO DESDE UN ARRAY DE DIGITOS.
FUNCION DE NORMALIZACION A LA BASE B DE UN ARGUMENTOS EN UN PACK DE ENTEROS CUALQUIERA
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_0(base_N_t &arg) noexcept
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_1(base_N_t &arg) noexcept
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_Bm1(base_N_t &arg) noexcept
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_dig(base_N_t &larg, dig_t d) noexcept
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_fill_dig(base_N_t &larg, dig_t d) noexcept
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_fill_1(base_N_t &larg) noexcept
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_fill_Bm1(base_N_t &larg) noexcept
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_0(base_N_t< N > &larg) noexcept
OPERACION DE PONER A VALOR DIG_0 DEL ARRAY DESDE [N_0 , N_1) EN BASE_N_T<N>
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_Bm1(base_N_t< N > &larg) noexcept
OPERACION DE PONER A VALOR DIG_Bm1 DEL ARRAY DESDE [N_0 , N_1) EN BASE_N_T<N>
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_dig(base_N_t< N > &larg, dig_t dig) noexcept
OPERACION DE PONER A VALOR DIG DEL ARRAY DESDE [N_0 , N_1) EN BASE_N_T<N>
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_0(base_t &larg) noexcept
OPERACION DE PONER A VALOR DIG_0 DEL ARRAY DESDE [N_0 , N_1) EN BASE_T ESPECIALIZACION PARA N==L
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_Bm1(base_t &larg) noexcept
OPERACION DE PONER A VALOR DIG_Bm1 DEL ARRAY DESDE [N_0 , N_1) EN BASE_T ESPECIALIZACION PARA N==L
static constexpr void NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_dig(base_t &larg, dig_t dig) noexcept
OPERACION DE PONER A VALOR DIG DEL ARRAY DESDE [N_0 , N_1) EN BASE_T ESPECIALIZACION PARA N==L
static constexpr base_N_t< N > NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(const base_N_t< N > &larg) noexcept
STATIC BASE_N_T<N> CONCAT(BASE_N_T<N>)
STATIC BASE_N_T<N> CONCAT(BASE_N_T<N>) STATIC BASE_N_T<N+M> CONCAT(BASE_N_T<N>,BASE_N_T<M>) STATIC BASE_N_T<N+1> CONCAT(BASE_N_T<N>,DIG_T) STATIC BASE_N_T<1+M> CONCAT(DIG_T,BASE_N_T<M>) STATIC BASE_N_T<1> CONCAT(DIG_T) STATIC BASE_N_T<1+1> CONCAT(DIG_T,DIG_T) STATIC BASE_N_T<SIZEOF...(DIG_PACK)> CONCAT(DIG_T ... DIG_PACK) VARIADIC PACK
static constexpr base_N_t< N+M > NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(const base_N_t< N > &larg, const base_N_t< M > &rarg) noexcept
STATIC BASE_N_T<N+M> CONCAT(BASE_N_T<N>,BASE_N_T<M>)
static constexpr base_N_t< N+1 > NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(const base_N_t< N > &larg, dig_t rarg) noexcept
STATIC BASE_N_T<N+1> CONCAT(BASE_N_T<N>,DIG_T)
static constexpr base_N_t< 1+M > NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(dig_t larg, const base_N_t< M > &rarg) noexcept
STATIC BASE_N_T<1+M> CONCAT(DIG_T,BASE_N_T<M>)
static constexpr base_N_t< 1 > NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(dig_t larg) noexcept
STATIC BASE_N_T<1> CONCAT(DIG_T)
static constexpr base_N_t< 2 > NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(dig_t larg, dig_t rarg) noexcept
STATIC BASE_N_T<1+1> CONCAT(DIG_T,DIG_T)
static constexpr base_N_t< 1+(sizeof ...(Ts))> NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(T0 dig0, Ts ... dig_pack) noexcept
STATIC BASE_N_T<SIZEOF...(DIG_PACK)> CONCAT(DIG_T,DIG_T ... DIG_PACK) VARIADIC.
static constexpr base_N_t< N+1+(sizeof ...(Ts))> NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(base_N_t< N > larg, T dig, Ts ... dig_pack) noexcept
STATIC BASE_N_T<N+1+(SIZEOF...(DIG_PACK))> CONCAT(BASE_N_T<N>,DIG_T,DIG_T ... DIG_PACK) VARIADIC.
static constexpr base_N_t< M+1+(sizeof ...(Ts))> NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(T dig, Ts ... dig_pack, base_N_t< M > rarg) noexcept
STATIC BASE_N_T<M+1+(SIZEOF...(DIG_PACK))> CONCAT(DIG_T,DIG_T ... DIG_PACK,BASE_N_T<M>) VARIADIC.
static constexpr base_N_t< N+(...+(N_pack))> NumRepr::nat_reg_digs_t< UINT_T, B, L >::concat(base_N_t< N > larg, base_N_t< N_pack... > ... rarg_pack) noexcept
STATIC BASE_N_T<SIZE_T N,SIZE_T ... N_PACK> CONCAT(BASE_N_T<N> LARG,BASE_N_T<N_PACK> ... RARG_PACK) VARIADIC.
static constexpr base_N_t< std::abs< size_t >(iend-ibegin)> NumRepr::nat_reg_digs_t< UINT_T, B, L >::subregister(const base_N_t< N > &arg) noexcept
TAKE A SUBREGISTER OF A REGISTER OF DIGITS.
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_0(const base_N_t< N > &arg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_1(const base_N_t< N > &arg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_Bm1(const base_N_t< N > &arg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_B(const base_N_t< N > &arg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_Bp1(const base_N_t< N > &arg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_B_pow_m1(const base_N_t< N > &arg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_B_pow(const base_N_t< N > &arg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_any_B_pow(const base_N_t< N > &arg) noexcept
static constexpr int32_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::index_of_MSDig(const base_N_t< N > &arg) noexcept
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_filled_of_1(const base_N_t< N > &arg)
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_filled_of_Bm1(const base_N_t< N > &arg)
static constexpr bool NumRepr::nat_reg_digs_t< UINT_T, B, L >::is_filled_of(const base_N_t< N > &arg)
static constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::preincrement(base_t &arg) -> std::conditional_t< with_result_type, res_base_op_t< binop_e::add >, const base_t & > noexcept
<! TODO : ME HE QUEDADO REPASANDO POR AQUI 31/23/18/11/2022
< PREINCREMENT(OBJ) == ++OBJ SOLO QUE DEVUELVE CARRY TAMBIN PREINCREMENT(OBJ) -> CONDICIONALMENTE BIEN RES_BASE_OP_T (con CARRY), BIEN BASE_T (sin CARRY) < result_content_low result_content_high carry borrow result_content_quotient result_content_remainder good_result
static constexpr auto NumRepr::nat_reg_digs_t< UINT_T, B, L >::postincrement(base_t &arg) -> std::conditional< with_result_type, res_base_op_t< binop_e::add >, const base_t & > noexcept
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::mC_Bm1(base_t &arg) noexcept
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::mC_B(base_t &arg) noexcept
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_Bm1(const base_t &arg) noexcept
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::C_B(const base_t &arg) noexcept
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<<(const base_t &larg, size_t n) noexcept
BEGIN : OPERATORS >> >>= << <<= REM_B^n M_REM_B^n MER_B_N M_MER_B_N.
MULTIPLY BY THE BASE B (10) << <<= DIVIDE BY THE BASE B (10) >> >>= REMAINDER BY THE BASE B (10) REM_B_N M_REM_B_N MULTIPLICATIVE CARRY BY THE BASE B (10) MER_B_N M_MER_B_N
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator<<=(base_t &larg, size_t n) noexcept
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>>=(base_t &larg, size_t n) noexcept
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator>>(const base_t &larg, size_t n) noexcept
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::rem_B(const base_t &larg, size_t n) noexcept
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_rem_B(base_t &larg, size_t n) noexcept
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::mer_B(const base_t &larg, size_t n) noexcept
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_mer_B(base_t &larg, size_t n) noexcept
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator|=(base_t &larg, const base_t &rarg) noexcept
END : OPERATORS >> >>= << <<= REM_B^n M_REM_B^n MER_B_N M_MER_B_N.
BEGIN : OPERATORS | & |= &=
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator|(const base_t &larg, const base_t &rarg) noexcept
static constexpr const base_t & NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator&=(base_t &larg, const base_t &rarg) noexcept
static constexpr base_t NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator&(base_t &larg, const base_t &rarg) noexcept
static constexpr base_N_t< N > NumRepr::nat_reg_digs_t< UINT_T, B, L >::aprox_units_divB(const base_N_t< N > &arg) noexcept
< PRECONDITIONS : ARG != 0 AND ARG != 1 >\\
FUNCIONES DE IMPLEMENTACION DE LA DIVISION ENTRE DOS REGISTROS DE DIGITOS BEGIN POSTCONDICION RET[N-1] == (DIG_1() | DIG_0()) >\\ POSTCONDICION RET[N-1] == DIG_1() => RET[N-2,0] == REGD_N_0() >\\ HAY QUE VER SI ES POTENCIA DE B : is_any_B_pow
static constexpr base_N_t< N > NumRepr::nat_reg_digs_t< UINT_T, B, L >::aprox_units_divB_n(const base_N_t< N > &arg) noexcept
FUNCION DE RECURSION PARA LA DIVISION.
static constexpr std::array< SIG_UINT_T, 2 > NumRepr::nat_reg_digs_t< UINT_T, B, L >::aprox_coc_rem(const base_N_t< N > &rem, const base_N_t< N > &dsor) noexcept
std::array<SIG_UINT_T,2>{}[0] == COC std::array<SIG_UINT_T,2>{}[1] == REM PRECONDICION DSOR != 0 Y DSOR != 1 FUNCION DE RECURSION PARA LA DIVISION SOBRECARGA DE LA ANTERIOR PARA LA RECURSION QUE NO SEA EL PRIMER CASO
static constexpr std::array< SIG_UINT_T, 2 > NumRepr::nat_reg_digs_t< UINT_T, B, L >::aprox_coc_rem(const base_N_t< N > &rem, const base_N_t< N > &dsor, SIG_UINT_T coc_calculado, SIG_UINT_T rem_calculado) noexcept
std::array<SIG_UINT_T,2>{}[0] == COC std::array<SIG_UINT_T,2>{}[1] == REM PRECONDICION DSOR != 0 Y DSOR != 1
static constexpr std::array< base_N_t< N >, 2 > NumRepr::nat_reg_digs_t< UINT_T, B, L >::fediv(const base_N_t< N > &larg, const base_N_t< N > &rarg) noexcept
END FUNCIONES DE IMPLEMENTACION DE LA DIVISION ENTRE DOS REGISTROS DE DIGITOS TODO TO DO 36 : 20 : 25 : 11 : 2022 TODO TO DO repasar que el tipo de vuelta cambie y sea : std::array<base_N_t<N>,2> -> res_base_N_op_t<N,binop_e::fediv> '@' = FULL_EUCLID_DIV(BASE_T,DIG_T) -> (REM,COC,GOOD)