NumRepr::dig_t
using NumRepr::dig_t< UINT_T, B >::SIG_UINT_T = sig_UInt_for_UInt_t<UINT_T>
using NumRepr::dig_t< UINT_T, B >::SIG_SINT_T = sig_SInt_for_UInt_t<UINT_T>
using NumRepr::dig_t< UINT_T, B >::uintspair = std::array<UINT_T,2>
using NumRepr::dig_t< UINT_T, B >::digspair = std::array<dig_t,2>
using NumRepr::dig_t< UINT_T, B >::uintspairlist = std::array<uintspair,B>
using NumRepr::dig_t< UINT_T, B >::uintspairtbl = std::array<uintspairlist,B>
using NumRepr::dig_t< UINT_T, B >::resbinop_t = auxiliary_types::resbinop_t<dig_t,op>
BEGIN : CONSTRUCCION DE LAS TABLAS DE MULTIPLICAR ESTATICAS PARA TODA LA CLASE
UINT_T NumRepr::dig_t< UINT_T, B >::m_d
Referenced by NumRepr::dig_t< UINT_T, B >::operator%=, NumRepr::dig_t< UINT_T, B >::operator*=, NumRepr::dig_t< UINT_T, B >::operator+=, NumRepr::dig_t< UINT_T, B >::operator-=, NumRepr::dig_t< UINT_T, B >::operator/=.
static consteval uintspair NumRepr::dig_t< UINT_T, B >::mult() noexcept
static consteval bool NumRepr::dig_t< UINT_T, B >::is_prime() noexcept
References NumRepr::auxiliary_functions::is_prime.
static consteval dig_t NumRepr::dig_t< UINT_T, B >::dig_max() noexcept
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_max.
static consteval dig_t NumRepr::dig_t< UINT_T, B >::dig_submax() noexcept
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_Bm2, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_submax.
static consteval dig_t NumRepr::dig_t< UINT_T, B >::dig_Bm1() noexcept
Referenced by NumRepr::reg_digs_t< UINT_T, B, L >::dig_Bm1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_add, NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_sub, NumRepr::nat_reg_digs_t< UINT_T, B, L >::predecrement, NumRepr::nat_reg_digs_t< UINT_T, B, L >::preincrement, NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_Bm1.
static consteval dig_t NumRepr::dig_t< UINT_T, B >::dig_Bm2() noexcept
Referenced by NumRepr::reg_digs_t< UINT_T, B, L >::dig_Bm2.
static consteval dig_t NumRepr::dig_t< UINT_T, B >::dig_0() noexcept
Referenced by NumRepr::nat_reg_digs_t< UINT_T, B, L >::copy_arg_N, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_0, NumRepr::reg_digs_t< UINT_T, B, L >::dig_0, NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_add, NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_sub, NumRepr::nat_reg_digs_t< UINT_T, B, L >::move_arg_N, NumRepr::nat_reg_digs_t< UINT_T, B, L >::nat_reg_digs_t, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator=, NumRepr::nat_reg_digs_t< UINT_T, B, L >::predecrement, NumRepr::nat_reg_digs_t< UINT_T, B, L >::preincrement, NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_0, NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_Bm1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_dig, NumRepr::nat_reg_digs_t< UINT_T, B, L >::set_interval_0.
static consteval dig_t NumRepr::dig_t< UINT_T, B >::dig_1() noexcept
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::dig_1, NumRepr::reg_digs_t< UINT_T, B, L >::dig_1, NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_add, NumRepr::nat_reg_digs_t< UINT_T, B, L >::m_sub, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator+=, NumRepr::nat_reg_digs_t< UINT_T, B, L >::operator-=, NumRepr::nat_reg_digs_t< UINT_T, B, L >::predecrement, NumRepr::nat_reg_digs_t< UINT_T, B, L >::preincrement.
static consteval UINT_T NumRepr::dig_t< UINT_T, B >::ui_max() noexcept
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::ui_max.
static consteval UINT_T NumRepr::dig_t< UINT_T, B >::ui_submax() noexcept
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::ui_submax.
static consteval UINT_T NumRepr::dig_t< UINT_T, B >::ui_Bm1() noexcept
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::ui_Bm1.
static consteval UINT_T NumRepr::dig_t< UINT_T, B >::ui_Bm2() noexcept
static consteval UINT_T NumRepr::dig_t< UINT_T, B >::ui_0() noexcept
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::ui_0, NumRepr::reg_digs_t< UINT_T, B, L >::ui_0.
static consteval UINT_T NumRepr::dig_t< UINT_T, B >::ui_1() noexcept
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::ui_1, NumRepr::reg_digs_t< UINT_T, B, L >::ui_1.
static consteval SIG_UINT_T NumRepr::dig_t< UINT_T, B >::sui_B() noexcept
Referenced by NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::sui_B, NumRepr::reg_digs_t< UINT_T, B, L >::sui_B, NumRepr::reg_digs_t< UINT_T, B, L >::sui_Bm1, NumRepr::nat_rat_fixed_reg_t< UINT_T, B, LE, LF >::sui_Bp1, NumRepr::reg_digs_t< UINT_T, B, L >::sui_Bp1.
static consteval SIG_UINT_T NumRepr::dig_t< UINT_T, B >::sui_max() noexcept
static consteval SIG_UINT_T NumRepr::dig_t< UINT_T, B >::sui_submax() noexcept
static consteval SIG_UINT_T NumRepr::dig_t< UINT_T, B >::sui_0() noexcept
Referenced by NumRepr::reg_digs_t< UINT_T, B, L >::sui_0.
static consteval SIG_UINT_T NumRepr::dig_t< UINT_T, B >::sui_1() noexcept
Referenced by NumRepr::reg_digs_t< UINT_T, B, L >::sui_1.
static consteval SIG_SINT_T NumRepr::dig_t< UINT_T, B >::ssi_B() noexcept
Referenced by NumRepr::reg_digs_t< UINT_T, B, L >::ssi_B, NumRepr::reg_digs_t< UINT_T, B, L >::ssi_Bm1, NumRepr::reg_digs_t< UINT_T, B, L >::ssi_Bp1.
static consteval SIG_SINT_T NumRepr::dig_t< UINT_T, B >::ssi_max() noexcept
static consteval SIG_UINT_T NumRepr::dig_t< UINT_T, B >::ssi_submax() noexcept
static consteval SIG_UINT_T NumRepr::dig_t< UINT_T, B >::ssi_0() noexcept
Referenced by NumRepr::reg_digs_t< UINT_T, B, L >::ssi_0.
static consteval SIG_UINT_T NumRepr::dig_t< UINT_T, B >::ssi_1() noexcept
Referenced by NumRepr::reg_digs_t< UINT_T, B, L >::ssi_1.
static constexpr UINT_T NumRepr::dig_t< UINT_T, B >::normaliza(Int_t arg) noexcept
static constexpr dig_t NumRepr::dig_t< UINT_T, B >::sum_carry(dig_t arg_1, dig_t arg_2) noexcept
static constexpr bool NumRepr::dig_t< UINT_T, B >::is_type_template_string_id(std::string in) noexcept
el parser/lexer del dig_t
Funciones de ayuda para
static constexpr std::string NumRepr::dig_t< UINT_T, B >::to_type_template_string_id() noexcept
static constexpr size_t NumRepr::dig_t< UINT_T, B >::size_of_type_template_string_id() noexcept
static constexpr bool NumRepr::dig_t< UINT_T, B >::get_digit_token(std::istream &is, UINT_T &uint_value)
FUNCION QUE CONSIGUE EL TOKEN DIGITO.
References NumRepr::lex::digit_value, NumRepr::lex::is_digit, NumRepr::lex::is_separator.
static bool NumRepr::dig_t< UINT_T, B >::get_radix_token(std::istream &is)
FUNCION QUE CONSIGUE EL TOKEN BASE.
References NumRepr::lex::digit_value, NumRepr::lex::is_digit, NumRepr::lex::is_separator.
static bool NumRepr::dig_t< UINT_T, B >::read(std::istream &is, dig_t &value) noexcept
References NumRepr::get_digit_token, NumRepr::get_radix_token, NumRepr::dig_t< UINT_T, B >::get_type_template_string_id_token.
constexpr NumRepr::dig_t< UINT_T, B >::operator UINT_T() const noexcept
PARA B=3 2*2 1 COMIENZAN POR 2 B-2 PARA B=4 2*2 2*3 3*4 3 COMIENZAN POR 2 B-2, 3 B-3 PARA B=5 2*2 2*3 2*4 3*3 3*4 4*4 6 COMIENZAN POR 2 B-2, 3 B-3, 4 B-4 PARA B=6 2*2 2*3 2*4 2*5 3*3 3*4 3*5 4*4 4*5 5*5 10 COMIENZAN POR 2 B-2, 3 B-3, 4 B-4, 5 B-5 PARA B=r 2*2 2*(2+1) ... 2*(r-1) r-1 r COMIENZAN POR 2 B-2, 3 B-3, 4 B-4, 5 B-1, ... , r-1 B-r+1 3*3 ... 3*(r-1) r-2 ... (r-1)*(r-1) r-(r-1) (r-2)r-(r-1)*r/2 + 1 = [2(r-2)-((r-2)+1)]r/2 + 1 = ((r-3)r + 2)/2 = (r^2 - 3r + 2) / 2 a r^2 + b r + c 1 = a 9 + b 3 + c 3 = a 16 + b 4 + c 6 = a 25 + b 5 + c 1 = a 9 + b 3 + c 2 = a 7 + b 1 5 = a 16 + b 2 1 = a 9 + b 3 + c 2 = a 7 + b 1 = a 2 c = 2/2 b = -3/2 a = 1/2 SIZE = (B^2 - 3B + 2)/2 2+3+4+...+B-1 = 1+2+3+4+...+B-1 - 1 = (B-1)B/2 - 2(B-1)/2 = (B^2 - B - 2B +2)/2 = =(B^2-3B+2)/2 FALTARIA HACER SOLO PARA BASES MAYORES QUE 2 CODE NEW USING TYPES : using pair_map = std::pair<uintspair,uintspair>; CODE MULTTABLE: static consteval std::array<pair_map,(B^2 - 3B + 2)/2> multtable{make_multtables()}; CODE FOR MAKE_MULTTABLES(): static consteval std::array<pair_map,(B^2 - 3B + 2)/2> make_multtables() noexcept { std::array<pair_map,(B^2 - 3B + 2)/2> ret; /// ESTO QUE SIGUE HABRIA QUE HACERLO POR UNROOLING LOOP EN COMPILE TIME /// YA QUE IDX E IDY NO SON CONSTANTES EN TIEMPO DE COMPILACION /// LO MEJOR ES HACERLO EN UNA CLASE TEMPLATE POR RECURSION for(size_t idx{2} ; idx < B ; ++idx) { for(size_t idy{idx} ; idy < B ; ++idy) { make_pair(make_array(idx,idy),mult<idx,idy>()); } } }
constexpr const UINT_T & NumRepr::dig_t< UINT_T, B >::get() const noexcept
constexpr NumRepr::dig_t< UINT_T, B >::operator SIG_UINT_T() const noexcept
constexpr NumRepr::dig_t< UINT_T, B >::operator SIG_SINT_T() const noexcept
constexpr UINT_T NumRepr::dig_t< UINT_T, B >::operator()() const noexcept
constexpr void NumRepr::dig_t< UINT_T, B >::set_0() noexcept
dig_t<uchint,10> digito{4}; digito() devuelve un 4 de tipo uchint
constexpr void NumRepr::dig_t< UINT_T, B >::set_1() noexcept
constexpr void NumRepr::dig_t< UINT_T, B >::set_Bm1() noexcept
constexpr void NumRepr::dig_t< UINT_T, B >::set_Bm2() noexcept
consteval NumRepr::dig_t< UINT_T, B >::dig_t() noexcept
< CONSTRUCTORES CONSTRUCTOR POR DEFECTO NORMALIZA ES UNA FUNCION QUE BASICAMENTE SI ENTRA 1524 DEVUELVE 1524B TENIENDO EN CUENTA TIPOS Y SIGNOS
constexpr NumRepr::dig_t< UINT_T, B >::dig_t(Int_t arg) noexcept
CONSTRUCTOR A PARTIR DE UN ENTERO ARG ARG EQUIV ARG+Z*B DONDE Z ES UN ENTERO EN m_d SOLO QUEREMOS QUE HAYA UN NUMERO ENTRE 0 Y B-1 INCLUSIVES
constexpr NumRepr::dig_t< UINT_T, B >::dig_t(const dig_t &) noexcept=default
CONSTRUCTOR COPIA POR REFERENCIA.
constexpr NumRepr::dig_t< UINT_T, B >::dig_t(dig_t &&) noexcept=default
CONSTRUCTOR POR MOVIMIENTO.
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::operator=(const Int_t &a) noexcept
SOBRECARGA DEL OPERATOR=() MEDIANTE REFERENCIA CTE DESDE UN INT_T.
PODEMOS PASAR ARGUMENTOS POR COPIA, REFERENCIA (PUNTEROS) Y MOVIMIENTO COPIA : COPIA EL ARGUMENTO LITERALMENTE PARA PASARLO: EL ORIGINAL INTACTO REFERENCIA: COPIA LA DIRECCION DEL ARGUMENTO (SI ES CONST EL COMPILADOR NO TE DEJA COMPILAR SI LO CAMBIAS) MOVIMIENTO: SI EL ARGUMETO NO SE VA A UTILIZAR MAS SE LE PASA LA PROPIEDAD A LA FUNCION
constexpr dig_t & NumRepr::dig_t< UINT_T, B >::operator=(const dig_t &) noexcept=default
SOBRECARGA DEL OPERATOR=() MEDIANTE REFERENCIA CTE DESDE UN DIG_T.
constexpr dig_t & NumRepr::dig_t< UINT_T, B >::operator=(dig_t &&) noexcept=default
SOBRECARGA DEL OPERATOR=() MEDIANTE MOVIMIENTO DESDE UN DIG_T.
constexpr bool NumRepr::dig_t< UINT_T, B >::is_unit() const noexcept
a y b son digitos; a = std::move(b); a es identico a b; en b puede no queda nada;
References NumRepr::ui_1.
constexpr bool NumRepr::dig_t< UINT_T, B >::is_0_divisor() const noexcept
References NumRepr::ui_1.
constexpr dig_t NumRepr::dig_t< UINT_T, B >::mult_inv() const noexcept
References NumRepr::dig_max.
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator&(const dig_t &arg) const noexcept
DEVOLVER EL MENOR: ANDBITWISE NO TIENE POSIBILIDAD DE ERROR
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::operator&=(dig_t arg) noexcept
DEVOLVER EL MENOR HABIENDOLO ASIGNADO ANDBITWISE AND ASSIGN NO TIENE POSIBILIDAD DE ERROR
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator|(const dig_t &arg) const noexcept
DEVOLVER EL MAYOR ORBITWISE NO TIENE POSIBILIDAD DE ERROR
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::operator|=(dig_t arg) noexcept
DEVOLVER EL MAYOR HABIENDOLO ASIGNADO ORBITWISE AND ASSIGN NO TIENE POSIBILIDAD DE ERROR
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::operator^=(UIntType exp) noexcept
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator^(UIntType exp) const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::operator==(dig_t a) const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::operator!=(dig_t a) const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::operator>=(dig_t a) const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::operator>(dig_t a) const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::operator<=(dig_t a) const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::operator<(dig_t a) const noexcept
constexpr std::strong_ordering NumRepr::dig_t< UINT_T, B >::operator<=>(dig_t rhs) const noexcept
SI COMPARAMOS O HACEMOS UNA OPERACION CON UN INT_T SIEMPRE SERA DIG_T @ INT_T -> DIG_T Y NUNCA INT_T @ DIG_T -> ANY_TYPE METODO PROPIO DE C++20
constexpr bool NumRepr::dig_t< UINT_T, B >::operator==(Int_t rhs) noexcept
constexpr std::weak_ordering NumRepr::dig_t< UINT_T, B >::operator<=>(Int_t rhs) const noexcept
METODO PROPIO DE C++20 ESTABLECEMOS UN ORDEN PARCIAL SOBRE LOS ENTEROS SI a b EN Z ESTANDO EN ESTE AMBITO DE BASE B SI a mod B = b mod B
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::operator+=(dig_t arg) noexcept
References NumRepr::dig_t< UINT_T, B >::m_d.
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::operator+=(Int_t arg) noexcept
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::operator-=(dig_t arg) noexcept
References NumRepr::dig_t< UINT_T, B >::m_d.
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::operator-=(Int_t arg) noexcept
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::operator*=(dig_t arg) noexcept
References NumRepr::dig_t< UINT_T, B >::m_d.
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::operator*=(Int_t arg) noexcept
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::operator/=(dig_t arg) noexcept
References NumRepr::dig_t< UINT_T, B >::m_d.
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::operator/=(Int_t arg) noexcept
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::operator%=(dig_t arg) noexcept
References NumRepr::dig_t< UINT_T, B >::m_d.
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::operator%=(Int_t arg) noexcept
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::operator++() noexcept
Tengo serias dudas que la division y el resto euclideo tengan cabida entre los operadores aritmeticos de un tipo dig_t DUDA SATISFECHA: TIENEN CABIDA PORQUE EL INVERSO MULTIPLICATIVO ETC. SOLO NOS SIRVE SI ESTUVIERAMOS CONSTRUYENDO NUMEROS DE UN ANILLO FINITO
References NumRepr::ui_1.
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator++(int) noexcept
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::operator--() noexcept
References NumRepr::ui_1.
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator--(int) noexcept
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator+(dig_t arg) const noexcept
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator-(dig_t arg) const noexcept
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator*(dig_t arg) const noexcept
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator/(dig_t arg) const noexcept
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator%(dig_t arg) const noexcept
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator+(Int_type arg) const noexcept
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator-(Int_type arg) const noexcept
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator*(Int_type arg) const noexcept
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator/(Int_type arg) const noexcept
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator%(Int_type arg) const noexcept
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator!() const noexcept
EN BASE B, B-1-m_d ES EL COMPL_Bm1(m_d)
constexpr dig_t NumRepr::dig_t< UINT_T, B >::operator-() const noexcept
EN BASE B, B-m_d ES EL COMPL_B(m_d)
constexpr dig_t NumRepr::dig_t< UINT_T, B >::C_Bm1() const noexcept
"C_Bm1" es identico a "operator!()"
Referenced by NumRepr::display_operator_C_Bm1, NumRepr::display_prop_C_B_minus_1_eq_C_Bm1, NumRepr::display_prop_C_Bm1_eq_inv_C_Bm1, NumRepr::m_sum_digs_carryin0, NumRepr::m_sum_digs_carryin1.
constexpr dig_t NumRepr::dig_t< UINT_T, B >::C_B() const noexcept
"C_B" es identico a "operator-()"
Referenced by NumRepr::display_operator_C_B, NumRepr::display_prop_C_B_eq_inv_C_B, NumRepr::display_prop_C_B_minus_1_eq_C_Bm1.
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::mC_Bm1() noexcept
constexpr const dig_t & NumRepr::dig_t< UINT_T, B >::mC_B() noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::is_0() const noexcept
dig_t<uchint,7> a,b,c; a = 5; b = 2; c = 0; !a == 1 is TRUE a.C_Bm1() == 1 is TRUE !b == 4 is TRUE b.C_Bm1() == 4 is TRUE !c == 6 is TRUE c.C_Bm1() == 6 is TRUE -a == 2 is TRUE a.C_B() == 2 is TRUE -b == 5 is TRUE b.C_B() == 5 is TRUE -c == 0 is TRUE c.C_B() == 0 is TRUE a.mC_Bm1() == 1 is TRUE a == 1 is TRUE b.mC_Bm1() == 4 is TRUE b == 4 is TRUE c.mC_Bm1() == 6 is TRUE c == 6 is TRUE a.mC_B() == 2 is TRUE a == 2 is TRUE b.mC_B() == 5 is TRUE b == 5 is TRUE c.mC_B() == 0 is TRUE c == 0 is TRUE
constexpr bool NumRepr::dig_t< UINT_T, B >::is_1() const noexcept
References NumRepr::ui_1.
constexpr bool NumRepr::dig_t< UINT_T, B >::is_0or1() const noexcept
References NumRepr::ui_1.
constexpr bool NumRepr::dig_t< UINT_T, B >::is_not_1() const noexcept
References NumRepr::ui_1.
constexpr bool NumRepr::dig_t< UINT_T, B >::is_not_0() const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::is_not_0or1() const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::is_Bm1() const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::is_not_Bm1() const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::is_Bm1orBm2() const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::is_not_Bm1orBm2() const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::is_Bm2() const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::is_not_Bm2() const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::is_not_maxormin() const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::is_maxormin() const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::is_far_maxormin() const noexcept
constexpr bool NumRepr::dig_t< UINT_T, B >::is_near_maxormin() const noexcept
constexpr std::string NumRepr::dig_t< UINT_T, B >::to_string() const noexcept
bool NumRepr::dig_t< UINT_T, B >::get_type_template_string_id_token(std::istream &is) noexcept
FUNCION GENERICA QUE CONSIGUE EL TOKEN TYPE PARA LA OBTENCION DEL OBJETO CORRESPONDIENTE POR TECLADO
Referenced by NumRepr::dig_t< UINT_T, B >::read.
constexpr std::string NumRepr::dig_t< UINT_T, B >::num_to_string() const noexcept
TIENE QUE DEVOLVER STD::STRING.
static constexpr std::string NumRepr::dig_t< UINT_T, B >::radix_str() noexcept