int_num_t
typedef dig_t<B> int_num_t< UINT_T, B >::dig
typedef num_basic_t<B> int_num_t< UINT_T, B >::num_basic
typedef basic_string< dig_t<B> > int_num_t< UINT_T, B >::nbstr
typedef nbstr::iterator int_num_t< UINT_T, B >::striterator
typedef nbstr::reverse_iterator int_num_t< UINT_T, B >::rstriterator
typedef nbstr::const_iterator int_num_t< UINT_T, B >::cstriterator
typedef nbstr::const_reverse_iterator int_num_t< UINT_T, B >::crstriterator
typedef num_basic::iterator int_num_t< UINT_T, B >::b_iterator
typedef num_basic::reverse_iterator int_num_t< UINT_T, B >::b_riterator
typedef num_basic::const_iterator int_num_t< UINT_T, B >::b_citerator
typedef num_basic::const_reverse_iterator int_num_t< UINT_T, B >::b_criterator
typedef num_int::iterator int_num_t< UINT_T, B >::iterator
typedef num_int::reverse_iterator int_num_t< UINT_T, B >::riterator
typedef num_int::const_iterator int_num_t< UINT_T, B >::citerator
typedef num_int::const_reverse_iterator int_num_t< UINT_T, B >::criterator
typedef n2digs_t<B> int_num_t< UINT_T, B >::n2digs
typedef pardigs_t<B> int_num_t< UINT_T, B >::pardigs
typedef spardigs_t<B> int_num_t< UINT_T, B >::spardigs
sign_e int_num_t< UINT_T, B >::signo
Referenced by int_num_t< UINT_T, B >::abs, int_num_t< UINT_T, B >::absp, int_num_t< UINT_T, B >::digs_no_significativos, int_num_t< UINT_T, B >::div2, int_num_t< UINT_T, B >::div2p, int_num_t< UINT_T, B >::erase, int_num_t< UINT_T, B >::EuclidDiv, int_num_t< UINT_T, B >::EuclidDivP, int_num_t< UINT_T, B >::mC_B, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::operator!=, int_num_t< UINT_T, B >::operator*, int_num_t< UINT_T, B >::operator*=, int_num_t< UINT_T, B >::operator++, int_num_t< UINT_T, B >::operator--, int_num_t< UINT_T, B >::operator/, int_num_t< UINT_T, B >::operator/=, int_num_t< UINT_T, B >::operator<, int_num_t< UINT_T, B >::operator<=, int_num_t< UINT_T, B >::operator=, int_num_t< UINT_T, B >::operator==, int_num_t< UINT_T, B >::operator>, int_num_t< UINT_T, B >::operator>=, int_num_t< UINT_T, B >::rem2, int_num_t< UINT_T, B >::rem2p, int_num_t< UINT_T, B >::remB, int_num_t< UINT_T, B >::remBm1, int_num_t< UINT_T, B >::remBp.
spardigs int_num_t< UINT_T, B >::aux
Referenced by int_num_t< UINT_T, B >::mC_B, int_num_t< UINT_T, B >::mC_B_incondicionado, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::operator+, int_num_t< UINT_T, B >::operator++, int_num_t< UINT_T, B >::operator+=, int_num_t< UINT_T, B >::operator-, int_num_t< UINT_T, B >::operator--, int_num_t< UINT_T, B >::operator-=, int_num_t< UINT_T, B >::operator=.
size_t int_num_t< UINT_T, B >::size() const
Referenced by int_num_t< UINT_T, B >::ceros_a_la_drcha, int_num_t< UINT_T, B >::ceros_a_la_izqda, int_num_t< UINT_T, B >::erase, int_num_t< UINT_T, B >::unos_a_la_drcha.
void int_num_t< UINT_T, B >::resize(size_t arg)
void int_num_t< UINT_T, B >::push_front(dig_t< B > parg)
void int_num_t< UINT_T, B >::push_back(dig_t< B > arg)
Referenced by int_num_t< UINT_T, B >::mC_B.
const num_int & int_num_t< UINT_T, B >::operator&=(const num_int &arg)
int_num_t< UINT_T, B >::num_int()
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
Referenced by int_num_t< UINT_T, B >::abs, int_num_t< UINT_T, B >::absp, int_num_t< UINT_T, B >::Bm1_a_la_drcha, int_num_t< UINT_T, B >::Bm1_a_la_izqda, int_num_t< UINT_T, B >::ceros_a_la_izqda, int_num_t< UINT_T, B >::digs_no_significativos, int_num_t< UINT_T, B >::div2, int_num_t< UINT_T, B >::div2p, int_num_t< UINT_T, B >::div_gen_step, int_num_t< UINT_T, B >::div_uno, int_num_t< UINT_T, B >::divB, int_num_t< UINT_T, B >::divBp, int_num_t< UINT_T, B >::divp_gen_step, int_num_t< UINT_T, B >::erase, int_num_t< UINT_T, B >::EuclidDiv, int_num_t< UINT_T, B >::EuclidDivP, int_num_t< UINT_T, B >::filled_of_all_digits_are_0, int_num_t< UINT_T, B >::filled_of_all_digits_are_Bm1, int_num_t< UINT_T, B >::mC_B, int_num_t< UINT_T, B >::mC_B_incondicionado, int_num_t< UINT_T, B >::mC_Bm1, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::operator!, int_num_t< UINT_T, B >::operator!=, int_num_t< UINT_T, B >::operator%, int_num_t< UINT_T, B >::operator%=, int_num_t< UINT_T, B >::operator*, int_num_t< UINT_T, B >::operator*=, int_num_t< UINT_T, B >::operator+, int_num_t< UINT_T, B >::operator++, int_num_t< UINT_T, B >::operator+=, int_num_t< UINT_T, B >::operator-, int_num_t< UINT_T, B >::operator--, int_num_t< UINT_T, B >::operator-=, int_num_t< UINT_T, B >::operator/, int_num_t< UINT_T, B >::operator/=, int_num_t< UINT_T, B >::operator<, int_num_t< UINT_T, B >::operator<=, int_num_t< UINT_T, B >::operator=, int_num_t< UINT_T, B >::operator==, int_num_t< UINT_T, B >::operator>, int_num_t< UINT_T, B >::operator>=, int_num_t< UINT_T, B >::reduce, int_num_t< UINT_T, B >::reduce_fracc, int_num_t< UINT_T, B >::rem2, int_num_t< UINT_T, B >::rem2p, int_num_t< UINT_T, B >::remB, int_num_t< UINT_T, B >::remBm1, int_num_t< UINT_T, B >::remBp, int_num_t< UINT_T, B >::unos_a_la_izqda.
int_num_t< UINT_T, B >::num_int(const num_int &a)
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
int_num_t< UINT_T, B >::num_int(const string &a)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
int_num_t< UINT_T, B >::num_int(dig a0)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
int_num_t< UINT_T, B >::num_int(dig a1, dig a0)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
int_num_t< UINT_T, B >::num_int(dig a2, dig a1, dig a0)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
int_num_t< UINT_T, B >::num_int(const std::vector< dig > &arg)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
int_num_t< UINT_T, B >::num_int(const std::list< dig > &arg)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
int_num_t< UINT_T, B >::num_int(sign_e s, dig a0)
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
int_num_t< UINT_T, B >::num_int(sign_e s, dig a1, dig a0)
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
int_num_t< UINT_T, B >::num_int(sign_e s, dig a2, dig a1, dig a0)
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
int_num_t< UINT_T, B >::num_int(sign_e s, const std::vector< dig > &arg, forma_t argforma=noraw)
References noraw, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
int_num_t< UINT_T, B >::num_int(sign_e s, const std::list< dig > &arg)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
int_num_t< UINT_T, B >::num_int(spardigs a)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
int_num_t< UINT_T, B >::num_int(pardigs a)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
int_num_t< UINT_T, B >::num_int(sign_e s, pardigs a)
References int_num_t< UINT_T, B >::num_int.
int_num_t< UINT_T, B >::num_int(char ch)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
int_num_t< UINT_T, B >::num_int(uchint a)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
int_num_t< UINT_T, B >::num_int(Int_T a)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int & int_num_t< UINT_T, B >::operator=(const num_int &a)
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int & int_num_t< UINT_T, B >::operator=(const num_uint< B > &a)
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int & int_num_t< UINT_T, B >::operator=(const pardigs_t< B > &a)
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int & int_num_t< UINT_T, B >::operator=(const spardigs_t< B > &a)
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int & int_num_t< UINT_T, B >::operator=(const dig_t< B > &a)
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int & int_num_t< UINT_T, B >::operator=(Int_T a)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int & int_num_t< UINT_T, B >::operator=(const std::vector< dig > &arg)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int & int_num_t< UINT_T, B >::operator=(const std::list< dig > &arg)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
usint int_num_t< UINT_T, B >::ceros_a_la_izqda() const
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::size.
usint int_num_t< UINT_T, B >::unos_a_la_izqda() const
References int_num_t< UINT_T, B >::num_int.
size_t int_num_t< UINT_T, B >::ceros_a_la_drcha() const
References int_num_t< UINT_T, B >::size.
Referenced by int_num_t< UINT_T, B >::digs_fracc_no_significativos.
size_t int_num_t< UINT_T, B >::unos_a_la_drcha() const
References int_num_t< UINT_T, B >::size.
bool int_num_t< UINT_T, B >::filled_of_all_digits_are_Bm1() const
References int_num_t< UINT_T, B >::num_int.
bool int_num_t< UINT_T, B >::filled_of_all_digits_are_0() const
References int_num_t< UINT_T, B >::num_int.
usint int_num_t< UINT_T, B >::digs_no_significativos() const
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
Referenced by int_num_t< UINT_T, B >::operator!=.
usint int_num_t< UINT_T, B >::digs_fracc_no_significativos() const
References int_num_t< UINT_T, B >::ceros_a_la_drcha.
usint int_num_t< UINT_T, B >::Bm1_a_la_izqda() const
References int_num_t< UINT_T, B >::num_int.
usint int_num_t< UINT_T, B >::Bm1_a_la_drcha() const
References int_num_t< UINT_T, B >::num_int.
bool int_num_t< UINT_T, B >::operator==(const num_int &arg) const
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
bool int_num_t< UINT_T, B >::operator!=(const num_int &arg) const
References int_num_t< UINT_T, B >::digs_no_significativos, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
bool int_num_t< UINT_T, B >::operator>=(const num_int &arg) const
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
bool int_num_t< UINT_T, B >::operator<=(const num_int &arg) const
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
bool int_num_t< UINT_T, B >::operator>(const num_int &arg) const
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
bool int_num_t< UINT_T, B >::operator<(const num_int &arg) const
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
num_int int_num_t< UINT_T, B >::operator+(const num_int &arg) const
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int.
num_int int_num_t< UINT_T, B >::operator-(const num_int &arg) const
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int.
num_int int_num_t< UINT_T, B >::operator*(const num_int &arg) const
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
num_int int_num_t< UINT_T, B >::operator/(const num_int &arg) const
References int_num_t< UINT_T, B >::abs, int_num_t< UINT_T, B >::div_uno, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
num_int int_num_t< UINT_T, B >::operator%(const num_int &arg) const
References int_num_t< UINT_T, B >::abs, int_num_t< UINT_T, B >::div_uno, int_num_t< UINT_T, B >::num_int.
num_int int_num_t< UINT_T, B >::operator*(pardigs a) const
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
num_int int_num_t< UINT_T, B >::operator+(dig arg) const
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int.
num_int int_num_t< UINT_T, B >::operator-(dig arg) const
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int.
num_int int_num_t< UINT_T, B >::operator*(dig a) const
References int_num_t< UINT_T, B >::num_int.
const num_int & int_num_t< UINT_T, B >::operator+=(const num_int &arg)
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::reduce.
const num_int & int_num_t< UINT_T, B >::operator-=(const num_int &arg)
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::reduce.
const num_int & int_num_t< UINT_T, B >::operator*=(const num_int &arg)
References int_num_t< UINT_T, B >::absp, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::reduce, int_num_t< UINT_T, B >::signo.
const num_int & int_num_t< UINT_T, B >::operator/=(const num_int &arg)
References int_num_t< UINT_T, B >::absp, int_num_t< UINT_T, B >::div_uno, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int & int_num_t< UINT_T, B >::operator%=(const num_int &arg)
References int_num_t< UINT_T, B >::div_uno, int_num_t< UINT_T, B >::num_int.
const num_int & int_num_t< UINT_T, B >::operator*=(pardigs a)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int & int_num_t< UINT_T, B >::operator+=(dig arg)
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::reduce.
const num_int & int_num_t< UINT_T, B >::operator-=(dig arg)
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::reduce.
const num_int & int_num_t< UINT_T, B >::operator*=(dig arg)
References int_num_t< UINT_T, B >::absp, int_num_t< UINT_T, B >::insert, int_num_t< UINT_T, B >::mC_B, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::reduce, int_num_t< UINT_T, B >::signo.
num_int int_num_t< UINT_T, B >::operator-() const
References int_num_t< UINT_T, B >::num_int.
num_int int_num_t< UINT_T, B >::operator!() const
References int_num_t< UINT_T, B >::num_int.
const num_int & int_num_t< UINT_T, B >::mC_B()
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::push_back, int_num_t< UINT_T, B >::signo.
Referenced by int_num_t< UINT_T, B >::operator*=.
const num_int & int_num_t< UINT_T, B >::mC_Bm1()
References int_num_t< UINT_T, B >::num_int.
Referenced by int_num_t< UINT_T, B >::mC_B_incondicionado.
num_int int_num_t< UINT_T, B >::abs() const
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
Referenced by int_num_t< UINT_T, B >::operator%, int_num_t< UINT_T, B >::operator/.
const num_int & int_num_t< UINT_T, B >::absp()
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
Referenced by int_num_t< UINT_T, B >::operator*=, int_num_t< UINT_T, B >::operator/=.
num_int int_num_t< UINT_T, B >::divB() const
References int_num_t< UINT_T, B >::num_int.
dig int_num_t< UINT_T, B >::remB() const
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int & int_num_t< UINT_T, B >::divBp()
References int_num_t< UINT_T, B >::num_int.
dig int_num_t< UINT_T, B >::remBp()
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
num_int int_num_t< UINT_T, B >::div2() const
References int_num_t< UINT_T, B >::div_uno, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
dig int_num_t< UINT_T, B >::rem2() const
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int & int_num_t< UINT_T, B >::div2p()
References int_num_t< UINT_T, B >::div_uno, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
dig int_num_t< UINT_T, B >::rem2p()
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
dig int_num_t< UINT_T, B >::remBm1() const
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
pair< num_int, num_int > int_num_t< UINT_T, B >::EuclidDiv(const num_int &arg) const
References int_num_t< UINT_T, B >::div_uno, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
pair< num_int, const num_int & > int_num_t< UINT_T, B >::EuclidDivP(const num_int &arg)
References int_num_t< UINT_T, B >::div_uno, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int & int_num_t< UINT_T, B >::operator++()
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int int_num_t< UINT_T, B >::operator++(int)
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int & int_num_t< UINT_T, B >::operator--()
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int int_num_t< UINT_T, B >::operator--(int)
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo.
const num_int & int_num_t< UINT_T, B >::reduce()
References int_num_t< UINT_T, B >::num_int.
Referenced by int_num_t< UINT_T, B >::operator*=, int_num_t< UINT_T, B >::operator+=, int_num_t< UINT_T, B >::operator-=.
num_int int_num_t< UINT_T, B >::reduce() const
References int_num_t< UINT_T, B >::num_int.
const num_int & int_num_t< UINT_T, B >::reduce_fracc()
References int_num_t< UINT_T, B >::num_int.
num_int int_num_t< UINT_T, B >::reduce_fracc() const
References int_num_t< UINT_T, B >::num_int.
void int_num_t< UINT_T, B >::mC_B_incondicionado()
References int_num_t< UINT_T, B >::aux, int_num_t< UINT_T, B >::mC_Bm1, int_num_t< UINT_T, B >::num_int.
num_int & int_num_t< UINT_T, B >::insert(size_t pos1, const dig_t< B > chardig)
Referenced by int_num_t< UINT_T, B >::operator*=.
num_int & int_num_t< UINT_T, B >::insert(size_t pos1, size_t n, dig_t< B > c)
num_int & int_num_t< UINT_T, B >::erase(size_t pos, size_t npos)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::signo, int_num_t< UINT_T, B >::size.
iterator int_num_t< UINT_T, B >::erase(iterator first, iterator last)
References int_num_t< UINT_T, B >::num_int, int_num_t< UINT_T, B >::size.
void int_num_t< UINT_T, B >::div_gen_step(const num_int &dvsor, num_int &rem, num_int &coc, usint &ndig) const
References int_num_t< UINT_T, B >::num_int.
Referenced by int_num_t< UINT_T, B >::div_uno.
void int_num_t< UINT_T, B >::divp_gen_step(const num_int &dvsor, num_int &rem, num_int &coc, usint &ndig)
References int_num_t< UINT_T, B >::num_int.
void int_num_t< UINT_T, B >::div_uno(num_int &rem, num_int &dvndo, num_int &dvsor, const usint long_dvndo, const usint long_dvsor) const
References int_num_t< UINT_T, B >::div_gen_step, int_num_t< UINT_T, B >::num_int.
Referenced by int_num_t< UINT_T, B >::div2, int_num_t< UINT_T, B >::div2p, int_num_t< UINT_T, B >::EuclidDiv, int_num_t< UINT_T, B >::EuclidDivP, int_num_t< UINT_T, B >::operator%, int_num_t< UINT_T, B >::operator%=, int_num_t< UINT_T, B >::operator/, int_num_t< UINT_T, B >::operator/=.
istream & operator>>(istream &is, num_int< Base > &arg)
ostream & operator<<(ostream &os, num_int< Base > arg)