.TH "auxiliary_functions.hpp" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
auxiliary_functions.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'auxiliary_types\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBNumRepr\fP"
.br
.ti -1c
.RI "namespace \fBNumRepr::detail\fP"
.br
.ti -1c
.RI "namespace \fBNumRepr::auxiliary_functions\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "constexpr sign_e \fBNumRepr::Char2Sign\fP (char ch) noexcept"
.br
.ti -1c
.RI "template<type_traits::arith_integral_c IntT> constexpr sign_e \fBNumRepr::Int2Sign\fP (IntT nu) noexcept"
.br
.ti -1c
.RI "template<type_traits::arith_integral_c IntT> constexpr sign_funct_e \fBNumRepr::Int2SignFunct\fP (IntT nu) noexcept"
.br
.ti -1c
.RI "template<type_traits::arith_natural_c NatIntT> constexpr sign_funct_e \fBNumRepr::Nat2SignFunct\fP (NatIntT nu) noexcept"
.br
.ti -1c
.RI "constexpr size_t \fBNumRepr::detail::ceilsqrt\fP (size_t n, size_t low, size_t high) noexcept"
.br
.ti -1c
.RI "constexpr size_t \fBNumRepr::detail::ceilsqrt\fP (size_t n) noexcept"
.br
.ti -1c
.RI "constexpr bool \fBNumRepr::detail::find_factor\fP (size_t n, size_t low, size_t high) noexcept"
.br
.ti -1c
.RI "constexpr bool \fBNumRepr::auxiliary_functions::is_prime\fP (size_t n) noexcept"
.br
.ti -1c
.RI "constexpr bool \fBNumRepr::auxiliary_functions::is_power_of_2\fP (uint128_t num) noexcept"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
