.TH "base_num_t.hpp" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
base_num_t.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'int_reg_digs_t\&.hpp'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBNumRepr::base_num_t< UINT_T, B >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBNumRepr\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "template<typename Int_T , usint B> constexpr ullint \fBNumRepr::pot_max_base_B_en_Int_T\fP () noexcept"
.br
.ti -1c
.RI "template<typename Int_T , ullint B> constexpr ullint \fBNumRepr::num_digs_max_base_B_en_Int_T\fP () noexcept"
.br
.ti -1c
.RI "template<typename Int_T , ullint B> constexpr ullint \fBNumRepr::max_base_B_en_Int_T\fP () noexcept"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
