.TH "details::cp_delete< aT, T, std::numeric_limits< uchint >::max()>" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
details::cp_delete< aT, T, std::numeric_limits< uchint >::max()>
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memory_handler\&.hpp>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (aT **var_list_list)"
.br
.in -1c
.SS "Métodos privados estáticos"

.in +1c
.ti -1c
.RI "static void \fBcontruye_lista_de_variables\fP (aT *var_list)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename aT, template< uchint > class T>
.br
struct details::cp_delete< aT, T, std::numeric_limits< uchint >::max()>"
.PP
Definición en la línea \fB91\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename aT , template< uchint > class T> static void \fBdetails::cp_delete\fP< aT, T, std::numeric_limits< uchint >::max()>::contruye_lista_de_variables (aT * var_list)\fC [inline]\fP, \fC [static]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB93\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<typename aT , template< uchint > class T> void \fBdetails::cp_delete\fP< aT, T, std::numeric_limits< uchint >::max()>::operator() (aT ** var_list_list)\fC [inline]\fP"

.PP
Definición en la línea \fB97\fP del archivo \fBmemory_handler\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
