.TH "details::cp_new< 0u >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
details::cp_new< 0u >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memory_handler\&.hpp>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (aT **var_list_list)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename aT, template< uchint > class T, usint num_vars>
.br
struct details::cp_new< 0u >"
.PP
Definición en la línea \fB71\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename aT , template< uchint > class T, usint num_vars> void \fBdetails::cp_new\fP< 0u >::operator() (aT ** var_list_list)\fC [inline]\fP"

.PP
Definición en la línea \fB72\fP del archivo \fBmemory_handler\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
