.TH "details::cp_delete< aT, T, B >" 3 "Lunes, 28 de Noviembre de 2022" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
details::cp_delete< aT, T, B >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memory_handler\&.hpp>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (aT **var_list_list)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename aT, template< \fBuchint\fP > class T, \fBuchint\fP B>
.br
struct details::cp_delete< aT, T, B >"
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename aT , template< \fBuchint\fP > class T, \fBuchint\fP B> void \fBdetails::cp_delete\fP< aT, T, B >::operator() (aT ** var_list_list)\fC [inline]\fP"

.PP
.nf
83                                             {
84                         destruye_lista_de_variables(var_list_list[B]);
85                         cp_delete<aT,T,B-1>(var_list_list);
86         }
.fi


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
