.TH "func_refvar_t< UINT **, UINT *, UINT >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
func_refvar_t< UINT **, UINT *, UINT >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memory_handler\&.hpp>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBfunc_refvar_t\fP ()"
.br
.ti -1c
.RI "\fB~func_refvar_t\fP ()"
.br
.ti -1c
.RI "void \fBborra_var\fP (string nombre)"
.br
.ti -1c
.RI "bool \fBexiste_lugar_de_base\fP (uchint Base)"
.br
.ti -1c
.RI "bool \fBeste_nombre_ya_ha_sido_declarado\fP (string nombre)"
.br
.ti -1c
.RI "template<const uchint B> \fBUINT\fP \fBget\fP (string nombre)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (string nombre, string lhs)"
.br
.in -1c
.SS "Métodos privados"

.in +1c
.ti -1c
.RI "bool \fBinsert\fP (string nombre, uchint base, uchint var_base)"
.br
.ti -1c
.RI "\fBfunc_refvar_t\fP (const \fBfunc_refvar_t\fP &)"
.br
.ti -1c
.RI "bool \fBescribe_var\fP (string nombre, uchint base, uchint var_base)"
.br
.in -1c
.SS "Atributos privados"

.in +1c
.ti -1c
.RI "vector< vector< bool > > \fBmapmem\fP"
.br
.ti -1c
.RI "map< string, \fBpar_dir_t\fP > \fBmapvd\fP"
.br
.ti -1c
.RI "\fBUINT\fP ** \fBmatd\fP"
.br
.ti -1c
.RI "vector< uint > \fBcuentavars\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB426\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBfunc_refvar_t\fP< \fBUINT\fP **, \fBUINT\fP *, \fBUINT\fP >\fB::func_refvar_t\fP (const \fBfunc_refvar_t\fP< \fBUINT\fP **, \fBUINT\fP *, \fBUINT\fP > &)\fC [private]\fP"

.SS "\fBfunc_refvar_t\fP< \fBUINT\fP **, \fBUINT\fP *, \fBUINT\fP >\fB::func_refvar_t\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB462\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "\fBfunc_refvar_t\fP< \fBUINT\fP **, \fBUINT\fP *, \fBUINT\fP >::~\fBfunc_refvar_t\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB477\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "void \fBfunc_refvar_t\fP< \fBUINT\fP **, \fBUINT\fP *, \fBUINT\fP >::borra_var (string nombre)\fC [inline]\fP"

.PP
Definición en la línea \fB499\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "bool \fBfunc_refvar_t\fP< \fBUINT\fP **, \fBUINT\fP *, \fBUINT\fP >::escribe_var (string nombre, uchint base, uchint var_base)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB485\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "bool \fBfunc_refvar_t\fP< \fBUINT\fP **, \fBUINT\fP *, \fBUINT\fP >::este_nombre_ya_ha_sido_declarado (string nombre)\fC [inline]\fP"

.PP
Definición en la línea \fB522\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "bool \fBfunc_refvar_t\fP< \fBUINT\fP **, \fBUINT\fP *, \fBUINT\fP >::existe_lugar_de_base (uchint Base)\fC [inline]\fP"

.PP
Definición en la línea \fB513\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<const uchint B> \fBUINT\fP \fBfunc_refvar_t\fP< \fBUINT\fP **, \fBUINT\fP *, \fBUINT\fP >::get (string nombre)\fC [inline]\fP"

.PP
Definición en la línea \fB534\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "bool \fBfunc_refvar_t\fP< \fBUINT\fP **, \fBUINT\fP *, \fBUINT\fP >::insert (string nombre, uchint base, uchint var_base)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB437\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "bool \fBfunc_refvar_t\fP< \fBUINT\fP **, \fBUINT\fP *, \fBUINT\fP >::operator() (string nombre, string lhs)\fC [inline]\fP"

.PP
Definición en la línea \fB540\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "vector<uint> \fBfunc_refvar_t\fP< \fBUINT\fP **, \fBUINT\fP *, \fBUINT\fP >::cuentavars\fC [private]\fP"

.PP
Definición en la línea \fB432\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "vector< vector<bool> > \fBfunc_refvar_t\fP< \fBUINT\fP **, \fBUINT\fP *, \fBUINT\fP >::mapmem\fC [private]\fP"

.PP
Definición en la línea \fB429\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "map< string , \fBpar_dir_t\fP > \fBfunc_refvar_t\fP< \fBUINT\fP **, \fBUINT\fP *, \fBUINT\fP >::mapvd\fC [private]\fP"

.PP
Definición en la línea \fB430\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "\fBUINT\fP** \fBfunc_refvar_t\fP< \fBUINT\fP **, \fBUINT\fP *, \fBUINT\fP >::matd\fC [private]\fP"

.PP
Definición en la línea \fB431\fP del archivo \fBmemory_handler\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
