.TH "func_refvar_t< INT **, INT *, INT >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
func_refvar_t< INT **, INT *, INT >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memory_handler\&.hpp>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBfunc_refvar_t\fP ()"
.br
.ti -1c
.RI "\fB~func_refvar_t\fP ()"
.br
.ti -1c
.RI "void \fBborra_var\fP (string nombre)"
.br
.ti -1c
.RI "bool \fBexiste_lugar_de_base\fP (uchint Base)"
.br
.ti -1c
.RI "bool \fBeste_nombre_ya_ha_sido_declarado\fP (string nombre)"
.br
.ti -1c
.RI "\fBINT\fP \fBget\fP (string nombre)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (string nombre, string lhs)"
.br
.in -1c
.SS "Métodos privados"

.in +1c
.ti -1c
.RI "bool \fBinsert\fP (string nombre, uchint base, uchint var_base)"
.br
.ti -1c
.RI "\fBfunc_refvar_t\fP (const \fBfunc_refvar_t\fP &)=delete"
.br
.ti -1c
.RI "bool \fBescribe_var\fP (string nombre, uchint base, uchint var_base)"
.br
.in -1c
.SS "Atributos privados"

.in +1c
.ti -1c
.RI "vector< vector< bool > > \fBmapmem\fP"
.br
.ti -1c
.RI "map< string, \fBpar_dir_t\fP > \fBmapvd\fP"
.br
.ti -1c
.RI "\fBINT\fP ** \fBmatd\fP"
.br
.ti -1c
.RI "vector< uint > \fBcuentavars\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB305\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBfunc_refvar_t\fP< \fBINT\fP **, \fBINT\fP *, \fBINT\fP >\fB::func_refvar_t\fP (const \fBfunc_refvar_t\fP< \fBINT\fP **, \fBINT\fP *, \fBINT\fP > &)\fC [private]\fP, \fC [delete]\fP"

.SS "\fBfunc_refvar_t\fP< \fBINT\fP **, \fBINT\fP *, \fBINT\fP >\fB::func_refvar_t\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB341\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "\fBfunc_refvar_t\fP< \fBINT\fP **, \fBINT\fP *, \fBINT\fP >::~\fBfunc_refvar_t\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB356\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "void \fBfunc_refvar_t\fP< \fBINT\fP **, \fBINT\fP *, \fBINT\fP >::borra_var (string nombre)\fC [inline]\fP"

.PP
Definición en la línea \fB378\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "bool \fBfunc_refvar_t\fP< \fBINT\fP **, \fBINT\fP *, \fBINT\fP >::escribe_var (string nombre, uchint base, uchint var_base)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB364\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "bool \fBfunc_refvar_t\fP< \fBINT\fP **, \fBINT\fP *, \fBINT\fP >::este_nombre_ya_ha_sido_declarado (string nombre)\fC [inline]\fP"

.PP
Definición en la línea \fB401\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "bool \fBfunc_refvar_t\fP< \fBINT\fP **, \fBINT\fP *, \fBINT\fP >::existe_lugar_de_base (uchint Base)\fC [inline]\fP"

.PP
Definición en la línea \fB392\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "\fBINT\fP \fBfunc_refvar_t\fP< \fBINT\fP **, \fBINT\fP *, \fBINT\fP >::get (string nombre)\fC [inline]\fP"

.PP
Definición en la línea \fB412\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "bool \fBfunc_refvar_t\fP< \fBINT\fP **, \fBINT\fP *, \fBINT\fP >::insert (string nombre, uchint base, uchint var_base)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB316\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "bool \fBfunc_refvar_t\fP< \fBINT\fP **, \fBINT\fP *, \fBINT\fP >::operator() (string nombre, string lhs)\fC [inline]\fP"

.PP
Definición en la línea \fB417\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "vector<uint> \fBfunc_refvar_t\fP< \fBINT\fP **, \fBINT\fP *, \fBINT\fP >::cuentavars\fC [private]\fP"

.PP
Definición en la línea \fB311\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "vector< vector<bool> > \fBfunc_refvar_t\fP< \fBINT\fP **, \fBINT\fP *, \fBINT\fP >::mapmem\fC [private]\fP"

.PP
Definición en la línea \fB308\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "map< string , \fBpar_dir_t\fP > \fBfunc_refvar_t\fP< \fBINT\fP **, \fBINT\fP *, \fBINT\fP >::mapvd\fC [private]\fP"

.PP
Definición en la línea \fB309\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "\fBINT\fP** \fBfunc_refvar_t\fP< \fBINT\fP **, \fBINT\fP *, \fBINT\fP >::matd\fC [private]\fP"

.PP
Definición en la línea \fB310\fP del archivo \fBmemory_handler\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
