.TH "func_refvar_t< aT, T >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
func_refvar_t< aT, T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memory_handler\&.hpp>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBfunc_refvar_t\fP ()"
.br
.ti -1c
.RI "\fB~func_refvar_t\fP ()"
.br
.ti -1c
.RI "void \fBborra_var\fP (string nombre)"
.br
.ti -1c
.RI "bool \fBexiste_lugar_de_base\fP (uchint Base)"
.br
.ti -1c
.RI "bool \fBeste_nombre_ya_ha_sido_declarado\fP (string nombre)"
.br
.ti -1c
.RI "template<const uchint B> T< B > \fBget\fP (string nombre)"
.br
.ti -1c
.RI "template<const uchint B> bool \fBoperator()\fP (string nombre, string lhs)"
.br
.in -1c
.SS "Métodos privados"

.in +1c
.ti -1c
.RI "bool \fBinsert\fP (string nombre, uchint base, uchint var_base)"
.br
.ti -1c
.RI "\fBfunc_refvar_t\fP (const \fBfunc_refvar_t\fP &)"
.br
.ti -1c
.RI "bool \fBescribe_var\fP (string nombre, uchint base, uchint var_base)"
.br
.in -1c
.SS "Atributos privados"

.in +1c
.ti -1c
.RI "vector< vector< bool > > \fBmapmem\fP"
.br
.ti -1c
.RI "map< string, \fBpar_dir_t\fP > \fBmapvd\fP"
.br
.ti -1c
.RI "aT ** \fBmatd\fP"
.br
.ti -1c
.RI "vector< uint > \fBcuentavars\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename aT, template< uchint > class T>
.br
class func_refvar_t< aT, T >"
.PP
Definición en la línea \fB182\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "template<typename aT , template< uchint > class T> \fBfunc_refvar_t\fP< aT, T >\fB::func_refvar_t\fP (const \fBfunc_refvar_t\fP< aT, T > &)\fC [private]\fP"

.SS "template<typename aT , template< uchint > class T> \fBfunc_refvar_t\fP< aT, T >\fB::func_refvar_t\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB218\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<typename aT , template< uchint > class T> \fBfunc_refvar_t\fP< aT, T >::~\fBfunc_refvar_t\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB233\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename aT , template< uchint > class T> void \fBfunc_refvar_t\fP< aT, T >::borra_var (string nombre)\fC [inline]\fP"

.PP
Definición en la línea \fB255\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<typename aT , template< uchint > class T> bool \fBfunc_refvar_t\fP< aT, T >::escribe_var (string nombre, uchint base, uchint var_base)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB241\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<typename aT , template< uchint > class T> bool \fBfunc_refvar_t\fP< aT, T >::este_nombre_ya_ha_sido_declarado (string nombre)\fC [inline]\fP"

.PP
Definición en la línea \fB278\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<typename aT , template< uchint > class T> bool \fBfunc_refvar_t\fP< aT, T >::existe_lugar_de_base (uchint Base)\fC [inline]\fP"

.PP
Definición en la línea \fB269\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<typename aT , template< uchint > class T> template<const uchint B> T< B > \fBfunc_refvar_t\fP< aT, T >::get (string nombre)\fC [inline]\fP"

.PP
Definición en la línea \fB290\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<typename aT , template< uchint > class T> bool \fBfunc_refvar_t\fP< aT, T >::insert (string nombre, uchint base, uchint var_base)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB193\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<typename aT , template< uchint > class T> template<const uchint B> bool \fBfunc_refvar_t\fP< aT, T >::operator() (string nombre, string lhs)\fC [inline]\fP"

.PP
Definición en la línea \fB296\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "template<typename aT , template< uchint > class T> vector<uint> \fBfunc_refvar_t\fP< aT, T >::cuentavars\fC [private]\fP"

.PP
Definición en la línea \fB188\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<typename aT , template< uchint > class T> vector< vector<bool> > \fBfunc_refvar_t\fP< aT, T >::mapmem\fC [private]\fP"

.PP
Definición en la línea \fB185\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<typename aT , template< uchint > class T> map< string , \fBpar_dir_t\fP > \fBfunc_refvar_t\fP< aT, T >::mapvd\fC [private]\fP"

.PP
Definición en la línea \fB186\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<typename aT , template< uchint > class T> aT** \fBfunc_refvar_t\fP< aT, T >::matd\fC [private]\fP"

.PP
Definición en la línea \fB187\fP del archivo \fBmemory_handler\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
