.TH "int_num_t< UINT_T, B >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
int_num_t< UINT_T, B >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <int_num_t\&.hpp>\fP
.PP
Herencias base_num_t< UINT_T, B >\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "void \fBresize\fP (size_t arg)"
.br
.ti -1c
.RI "void \fBpush_front\fP (dig_t< B > parg)"
.br
.ti -1c
.RI "void \fBpush_back\fP (dig_t< B > arg)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator&=\fP (const \fBnum_int\fP &arg)"
.br
.ti -1c
.RI "\fBnum_int\fP ()"
.br
.ti -1c
.RI "\fBnum_int\fP (const num_int &a)"
.br
.ti -1c
.RI "\fBnum_int\fP (const string &a)"
.br
.ti -1c
.RI "\fBnum_int\fP (\fBdig\fP a0)"
.br
.ti -1c
.RI "\fBnum_int\fP (\fBdig\fP a1, \fBdig\fP a0)"
.br
.ti -1c
.RI "\fBnum_int\fP (\fBdig\fP a2, \fBdig\fP a1, \fBdig\fP a0)"
.br
.ti -1c
.RI "\fBnum_int\fP (const std::vector< \fBdig\fP > &arg)"
.br
.ti -1c
.RI "\fBnum_int\fP (const std::list< \fBdig\fP > &arg)"
.br
.ti -1c
.RI "\fBnum_int\fP (sign_e s, \fBdig\fP a0)"
.br
.ti -1c
.RI "\fBnum_int\fP (sign_e s, \fBdig\fP a1, \fBdig\fP a0)"
.br
.ti -1c
.RI "\fBnum_int\fP (sign_e s, \fBdig\fP a2, \fBdig\fP a1, \fBdig\fP a0)"
.br
.ti -1c
.RI "\fBnum_int\fP (sign_e s, const std::vector< \fBdig\fP > &arg, \fBforma_t\fP argforma=\fBnoraw\fP)"
.br
.ti -1c
.RI "\fBnum_int\fP (sign_e s, const std::list< \fBdig\fP > &arg)"
.br
.ti -1c
.RI "\fBnum_int\fP (\fBspardigs\fP a)"
.br
.ti -1c
.RI "\fBnum_int\fP (\fBpardigs\fP a)"
.br
.ti -1c
.RI "\fBnum_int\fP (sign_e s, \fBpardigs\fP a)"
.br
.ti -1c
.RI "\fBnum_int\fP (char ch)"
.br
.ti -1c
.RI "\fBnum_int\fP (uchint a)"
.br
.ti -1c
.RI "template<typename Int_T > \fBnum_int\fP (Int_T a)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator=\fP (const \fBnum_int\fP &a)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator=\fP (const num_uint< B > &a)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator=\fP (const pardigs_t< B > &a)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator=\fP (const spardigs_t< B > &a)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator=\fP (const dig_t< B > &a)"
.br
.ti -1c
.RI "template<typename Int_T > const \fBnum_int\fP & \fBoperator=\fP (Int_T a)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator=\fP (const std::vector< \fBdig\fP > &arg)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator=\fP (const std::list< \fBdig\fP > &arg)"
.br
.ti -1c
.RI "usint \fBceros_a_la_izqda\fP () const"
.br
.ti -1c
.RI "usint \fBunos_a_la_izqda\fP () const"
.br
.ti -1c
.RI "size_t \fBceros_a_la_drcha\fP () const"
.br
.ti -1c
.RI "size_t \fBunos_a_la_drcha\fP () const"
.br
.ti -1c
.RI "bool \fBfilled_of_all_digits_are_Bm1\fP () const"
.br
.ti -1c
.RI "bool \fBfilled_of_all_digits_are_0\fP () const"
.br
.ti -1c
.RI "usint \fBdigs_no_significativos\fP () const"
.br
.ti -1c
.RI "usint \fBdigs_fracc_no_significativos\fP () const"
.br
.ti -1c
.RI "usint \fBBm1_a_la_izqda\fP () const"
.br
.ti -1c
.RI "usint \fBBm1_a_la_drcha\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBnum_int\fP &arg) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBnum_int\fP &arg) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBnum_int\fP &arg) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBnum_int\fP &arg) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBnum_int\fP &arg) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBnum_int\fP &arg) const"
.br
.ti -1c
.RI "\fBnum_int\fP \fBoperator+\fP (const \fBnum_int\fP &arg) const"
.br
.ti -1c
.RI "\fBnum_int\fP \fBoperator\-\fP (const \fBnum_int\fP &arg) const"
.br
.ti -1c
.RI "\fBnum_int\fP \fBoperator*\fP (const \fBnum_int\fP &arg) const"
.br
.ti -1c
.RI "\fBnum_int\fP \fBoperator/\fP (const \fBnum_int\fP &arg) const"
.br
.ti -1c
.RI "\fBnum_int\fP \fBoperator%\fP (const \fBnum_int\fP &arg) const"
.br
.ti -1c
.RI "\fBnum_int\fP \fBoperator*\fP (\fBpardigs\fP a) const"
.br
.ti -1c
.RI "\fBnum_int\fP \fBoperator+\fP (\fBdig\fP arg) const"
.br
.ti -1c
.RI "\fBnum_int\fP \fBoperator\-\fP (\fBdig\fP arg) const"
.br
.ti -1c
.RI "\fBnum_int\fP \fBoperator*\fP (\fBdig\fP a) const"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator+=\fP (const \fBnum_int\fP &arg)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator\-=\fP (const \fBnum_int\fP &arg)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator*=\fP (const \fBnum_int\fP &arg)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator/=\fP (const \fBnum_int\fP &arg)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator%=\fP (const \fBnum_int\fP &arg)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator*=\fP (\fBpardigs\fP a)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator+=\fP (\fBdig\fP arg)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator\-=\fP (\fBdig\fP arg)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator*=\fP (\fBdig\fP arg)"
.br
.ti -1c
.RI "\fBnum_int\fP \fBoperator\-\fP () const"
.br
.ti -1c
.RI "\fBnum_int\fP \fBoperator!\fP () const"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBmC_B\fP ()"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBmC_Bm1\fP ()"
.br
.ti -1c
.RI "\fBnum_int\fP \fBabs\fP () const"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBabsp\fP ()"
.br
.ti -1c
.RI "\fBnum_int\fP \fBdivB\fP () const"
.br
.ti -1c
.RI "\fBdig\fP \fBremB\fP () const"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBdivBp\fP ()"
.br
.ti -1c
.RI "\fBdig\fP \fBremBp\fP ()"
.br
.ti -1c
.RI "\fBnum_int\fP \fBdiv2\fP () const"
.br
.ti -1c
.RI "\fBdig\fP \fBrem2\fP () const"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBdiv2p\fP ()"
.br
.ti -1c
.RI "\fBdig\fP \fBrem2p\fP ()"
.br
.ti -1c
.RI "\fBdig\fP \fBremBm1\fP () const"
.br
.ti -1c
.RI "pair< \fBnum_int\fP, \fBnum_int\fP > \fBEuclidDiv\fP (const \fBnum_int\fP &arg) const"
.br
.ti -1c
.RI "pair< \fBnum_int\fP, const \fBnum_int\fP & > \fBEuclidDivP\fP (const \fBnum_int\fP &arg)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "const \fBnum_int\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "const \fBnum_int\fP \fBoperator\-\-\fP (int)"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBreduce\fP ()"
.br
.ti -1c
.RI "\fBnum_int\fP \fBreduce\fP () const"
.br
.ti -1c
.RI "const \fBnum_int\fP & \fBreduce_fracc\fP ()"
.br
.ti -1c
.RI "\fBnum_int\fP \fBreduce_fracc\fP () const"
.br
.in -1c
.SS "Tipos privados"

.in +1c
.ti -1c
.RI "typedef dig_t< B > \fBdig\fP"
.br
.ti -1c
.RI "typedef num_basic_t< B > \fBnum_basic\fP"
.br
.ti -1c
.RI "typedef basic_string< dig_t< B > > \fBnbstr\fP"
.br
.ti -1c
.RI "typedef nbstr::iterator \fBstriterator\fP"
.br
.ti -1c
.RI "typedef nbstr::reverse_iterator \fBrstriterator\fP"
.br
.ti -1c
.RI "typedef nbstr::const_iterator \fBcstriterator\fP"
.br
.ti -1c
.RI "typedef nbstr::const_reverse_iterator \fBcrstriterator\fP"
.br
.ti -1c
.RI "typedef num_basic::iterator \fBb_iterator\fP"
.br
.ti -1c
.RI "typedef num_basic::reverse_iterator \fBb_riterator\fP"
.br
.ti -1c
.RI "typedef num_basic::const_iterator \fBb_citerator\fP"
.br
.ti -1c
.RI "typedef num_basic::const_reverse_iterator \fBb_criterator\fP"
.br
.ti -1c
.RI "typedef num_int::iterator \fBiterator\fP"
.br
.ti -1c
.RI "typedef num_int::reverse_iterator \fBriterator\fP"
.br
.ti -1c
.RI "typedef num_int::const_iterator \fBciterator\fP"
.br
.ti -1c
.RI "typedef num_int::const_reverse_iterator \fBcriterator\fP"
.br
.ti -1c
.RI "typedef n2digs_t< B > \fBn2digs\fP"
.br
.ti -1c
.RI "typedef pardigs_t< B > \fBpardigs\fP"
.br
.ti -1c
.RI "typedef spardigs_t< B > \fBspardigs\fP"
.br
.in -1c
.SS "Métodos privados"

.in +1c
.ti -1c
.RI "void \fBmC_B_incondicionado\fP ()"
.br
.ti -1c
.RI "\fBnum_int\fP & \fBinsert\fP (size_t pos1, const dig_t< B > chardig)"
.br
.ti -1c
.RI "\fBnum_int\fP & \fBinsert\fP (size_t pos1, size_t n, dig_t< B > c)"
.br
.ti -1c
.RI "\fBnum_int\fP & \fBerase\fP (size_t pos, size_t npos)"
.br
.ti -1c
.RI "\fBiterator\fP \fBerase\fP (\fBiterator\fP first, \fBiterator\fP last)"
.br
.ti -1c
.RI "void \fBdiv_gen_step\fP (const \fBnum_int\fP &dvsor, \fBnum_int\fP &rem, \fBnum_int\fP &coc, usint &ndig) const"
.br
.ti -1c
.RI "void \fBdivp_gen_step\fP (const \fBnum_int\fP &dvsor, \fBnum_int\fP &rem, \fBnum_int\fP &coc, usint &ndig)"
.br
.ti -1c
.RI "void \fBdiv_uno\fP (\fBnum_int\fP &rem, \fBnum_int\fP &dvndo, \fBnum_int\fP &dvsor, const usint long_dvndo, const usint long_dvsor) const"
.br
.in -1c
.SS "Atributos privados"

.in +1c
.ti -1c
.RI "sign_e \fBsigno\fP"
.br
.ti -1c
.RI "\fBspardigs\fP \fBaux\fP"
.br
.in -1c
.SS "Amigas"

.in +1c
.ti -1c
.RI "template<const uchint Base> istream & \fBoperator>>\fP (istream &is, \fBnum_int\fP< Base > &arg)"
.br
.ti -1c
.RI "template<const uchint Base> ostream & \fBoperator<<\fP (ostream &os, \fBnum_int\fP< Base > arg)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B>
.br
struct int_num_t< UINT_T, B >"
.PP
Definición en la línea \fB13\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef num_basic::const_iterator \fBint_num_t\fP< UINT_T, B >::b_citerator\fC [private]\fP"

.PP
Definición en la línea \fB24\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef num_basic::const_reverse_iterator \fBint_num_t\fP< UINT_T, B >::b_criterator\fC [private]\fP"

.PP
Definición en la línea \fB25\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef num_basic::iterator \fBint_num_t\fP< UINT_T, B >::b_iterator\fC [private]\fP"

.PP
Definición en la línea \fB22\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef num_basic::reverse_iterator \fBint_num_t\fP< UINT_T, B >::b_riterator\fC [private]\fP"

.PP
Definición en la línea \fB23\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef num_int::const_iterator \fBint_num_t\fP< UINT_T, B >::citerator\fC [private]\fP"

.PP
Definición en la línea \fB28\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef num_int::const_reverse_iterator \fBint_num_t\fP< UINT_T, B >::criterator\fC [private]\fP"

.PP
Definición en la línea \fB29\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef nbstr::const_reverse_iterator \fBint_num_t\fP< UINT_T, B >::crstriterator\fC [private]\fP"

.PP
Definición en la línea \fB21\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef nbstr::const_iterator \fBint_num_t\fP< UINT_T, B >::cstriterator\fC [private]\fP"

.PP
Definición en la línea \fB20\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef dig_t<B> \fBint_num_t\fP< UINT_T, B >::dig\fC [private]\fP"

.PP
Definición en la línea \fB15\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef num_int::iterator \fBint_num_t\fP< UINT_T, B >::iterator\fC [private]\fP"

.PP
Definición en la línea \fB26\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef n2digs_t<B> \fBint_num_t\fP< UINT_T, B >::n2digs\fC [private]\fP"

.PP
Definición en la línea \fB30\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef basic_string< dig_t<B> > \fBint_num_t\fP< UINT_T, B >::nbstr\fC [private]\fP"

.PP
Definición en la línea \fB17\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef num_basic_t<B> \fBint_num_t\fP< UINT_T, B >::num_basic\fC [private]\fP"

.PP
Definición en la línea \fB16\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef pardigs_t<B> \fBint_num_t\fP< UINT_T, B >::pardigs\fC [private]\fP"

.PP
Definición en la línea \fB31\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef num_int::reverse_iterator \fBint_num_t\fP< UINT_T, B >::riterator\fC [private]\fP"

.PP
Definición en la línea \fB27\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef nbstr::reverse_iterator \fBint_num_t\fP< UINT_T, B >::rstriterator\fC [private]\fP"

.PP
Definición en la línea \fB19\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef spardigs_t<B> \fBint_num_t\fP< UINT_T, B >::spardigs\fC [private]\fP"

.PP
Definición en la línea \fB32\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> typedef nbstr::iterator \fBint_num_t\fP< UINT_T, B >::striterator\fC [private]\fP"

.PP
Definición en la línea \fB18\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::abs () const\fC [inline]\fP"

.PP
Definición en la línea \fB1601\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::absp ()\fC [inline]\fP"

.PP
Definición en la línea \fB1610\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> usint \fBint_num_t\fP< UINT_T, B >::Bm1_a_la_drcha () const\fC [inline]\fP"

.PP
Definición en la línea \fB627\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> usint \fBint_num_t\fP< UINT_T, B >::Bm1_a_la_izqda () const\fC [inline]\fP"

.PP
Definición en la línea \fB613\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> size_t \fBint_num_t\fP< UINT_T, B >::ceros_a_la_drcha () const\fC [inline]\fP"

.PP
Definición en la línea \fB545\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> usint \fBint_num_t\fP< UINT_T, B >::ceros_a_la_izqda () const\fC [inline]\fP"

.PP
Definición en la línea \fB511\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> usint \fBint_num_t\fP< UINT_T, B >::digs_fracc_no_significativos () const\fC [inline]\fP"

.PP
Definición en la línea \fB607\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> usint \fBint_num_t\fP< UINT_T, B >::digs_no_significativos () const\fC [inline]\fP"

.PP
Definición en la línea \fB592\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::div2 () const\fC [inline]\fP"

.PP
Definición en la línea \fB1660\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::div2p ()\fC [inline]\fP"

.PP
Definición en la línea \fB1725\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> void \fBint_num_t\fP< UINT_T, B >::div_gen_step (const \fBnum_int\fP & dvsor, \fBnum_int\fP & rem, \fBnum_int\fP & coc, usint & ndig) const\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB1842\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> void \fBint_num_t\fP< UINT_T, B >::div_uno (\fBnum_int\fP & rem, \fBnum_int\fP & dvndo, \fBnum_int\fP & dvsor, const usint long_dvndo, const usint long_dvsor) const\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB1960\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::divB () const\fC [inline]\fP"

.PP
Definición en la línea \fB1624\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::divBp ()\fC [inline]\fP"

.PP
Definición en la línea \fB1642\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> void \fBint_num_t\fP< UINT_T, B >::divp_gen_step (const \fBnum_int\fP & dvsor, \fBnum_int\fP & rem, \fBnum_int\fP & coc, usint & ndig)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB1898\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBiterator\fP \fBint_num_t\fP< UINT_T, B >::erase (\fBiterator\fP first, \fBiterator\fP last)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB121\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::erase (size_t pos, size_t npos)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB106\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> pair< \fBnum_int\fP, \fBnum_int\fP > \fBint_num_t\fP< UINT_T, B >::EuclidDiv (const \fBnum_int\fP & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB2079\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> pair< \fBnum_int\fP, const \fBnum_int\fP & > \fBint_num_t\fP< UINT_T, B >::EuclidDivP (const \fBnum_int\fP & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB2126\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> bool \fBint_num_t\fP< UINT_T, B >::filled_of_all_digits_are_0 () const\fC [inline]\fP"

.PP
Definición en la línea \fB584\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> bool \fBint_num_t\fP< UINT_T, B >::filled_of_all_digits_are_Bm1 () const\fC [inline]\fP"

.PP
Definición en la línea \fB576\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::insert (size_t pos1, const dig_t< B > chardig)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB87\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::insert (size_t pos1, size_t n, dig_t< B > c)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB92\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::mC_B ()\fC [inline]\fP"

.PP
Definición en la línea \fB1555\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> void \fBint_num_t\fP< UINT_T, B >::mC_B_incondicionado ()\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB51\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::mC_Bm1 ()\fC [inline]\fP"

.PP
Definición en la línea \fB1582\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int ()\fC [inline]\fP"

.PP
Definición en la línea \fB133\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (char ch)\fC [inline]\fP"

.PP
Definición en la línea \fB316\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (const num_int & a)\fC [inline]\fP"

.PP
Definición en la línea \fB141\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (const std::list< \fBdig\fP > & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB217\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (const std::vector< \fBdig\fP > & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB207\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (const string & a)\fC [inline]\fP"

.PP
Definición en la línea \fB152\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (\fBdig\fP a0)\fC [inline]\fP"

.PP
Definición en la línea \fB178\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (\fBdig\fP a1, \fBdig\fP a0)\fC [inline]\fP"

.PP
Definición en la línea \fB186\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (\fBdig\fP a2, \fBdig\fP a1, \fBdig\fP a0)\fC [inline]\fP"

.PP
Definición en la línea \fB196\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> template<typename Int_T > \fBint_num_t\fP< UINT_T, B >::num_int (Int_T a)\fC [inline]\fP"

.PP
Definición en la línea \fB333\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (\fBpardigs\fP a)\fC [inline]\fP"

.PP
Definición en la línea \fB296\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (sign_e s, const std::list< \fBdig\fP > & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB274\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (sign_e s, const std::vector< \fBdig\fP > & arg, \fBforma_t\fP argforma = \fC\fBnoraw\fP\fP)\fC [inline]\fP"

.PP
Definición en la línea \fB263\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (sign_e s, \fBdig\fP a0)\fC [inline]\fP"

.PP
Definición en la línea \fB228\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (sign_e s, \fBdig\fP a1, \fBdig\fP a0)\fC [inline]\fP"

.PP
Definición en la línea \fB239\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (sign_e s, \fBdig\fP a2, \fBdig\fP a1, \fBdig\fP a0)\fC [inline]\fP"

.PP
Definición en la línea \fB250\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (sign_e s, \fBpardigs\fP a)\fC [inline]\fP"

.PP
Definición en la línea \fB306\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (\fBspardigs\fP a)\fC [inline]\fP"

.PP
Definición en la línea \fB286\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBint_num_t\fP< UINT_T, B >::num_int (uchint a)\fC [inline]\fP"

.PP
Definición en la línea \fB324\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::operator! () const\fC [inline]\fP"

.PP
Definición en la línea \fB1534\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> bool \fBint_num_t\fP< UINT_T, B >\fB::operator!\fP= (const \fBnum_int\fP & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB663\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::operator% (const \fBnum_int\fP & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB978\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator%= (const \fBnum_int\fP & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1343\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator&= (const \fBnum_int\fP & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB98\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::operator* (const \fBnum_int\fP & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB912\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::operator* (\fBdig\fP a) const\fC [inline]\fP"

.PP
Definición en la línea \fB1161\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::operator* (\fBpardigs\fP a) const\fC [inline]\fP"

.PP
Definición en la línea \fB1035\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator*= (const \fBnum_int\fP & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1275\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator*= (\fBdig\fP arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1475\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator*= (\fBpardigs\fP a)\fC [inline]\fP"

.PP
Definición en la línea \fB1394\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::operator+ (const \fBnum_int\fP & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB799\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::operator+ (\fBdig\fP arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB1068\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator++ ()\fC [inline]\fP"

.PP
Definición en la línea \fB2196\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::operator++ (int)\fC [inline]\fP"

.PP
Definición en la línea \fB2235\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator+= (const \fBnum_int\fP & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1189\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator+= (\fBdig\fP arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1427\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::operator\- () const\fC [inline]\fP"

.PP
Definición en la línea \fB1505\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::operator\- (const \fBnum_int\fP & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB855\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::operator\- (\fBdig\fP arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB1125\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator\-\- ()\fC [inline]\fP"

.PP
Definición en la línea \fB2274\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::operator\-\- (int)\fC [inline]\fP"

.PP
Definición en la línea \fB2330\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator\-= (const \fBnum_int\fP & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1232\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator\-= (\fBdig\fP arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1450\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::operator/ (const \fBnum_int\fP & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB931\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator/= (const \fBnum_int\fP & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1295\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> bool \fBint_num_t\fP< UINT_T, B >::operator< (const \fBnum_int\fP & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB765\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> bool \fBint_num_t\fP< UINT_T, B >::operator<= (const \fBnum_int\fP & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB708\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator= (const dig_t< B > & a)\fC [inline]\fP"

.PP
Definición en la línea \fB424\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator= (const \fBnum_int\fP & a)\fC [inline]\fP"

.PP
Definición en la línea \fB372\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator= (const num_uint< B > & a)\fC [inline]\fP"

.PP
Definición en la línea \fB384\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator= (const pardigs_t< B > & a)\fC [inline]\fP"

.PP
Definición en la línea \fB396\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator= (const spardigs_t< B > & a)\fC [inline]\fP"

.PP
Definición en la línea \fB410\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator= (const std::list< \fBdig\fP > & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB490\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator= (const std::vector< \fBdig\fP > & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB478\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> template<typename Int_T > const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::operator= (Int_T a)\fC [inline]\fP"

.PP
Definición en la línea \fB437\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> bool \fBint_num_t\fP< UINT_T, B >::operator== (const \fBnum_int\fP & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB647\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> bool \fBint_num_t\fP< UINT_T, B >::operator> (const \fBnum_int\fP & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB736\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> bool \fBint_num_t\fP< UINT_T, B >::operator>= (const \fBnum_int\fP & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB680\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> void \fBint_num_t\fP< UINT_T, B >::push_back (dig_t< B > arg)\fC [inline]\fP"

.PP
Definición en la línea \fB83\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> void \fBint_num_t\fP< UINT_T, B >::push_front (dig_t< B > parg)\fC [inline]\fP"

.PP
Definición en la línea \fB78\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::reduce ()\fC [inline]\fP"

.PP
Definición en la línea \fB2393\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::reduce () const\fC [inline]\fP"

.PP
Definición en la línea \fB2402\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnum_int\fP & \fBint_num_t\fP< UINT_T, B >::reduce_fracc ()\fC [inline]\fP"

.PP
Definición en la línea \fB2411\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnum_int\fP \fBint_num_t\fP< UINT_T, B >::reduce_fracc () const\fC [inline]\fP"

.PP
Definición en la línea \fB2419\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBdig\fP \fBint_num_t\fP< UINT_T, B >::rem2 () const\fC [inline]\fP"

.PP
Definición en la línea \fB1703\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBdig\fP \fBint_num_t\fP< UINT_T, B >::rem2p ()\fC [inline]\fP"

.PP
Definición en la línea \fB1769\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBdig\fP \fBint_num_t\fP< UINT_T, B >::remB () const\fC [inline]\fP"

.PP
Definición en la línea \fB1635\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBdig\fP \fBint_num_t\fP< UINT_T, B >::remBm1 () const\fC [inline]\fP"

.PP
Definición en la línea \fB1805\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBdig\fP \fBint_num_t\fP< UINT_T, B >::remBp ()\fC [inline]\fP"

.PP
Definición en la línea \fB1653\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> void \fBint_num_t\fP< UINT_T, B >::resize (size_t arg)\fC [inline]\fP"

.PP
Definición en la línea \fB73\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> size_t \fBint_num_t\fP< UINT_T, B >::size () const\fC [inline]\fP"

.PP
Definición en la línea \fB46\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> size_t \fBint_num_t\fP< UINT_T, B >::unos_a_la_drcha () const\fC [inline]\fP"

.PP
Definición en la línea \fB561\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> usint \fBint_num_t\fP< UINT_T, B >::unos_a_la_izqda () const\fC [inline]\fP"

.PP
Definición en la línea \fB528\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SH "Documentación de las funciones relacionadas y clases amigas"
.PP 
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> template<const uchint Base> ostream & operator<< (ostream & os, \fBnum_int\fP< Base > arg)\fC [friend]\fP"

.PP
Definición en la línea \fB2544\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> template<const uchint Base> istream & operator>> (istream & is, \fBnum_int\fP< Base > & arg)\fC [friend]\fP"

.PP
Definición en la línea \fB2437\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBspardigs\fP \fBint_num_t\fP< UINT_T, B >::aux\fC [private]\fP"

.PP
Definición en la línea \fB38\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> sign_e \fBint_num_t\fP< UINT_T, B >::signo\fC [private]\fP"

.PP
Definición en la línea \fB37\fP del archivo \fBint_num_t\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
