.TH "int_num_t.hpp" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
int_num_t.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'dig_t\&.hpp'\fP
.br
\fC#include 'int_reg_digs_t\&.hpp'\fP
.br
\fC#include 'nat_num_t\&.hpp'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBint_num_t< UINT_T, B >\fP"
.br
.in -1c
.SS "Enumeraciones"

.in +1c
.ti -1c
.RI "enum \fBforma_t\fP { \fBnoraw\fP, \fBraw\fP }"
.br
.in -1c
.SH "Documentación de las enumeraciones"
.PP 
.SS "enum \fBforma_t\fP"

.PP
\fBValores de enumeraciones\fP
.in +1c
.TP
\fB\fInoraw \fP\fP
.TP
\fB\fIraw \fP\fP
.PP
Definición en la línea \fB10\fP del archivo \fBint_num_t\&.hpp\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
