.TH "memory_handler.hpp" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
memory_handler.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'dig_t\&.hpp'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBdetails::cp_new< aT, T, num_vars, B >\fP"
.br
.ti -1c
.RI "struct \fBdetails::cp_new< 2 >\fP"
.br
.ti -1c
.RI "struct \fBdetails::cp_new< 1u >\fP"
.br
.ti -1c
.RI "struct \fBdetails::cp_new< 0u >\fP"
.br
.ti -1c
.RI "struct \fBdetails::cp_delete< aT, T, B >\fP"
.br
.ti -1c
.RI "struct \fBdetails::cp_delete< 2u >\fP"
.br
.ti -1c
.RI "struct \fBdetails::cp_delete< 1u >\fP"
.br
.ti -1c
.RI "struct \fBdetails::cp_delete< 0u >\fP"
.br
.ti -1c
.RI "class \fBfunc_refvar_t< aT, T >\fP"
.br
.ti -1c
.RI "class \fBfunc_refvar_t< INT **, INT *, INT >\fP"
.br
.ti -1c
.RI "class \fBfunc_refvar_t< UINT **, UINT *, UINT >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBdetails\fP"
.br
.in -1c
.SS "typedefs"

.in +1c
.ti -1c
.RI "using \fBpar_dir_t\fP = std::pair< uchint, uchint >"
.br
.ti -1c
.RI "using \fBfunc_refn2digs_prim_t\fP = std::map< std::string, \fBpar_dir_t\fP >"
.br
.ti -1c
.RI "using \fBfunc_refdig_prim_t\fP = std::map< std::string, \fBpar_dir_t\fP >"
.br
.ti -1c
.RI "using \fBINT\fP = long long int"
.br
.ti -1c
.RI "using \fBUINT\fP = unsigned long long int"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "template<typename aT , template< uchint > class T, usint num_vars> 
.br
requires (num_vars>0)aT ** \fBconstruye_matriz_de_variables\fP (aT **matd)"
.br
.ti -1c
.RI "template<typename aT , template< uchint > class T> void \fBdestruye_matriz_de_variables\fP (aT **matd)"
.br
.ti -1c
.RI "template<usint num_vars> 
.br
requires (num_vars>0)\fBINT\fP ** \fBconstruye_matriz_de_variables< INT, INT >\fP (\fBINT\fP **matd)"
.br
.ti -1c
.RI "template<> void \fBdestruye_matriz_de_variables< INT, INT >\fP (\fBINT\fP **matd)"
.br
.ti -1c
.RI "template<usint num_vars> \fBUINT\fP ** \fBconstruye_matriz_de_variables< UINT, UINT >\fP (\fBUINT\fP **matd)"
.br
.ti -1c
.RI "template<> void \fBdestruye_matriz_de_variables< UINT, UINT >\fP (\fBUINT\fP **matd)"
.br
.in -1c
.SH "Documentación de los 'typedefs'"
.PP 
.SS "using \fBfunc_refdig_prim_t\fP =  std::map< std::string , \fBpar_dir_t\fP >"

.PP
Definición en la línea \fB10\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "using \fBfunc_refn2digs_prim_t\fP =  std::map< std::string , \fBpar_dir_t\fP >"

.PP
Definición en la línea \fB9\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "using \fBINT\fP =  long long int"

.PP
Definición en la línea \fB147\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "using \fBpar_dir_t\fP =  std::pair< uchint , uchint >"

.PP
Definición en la línea \fB8\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "using \fBUINT\fP =  unsigned long long int"

.PP
Definición en la línea \fB165\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SH "Documentación de las funciones"
.PP 
.SS "template<typename aT , template< uchint > class T, usint num_vars> 
.br
requires (num_vars>0)aT ** construye_matriz_de_variables (aT ** matd)"

.PP
Definición en la línea \fB137\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<usint num_vars> 
.br
requires (num_vars>0)\fBINT\fP ** \fBconstruye_matriz_de_variables\fP< \fBINT\fP, \fBINT\fP > (\fBINT\fP ** matd)"

.PP
Definición en la línea \fB151\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<usint num_vars> \fBUINT\fP ** \fBconstruye_matriz_de_variables\fP< \fBUINT\fP, \fBUINT\fP > (\fBUINT\fP ** matd)"

.PP
Definición en la línea \fB168\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<typename aT , template< uchint > class T> void destruye_matriz_de_variables (aT ** matd)"

.PP
Definición en la línea \fB143\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<> void \fBdestruye_matriz_de_variables\fP< \fBINT\fP, \fBINT\fP > (\fBINT\fP ** matd)"

.PP
Definición en la línea \fB159\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SS "template<> void \fBdestruye_matriz_de_variables\fP< \fBUINT\fP, \fBUINT\fP > (\fBUINT\fP ** matd)"

.PP
Definición en la línea \fB175\fP del archivo \fBmemory_handler\&.hpp\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
