.TH "nat_num_t.hpp" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nat_num_t.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'base_num_t\&.hpp'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBnat_num_t< UINT_T, B >\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "template<const uchint Base> istream & \fBoperator>>\fP (istream &is, \fBnat_num_t\fP< Base > &arg)"
.br
.ti -1c
.RI "template<const uchint Base> ostream & \fBoperator<<\fP (ostream &os, const \fBnat_num_t\fP< Base > &arg)"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "template<const uchint Base> ostream & operator<< (ostream & os, const \fBnat_num_t\fP< Base > & arg)"

.PP
Definición en la línea \fB2103\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<const uchint Base> istream & operator>> (istream & is, \fBnat_num_t\fP< Base > & arg)"

.PP
Definición en la línea \fB1965\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
