.TH "nat_reg_digs_t.hpp" 3 "Lunes, 28 de Noviembre de 2022" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nat_reg_digs_t.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'dig_t\&.hpp'\fP
.br
\fC#include 'utilities\&.hpp'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBNumRepr::nat_reg_digs_t< UINT_T, B, L >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBNumRepr\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "template<type_traits::allowable_base_type_c Int_Type, Int_Type Base, \fBsize_t\fP Length> 
.br
requires (type_traits::suitable_base<Int_Type,Base>()&&(Length > 0))std::istream & \fBNumRepr::operator>>\fP (std::istream &is, \fBnat_reg_digs_t\fP< Int_Type, Base, Length > &arg)"
.br
.ti -1c
.RI "template<type_traits::allowable_base_type_c Int_Type, Int_Type Base, \fBsize_t\fP Long> 
.br
requires (type_traits::suitable_base<Int_Type,Base>())std::ostream & \fBNumRepr::operator<<\fP (std::ostream &os, const \fBnat_reg_digs_t\fP< Int_Type, Base, Long > &arg)"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
