.TH "nat_num_t< UINT_T, B >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nat_num_t< UINT_T, B >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nat_num_t\&.hpp>\fP
.PP
Herencias base_num_t< UINT_T, B >\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "void \fBpush_front\fP (\fBdig_t\fP parg)"
.br
.ti -1c
.RI "\fBdig_t\fP \fBoperator[]\fP (uint arg) const"
.br
.ti -1c
.RI "\fBdig_t\fP & \fBoperator[]\fP (uint arg)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBpush_back\fP (\fBdig_t\fP arg)"
.br
.ti -1c
.RI "\fBstriterator\fP \fBbegin\fP ()"
.br
.ti -1c
.RI "\fBcstriterator\fP \fBend\fP () const"
.br
.ti -1c
.RI "\fBnat_num_t\fP ()"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator=\fP (const \fBnat_num_t\fP &a)"
.br
.ti -1c
.RI "\fBnat_num_t\fP & \fBoperator=\fP (\fBnat_num_t\fP &a)"
.br
.ti -1c
.RI "\fBnat_num_t\fP (const \fBnat_num_t\fP &a)"
.br
.ti -1c
.RI "\fBnat_num_t\fP (const string &a)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator=\fP (const string &a)"
.br
.ti -1c
.RI "\fBoperator string\fP () const"
.br
.ti -1c
.RI "\fBnat_num_t\fP (dig a0)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator=\fP (const dig &a0)"
.br
.ti -1c
.RI "\fBnat_num_t\fP (const dig &a1, const dig &a0)"
.br
.ti -1c
.RI "\fBnat_num_t\fP (const dig &a2, const dig &a1, const dig &a0)"
.br
.ti -1c
.RI "\fBnat_num_t\fP (const vector< dig > &arg)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator=\fP (const vector< dig > &arg)"
.br
.ti -1c
.RI "\fBoperator vector< dig >\fP () const"
.br
.ti -1c
.RI "\fBnat_num_t\fP (const pardigs &a)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator=\fP (const pardigs &a)"
.br
.ti -1c
.RI "\fBnat_num_t\fP (const n2digs &a)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator=\fP (const n2digs &a)"
.br
.ti -1c
.RI "\fBnat_num_t\fP (char ch)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator=\fP (char ch)"
.br
.ti -1c
.RI "\fBnat_num_t\fP (uchint a)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator=\fP (uchint a)"
.br
.ti -1c
.RI "\fBnat_num_t\fP (usint a)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator=\fP (usint a)"
.br
.ti -1c
.RI "\fBnat_num_t\fP (uint a)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator=\fP (uint a)"
.br
.ti -1c
.RI "\fBnat_num_t\fP (ulint a)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator=\fP (ulint a)"
.br
.ti -1c
.RI "\fBnat_num_t\fP (ullint a)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator=\fP (ullint a)"
.br
.ti -1c
.RI "\fBoperator uint\fP () const"
.br
.ti -1c
.RI "\fBoperator usint\fP () const"
.br
.ti -1c
.RI "\fBoperator uchint\fP () const"
.br
.ti -1c
.RI "\fBoperator ulint\fP () const"
.br
.ti -1c
.RI "\fBoperator ullint\fP () const"
.br
.ti -1c
.RI "\fBnat_num_t\fP & \fBoperator=\fP (dig a0)"
.br
.ti -1c
.RI "usint \fBceros_a_la_izqda\fP () const"
.br
.ti -1c
.RI "size_t \fBceros_a_la_drcha\fP () const"
.br
.ti -1c
.RI "usint \fBdigs_no_significativos\fP () const"
.br
.ti -1c
.RI "usint \fBdigs_fracc_no_significativos\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBnat_num_t\fP &arg) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBnat_num_t\fP &arg) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBnat_num_t\fP &arg) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBnat_num_t\fP &arg) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBnat_num_t\fP &arg) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBnat_num_t\fP &arg) const"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBoperator+\fP (const \fBnat_num_t\fP &arg) const"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBoperator\-\fP (const \fBnat_num_t\fP &arg) const"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBoperator*\fP (const \fBnat_num_t\fP &arg) const"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBoperator/\fP (const \fBnat_num_t\fP &arg) const"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBoperator%\fP (const \fBnat_num_t\fP &arg) const"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBoperator*\fP (pardigs a) const"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBoperator+\fP (dig arg) const"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBoperator\-\fP (dig arg) const"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBoperator*\fP (dig a) const"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator+=\fP (const \fBnat_num_t\fP &arg)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator\-=\fP (const \fBnat_num_t\fP &arg)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator*=\fP (const \fBnat_num_t\fP &arg)"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBsubstr\fP (size_t pos, size_t n) const"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator/=\fP (const \fBnat_num_t\fP &arg)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator%=\fP (const \fBnat_num_t\fP &arg)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator*=\fP (pardigs a)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator+=\fP (dig arg)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator\-=\fP (dig arg)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator*=\fP (dig arg)"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBoperator\-\fP () const"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBminus\fP (size_t sz) const"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBoperator!\fP () const"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBmC_B\fP ()"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBmC_Bm1\fP ()"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBabs\fP () const"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBm_abs\fP ()"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBdivB\fP () const"
.br
.ti -1c
.RI "dig \fBremB\fP () const"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBm_divB\fP ()"
.br
.ti -1c
.RI "dig \fBm_remB\fP ()"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBdiv2\fP () const"
.br
.ti -1c
.RI "dig \fBrem2\fP () const"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBm_div2\fP ()"
.br
.ti -1c
.RI "dig \fBm_rem2\fP ()"
.br
.ti -1c
.RI "dig \fBremBm1\fP () const"
.br
.ti -1c
.RI "pardigs \fBg_aux\fP () const"
.br
.ti -1c
.RI "void \fBp_aux\fP (pardigs arg)"
.br
.ti -1c
.RI "bool \fBes_cero\fP () const"
.br
.ti -1c
.RI "bool \fBno_es_cero\fP () const"
.br
.ti -1c
.RI "pair< \fBnat_num_t\fP, \fBnat_num_t\fP > \fBEuclidDiv\fP (const \fBnat_num_t\fP &arg) const"
.br
.ti -1c
.RI "pair< \fBnat_num_t\fP, const \fBnat_num_t\fP & > \fBm_EuclidDiv\fP (const \fBnat_num_t\fP &arg)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBoperator\-\-\fP (int)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBreduce\fP ()"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBreduce\fP () const"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBreduce_fracc\fP ()"
.br
.ti -1c
.RI "\fBnat_num_t\fP \fBreduce_fracc\fP () const"
.br
.in -1c
.SS "Tipos privados"

.in +1c
.ti -1c
.RI "using \fBdig_t\fP = \fBdig_t\fP< UINT_T, B >"
.br
.ti -1c
.RI "using \fBbase_num_t\fP = \fBbase_num_t\fP< UINT_T, B >"
.br
.ti -1c
.RI "using \fBnbstr\fP = basic_string< dig >"
.br
.ti -1c
.RI "using \fBstriterator\fP = typename nbstr::iterator"
.br
.ti -1c
.RI "using \fBrstriterator\fP = typename nbstr::reverse_iterator"
.br
.ti -1c
.RI "using \fBcstriterator\fP = typename nbstr::const_iterator"
.br
.ti -1c
.RI "using \fBcrstriterator\fP = typename nbstr::const_reverse_iterator"
.br
.ti -1c
.RI "using \fBb_iterator\fP = typename \fBbase_num_t\fP< UINT_T, B >\fB::iterator\fP"
.br
.ti -1c
.RI "using \fBb_riterator\fP = typename \fBbase_num_t\fP< UINT_T, B >::reverse_iterator"
.br
.ti -1c
.RI "using \fBb_citerator\fP = typename \fBbase_num_t\fP< UINT_T, B >::const_iterator"
.br
.ti -1c
.RI "using \fBb_criterator\fP = typename \fBbase_num_t\fP< UINT_T, B >::const_reverse_iterator"
.br
.ti -1c
.RI "using \fBiterator\fP = typename \fBnat_num_t\fP< UINT_T, B >::iterator"
.br
.ti -1c
.RI "using \fBriterator\fP = typename \fBnat_num_t\fP< UINT_T, B >::reverse_iterator"
.br
.ti -1c
.RI "using \fBciterator\fP = typename \fBnat_num_t\fP< UINT_T, B >::const_iterator"
.br
.ti -1c
.RI "using \fBcriterator\fP = typename \fBnat_num_t\fP< UINT_T, B >::const_reverse_iterator"
.br
.ti -1c
.RI "template<type_traits::unsigned_integral_c UINT_T, UINT_T B, size_t N> using \fBbase_N_t\fP = std::array< \fBdig_t\fP< UINT_T, B >, N >"
.br
.ti -1c
.RI "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBbase_t\fP = \fBnat_reg_N_digs_t\fP< UINT_T, B, 2 >"
.br
.ti -1c
.RI "template<type_traits::unsigned_integral_c UINT_T, UINT_T B, size_t N> using \fBnat_reg_N_digs_t\fP = \fBnat_reg_N_digs_t\fP< UINT_T, B, N >"
.br
.ti -1c
.RI "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_reg_digs_t\fP = \fBnat_reg_N_digs_t\fP< UINT_T, B, 2 >"
.br
.ti -1c
.RI "template<type_traits::unsigned_integral_c UINT_T, UINT_T B, size_t N> using \fBint_reg_N_digs_t\fP = \fBint_reg_N_digs_t\fP< UINT_T, B, N >"
.br
.ti -1c
.RI "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBint_reg_digs_t\fP = \fBint_reg_N_digs_t\fP< UINT_T, B, 2 >"
.br
.in -1c
.SS "Métodos privados"

.in +1c
.ti -1c
.RI "void \fBresize\fP (size_t arg)"
.br
.ti -1c
.RI "\fBnat_num_t\fP & \fBinsert\fP (size_t pos1, const \fBdig_t\fP chardig)"
.br
.ti -1c
.RI "\fBnat_num_t\fP & \fBinsert\fP (size_t pos1, size_t n, \fBdig_t\fP c)"
.br
.ti -1c
.RI "const \fBnat_num_t\fP & \fBoperator&=\fP (const \fBnat_num_t\fP &arg)"
.br
.ti -1c
.RI "\fBnat_num_t\fP & \fBerase\fP (size_t pos, size_t npos)"
.br
.ti -1c
.RI "\fBiterator\fP \fBerase\fP (\fBiterator\fP first, \fBiterator\fP last)"
.br
.ti -1c
.RI "void \fBdiv_gen_step\fP (const \fBnat_num_t\fP &dvsor, \fBnat_num_t\fP &rem, \fBnat_num_t\fP &coc, usint &ndig) const"
.br
.ti -1c
.RI "void \fBdiv_uno\fP (\fBnat_num_t\fP &rem, \fBnat_num_t\fP &dvndo, \fBnat_num_t\fP &dvsor, const usint szndo, const usint szsor) const"
.br
.in -1c
.SS "Atributos privados"

.in +1c
.ti -1c
.RI "pardigs \fBaux\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B>
.br
class nat_num_t< UINT_T, B >"
.PP
Definición en la línea \fB9\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::b_citerator =  typename \fBbase_num_t\fP<UINT_T,B>::const_iterator\fC [private]\fP"

.PP
Definición en la línea \fB20\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::b_criterator =  typename \fBbase_num_t\fP<UINT_T,B>::const_reverse_iterator\fC [private]\fP"

.PP
Definición en la línea \fB21\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::b_iterator =  typename \fBbase_num_t\fP<UINT_T,B>\fB::iterator\fP\fC [private]\fP"

.PP
Definición en la línea \fB18\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::b_riterator =  typename \fBbase_num_t\fP<UINT_T,B>::reverse_iterator\fC [private]\fP"

.PP
Definición en la línea \fB19\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> template<type_traits::unsigned_integral_c UINT_T, UINT_T B, size_t N> using \fBnat_num_t\fP< UINT_T, B >::base_N_t =  std::array<\fBdig_t\fP<UINT_T,B>,N>\fC [private]\fP"

.PP
Definición en la línea \fB27\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::base_num_t =  \fBbase_num_t\fP<UINT_T,B>\fC [private]\fP"

.PP
Definición en la línea \fB12\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::base_t =  \fBnat_reg_N_digs_t\fP<UINT_T,B,2>\fC [private]\fP"

.PP
Definición en la línea \fB29\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::citerator =  typename \fBnat_num_t\fP<UINT_T,B>::const_iterator\fC [private]\fP"

.PP
Definición en la línea \fB24\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::criterator =  typename \fBnat_num_t\fP<UINT_T,B>::const_reverse_iterator\fC [private]\fP"

.PP
Definición en la línea \fB25\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::crstriterator =  typename nbstr::const_reverse_iterator\fC [private]\fP"

.PP
Definición en la línea \fB17\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::cstriterator =  typename nbstr::const_iterator\fC [private]\fP"

.PP
Definición en la línea \fB16\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::dig_t =  \fBdig_t\fP<UINT_T,B>\fC [private]\fP"

.PP
Definición en la línea \fB11\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::int_reg_digs_t =  \fBint_reg_N_digs_t\fP<UINT_T,B,2>\fC [private]\fP"

.PP
Definición en la línea \fB37\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> template<type_traits::unsigned_integral_c UINT_T, UINT_T B, size_t N> using \fBnat_num_t\fP< UINT_T, B >::int_reg_N_digs_t =  \fBint_reg_N_digs_t\fP<UINT_T,B,N>\fC [private]\fP"

.PP
Definición en la línea \fB35\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::iterator =  typename \fBnat_num_t\fP<UINT_T,B>::iterator\fC [private]\fP"

.PP
Definición en la línea \fB22\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::nat_reg_digs_t =  \fBnat_reg_N_digs_t\fP<UINT_T,B,2>\fC [private]\fP"

.PP
Definición en la línea \fB33\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> template<type_traits::unsigned_integral_c UINT_T, UINT_T B, size_t N> using \fBnat_num_t\fP< UINT_T, B >::nat_reg_N_digs_t =  \fBnat_reg_N_digs_t\fP<UINT_T,B,N>\fC [private]\fP"

.PP
Definición en la línea \fB31\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::nbstr =  basic_string< dig >\fC [private]\fP"

.PP
Definición en la línea \fB13\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::riterator =  typename \fBnat_num_t\fP<UINT_T,B>::reverse_iterator\fC [private]\fP"

.PP
Definición en la línea \fB23\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::rstriterator =  typename nbstr::reverse_iterator\fC [private]\fP"

.PP
Definición en la línea \fB15\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> using \fBnat_num_t\fP< UINT_T, B >::striterator =  typename nbstr::iterator\fC [private]\fP"

.PP
Definición en la línea \fB14\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >\fB::nat_num_t\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB137\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >\fB::nat_num_t\fP (const \fBnat_num_t\fP< UINT_T, B > & a)\fC [inline]\fP"

.PP
Definición en la línea \fB170\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >\fB::nat_num_t\fP (const string & a)\fC [inline]\fP"

.PP
Definición en la línea \fB180\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >\fB::nat_num_t\fP (dig a0)\fC [inline]\fP"

.PP
Definición en la línea \fB210\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >\fB::nat_num_t\fP (const dig & a1, const dig & a0)\fC [inline]\fP"

.PP
Definición en la línea \fB227\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >\fB::nat_num_t\fP (const dig & a2, const dig & a1, const dig & a0)\fC [inline]\fP"

.PP
Definición en la línea \fB237\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >\fB::nat_num_t\fP (const vector< dig > & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB248\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >\fB::nat_num_t\fP (const pardigs & a)\fC [inline]\fP"

.PP
Definición en la línea \fB277\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >\fB::nat_num_t\fP (const n2digs & a)\fC [inline]\fP"

.PP
Definición en la línea \fB298\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >\fB::nat_num_t\fP (char ch)\fC [inline]\fP"

.PP
Definición en la línea \fB319\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >\fB::nat_num_t\fP (uchint a)\fC [inline]\fP"

.PP
Definición en la línea \fB336\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >\fB::nat_num_t\fP (usint a)\fC [inline]\fP"

.PP
Definición en la línea \fB353\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >\fB::nat_num_t\fP (uint a)\fC [inline]\fP"

.PP
Definición en la línea \fB386\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >\fB::nat_num_t\fP (ulint a)\fC [inline]\fP"

.PP
Definición en la línea \fB419\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >\fB::nat_num_t\fP (ullint a)\fC [inline]\fP"

.PP
Definición en la línea \fB450\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::abs () const\fC [inline]\fP"

.PP
Definición en la línea \fB1393\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBstriterator\fP \fBnat_num_t\fP< UINT_T, B >::begin ()\fC [inline]\fP"

.PP
Definición en la línea \fB126\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> size_t \fBnat_num_t\fP< UINT_T, B >::ceros_a_la_drcha () const\fC [inline]\fP"

.PP
Definición en la línea \fB579\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> usint \fBnat_num_t\fP< UINT_T, B >::ceros_a_la_izqda () const\fC [inline]\fP"

.PP
Definición en la línea \fB566\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> void \fBnat_num_t\fP< UINT_T, B >::clear ()\fC [inline]\fP"

.PP
Definición en la línea \fB116\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> usint \fBnat_num_t\fP< UINT_T, B >::digs_fracc_no_significativos () const\fC [inline]\fP"

.PP
Definición en la línea \fB599\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> usint \fBnat_num_t\fP< UINT_T, B >::digs_no_significativos () const\fC [inline]\fP"

.PP
Definición en la línea \fB594\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::div2 () const\fC [inline]\fP"

.PP
Definición en la línea \fB1437\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> void \fBnat_num_t\fP< UINT_T, B >::div_gen_step (const \fBnat_num_t\fP< UINT_T, B > & dvsor, \fBnat_num_t\fP< UINT_T, B > & rem, \fBnat_num_t\fP< UINT_T, B > & coc, usint & ndig) const\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB1608\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> void \fBnat_num_t\fP< UINT_T, B >::div_uno (\fBnat_num_t\fP< UINT_T, B > & rem, \fBnat_num_t\fP< UINT_T, B > & dvndo, \fBnat_num_t\fP< UINT_T, B > & dvsor, const usint szndo, const usint szsor) const\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB1682\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::divB () const\fC [inline]\fP"

.PP
Definición en la línea \fB1408\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBcstriterator\fP \fBnat_num_t\fP< UINT_T, B >::end () const\fC [inline]\fP"

.PP
Definición en la línea \fB131\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBiterator\fP \fBnat_num_t\fP< UINT_T, B >::erase (\fBiterator\fP first, \fBiterator\fP last)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB97\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::erase (size_t pos, size_t npos)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB85\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> bool \fBnat_num_t\fP< UINT_T, B >::es_cero () const\fC [inline]\fP"

.PP
Definición en la línea \fB1666\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> pair< \fBnat_num_t\fP, \fBnat_num_t\fP > \fBnat_num_t\fP< UINT_T, B >::EuclidDiv (const \fBnat_num_t\fP< UINT_T, B > & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB1745\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> pardigs \fBnat_num_t\fP< UINT_T, B >::g_aux () const\fC [inline]\fP"

.PP
Definición en la línea \fB1590\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::insert (size_t pos1, const \fBdig_t\fP chardig)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB66\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::insert (size_t pos1, size_t n, \fBdig_t\fP c)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB71\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::m_abs ()\fC [inline]\fP"

.PP
Definición en la línea \fB1397\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::m_div2 ()\fC [inline]\fP"

.PP
Definición en la línea \fB1499\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::m_divB ()\fC [inline]\fP"

.PP
Definición en la línea \fB1423\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> pair< \fBnat_num_t\fP, const \fBnat_num_t\fP & > \fBnat_num_t\fP< UINT_T, B >::m_EuclidDiv (const \fBnat_num_t\fP< UINT_T, B > & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1789\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> dig \fBnat_num_t\fP< UINT_T, B >::m_rem2 ()\fC [inline]\fP"

.PP
Definición en la línea \fB1541\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> dig \fBnat_num_t\fP< UINT_T, B >::m_remB ()\fC [inline]\fP"

.PP
Definición en la línea \fB1431\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::mC_B ()\fC [inline]\fP"

.PP
Definición en la línea \fB1343\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::mC_Bm1 ()\fC [inline]\fP"

.PP
Definición en la línea \fB1376\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::minus (size_t sz) const\fC [inline]\fP"

.PP
Definición en la línea \fB1273\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> bool \fBnat_num_t\fP< UINT_T, B >::no_es_cero () const\fC [inline]\fP"

.PP
Definición en la línea \fB1674\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >::operator string () const\fC [inline]\fP"

.PP
Definición en la línea \fB200\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >::operator uchint () const\fC [inline]\fP"

.PP
Definición en la línea \fB509\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >::operator uint () const\fC [inline]\fP"

.PP
Definición en la línea \fB481\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >::operator ulint () const\fC [inline]\fP"

.PP
Definición en la línea \fB523\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >::operator ullint () const\fC [inline]\fP"

.PP
Definición en la línea \fB537\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >::operator usint () const\fC [inline]\fP"

.PP
Definición en la línea \fB495\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP< UINT_T, B >::operator vector< dig > () const\fC [inline]\fP"

.PP
Definición en la línea \fB267\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::operator! () const\fC [inline]\fP"

.PP
Definición en la línea \fB1324\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> bool \fBnat_num_t\fP< UINT_T, B >\fB::operator!\fP= (const \fBnat_num_t\fP< UINT_T, B > & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB626\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::operator% (const \fBnat_num_t\fP< UINT_T, B > & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB849\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator%= (const \fBnat_num_t\fP< UINT_T, B > & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1134\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator&= (const \fBnat_num_t\fP< UINT_T, B > & arg)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB77\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::operator* (const \fBnat_num_t\fP< UINT_T, B > & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB768\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::operator* (dig a) const\fC [inline]\fP"

.PP
Definición en la línea \fB957\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::operator* (pardigs a) const\fC [inline]\fP"

.PP
Definición en la línea \fB863\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator*= (const \fBnat_num_t\fP< UINT_T, B > & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1045\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator*= (dig arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1214\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator*= (pardigs a)\fC [inline]\fP"

.PP
Definición en la línea \fB1149\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::operator+ (const \fBnat_num_t\fP< UINT_T, B > & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB712\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::operator+ (dig arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB897\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator++ ()\fC [inline]\fP"

.PP
Definición en la línea \fB1844\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::operator++ (int)\fC [inline]\fP"

.PP
Definición en la línea \fB1850\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator+= (const \fBnat_num_t\fP< UINT_T, B > & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB984\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator+= (dig arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1159\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::operator\- () const\fC [inline]\fP"

.PP
Definición en la línea \fB1239\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::operator\- (const \fBnat_num_t\fP< UINT_T, B > & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB754\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::operator\- (dig arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB927\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator\-\- ()\fC [inline]\fP"

.PP
Definición en la línea \fB1858\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::operator\-\- (int)\fC [inline]\fP"

.PP
Definición en la línea \fB1864\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator\-= (const \fBnat_num_t\fP< UINT_T, B > & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1031\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator\-= (dig arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1184\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::operator/ (const \fBnat_num_t\fP< UINT_T, B > & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB791\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator/= (const \fBnat_num_t\fP< UINT_T, B > & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1074\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> bool \fBnat_num_t\fP< UINT_T, B >::operator< (const \fBnat_num_t\fP< UINT_T, B > & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB690\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> bool \fBnat_num_t\fP< UINT_T, B >::operator<= (const \fBnat_num_t\fP< UINT_T, B > & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB659\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator= (char ch)\fC [inline]\fP"

.PP
Definición en la línea \fB327\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator= (const dig & a0)\fC [inline]\fP"

.PP
Definición en la línea \fB218\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator= (const n2digs & a)\fC [inline]\fP"

.PP
Definición en la línea \fB308\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator= (const \fBnat_num_t\fP< UINT_T, B > & a)\fC [inline]\fP"

.PP
Definición en la línea \fB144\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator= (const pardigs & a)\fC [inline]\fP"

.PP
Definición en la línea \fB287\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator= (const string & a)\fC [inline]\fP"

.PP
Definición en la línea \fB190\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator= (const vector< dig > & arg)\fC [inline]\fP"

.PP
Definición en la línea \fB257\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator= (dig a0)\fC [inline]\fP"

.PP
Definición en la línea \fB551\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator= (\fBnat_num_t\fP< UINT_T, B > & a)\fC [inline]\fP"

.PP
Definición en la línea \fB157\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator= (uchint a)\fC [inline]\fP"

.PP
Definición en la línea \fB344\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator= (uint a)\fC [inline]\fP"

.PP
Definición en la línea \fB403\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator= (ulint a)\fC [inline]\fP"

.PP
Definición en la línea \fB434\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator= (ullint a)\fC [inline]\fP"

.PP
Definición en la línea \fB465\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator= (usint a)\fC [inline]\fP"

.PP
Definición en la línea \fB369\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> bool \fBnat_num_t\fP< UINT_T, B >::operator== (const \fBnat_num_t\fP< UINT_T, B > & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB611\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> bool \fBnat_num_t\fP< UINT_T, B >::operator> (const \fBnat_num_t\fP< UINT_T, B > & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB674\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> bool \fBnat_num_t\fP< UINT_T, B >::operator>= (const \fBnat_num_t\fP< UINT_T, B > & arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB642\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBdig_t\fP & \fBnat_num_t\fP< UINT_T, B >::operator[] (uint arg)\fC [inline]\fP"

.PP
Definición en la línea \fB111\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBdig_t\fP \fBnat_num_t\fP< UINT_T, B >::operator[] (uint arg) const\fC [inline]\fP"

.PP
Definición en la línea \fB107\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> void \fBnat_num_t\fP< UINT_T, B >::p_aux (pardigs arg)\fC [inline]\fP"

.PP
Definición en la línea \fB1594\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> void \fBnat_num_t\fP< UINT_T, B >::push_back (\fBdig_t\fP arg)\fC [inline]\fP"

.PP
Definición en la línea \fB121\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> void \fBnat_num_t\fP< UINT_T, B >::push_front (\fBdig_t\fP parg)\fC [inline]\fP"

.PP
Definición en la línea \fB60\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::reduce ()\fC [inline]\fP"

.PP
Definición en la línea \fB1877\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::reduce () const\fC [inline]\fP"

.PP
Definición en la línea \fB1895\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> const \fBnat_num_t\fP & \fBnat_num_t\fP< UINT_T, B >::reduce_fracc ()\fC [inline]\fP"

.PP
Definición en la línea \fB1914\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::reduce_fracc () const\fC [inline]\fP"

.PP
Definición en la línea \fB1932\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> dig \fBnat_num_t\fP< UINT_T, B >::rem2 () const\fC [inline]\fP"

.PP
Definición en la línea \fB1479\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> dig \fBnat_num_t\fP< UINT_T, B >::remB () const\fC [inline]\fP"

.PP
Definición en la línea \fB1417\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> dig \fBnat_num_t\fP< UINT_T, B >::remBm1 () const\fC [inline]\fP"

.PP
Definición en la línea \fB1561\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> void \fBnat_num_t\fP< UINT_T, B >::resize (size_t arg)\fC [inline]\fP, \fC [private]\fP"

.PP
Definición en la línea \fB54\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> size_t \fBnat_num_t\fP< UINT_T, B >::size () const\fC [inline]\fP"

.PP
Definición en la línea \fB49\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> \fBnat_num_t\fP \fBnat_num_t\fP< UINT_T, B >::substr (size_t pos, size_t n) const\fC [inline]\fP"

.PP
Definición en la línea \fB1068\fP del archivo \fBnat_num_t\&.hpp\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "template<type_traits::unsigned_integral_c UINT_T, UINT_T B> pardigs \fBnat_num_t\fP< UINT_T, B >::aux\fC [private]\fP"

.PP
Definición en la línea \fB41\fP del archivo \fBnat_num_t\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
