.TH "NumRepr::type_traits::integral_c" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::integral_c
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SH "Concept definition"
.PP 
.PP
.nf
template<typename INT_T>
concept NumRepr::type_traits::integral_c =  is_integral_type_v<INT_T>
.fi
.SH "Descripción detallada"
.PP 
Definición en la línea \fB202\fP del archivo \fBbasic_types\&.hpp\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
