.TH "NumRepr::type_traits::uint_type_for_radix_c" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::uint_type_for_radix_c \- CONCEPT FOR UNSIGNED INTEGRAL TYPES VALID FOR THE RADIX\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SH "Concept definition"
.PP 
.PP
.nf
template<typename UINT_T>
concept NumRepr::type_traits::uint_type_for_radix_c =  is_uint_type_for_radix_v<UINT_T>
.fi
.SH "Descripción detallada"
.PP 
CONCEPT FOR UNSIGNED INTEGRAL TYPES VALID FOR THE RADIX\&. 
.PP
Definición en la línea \fB178\fP del archivo \fBbasic_types\&.hpp\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
