.TH "NumRepr::type_traits::char_type_c" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::char_type_c
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SH "Concept definition"
.PP 
.PP
.nf
template<typename CharT>
concept NumRepr::type_traits::char_type_c =  std::is_same_v<CharT,char>                                                 ||
                                                                                        std::is_same_v<CharT,signed char>               ||
                                                                                        std::is_same_v<CharT,unsigned char>     ||
                                                                                        std::is_same_v<CharT,wchar_t>
.fi
.SH "Descripción detallada"
.PP 
Definición en la línea \fB119\fP del archivo \fBbasic_types\&.hpp\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
