.TH "NumRepr::type_traits::ugly_details_SInt_for_SInt::__sig_SInt_for_SInt_t< schint_t >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::ugly_details_SInt_for_SInt::__sig_SInt_for_SInt_t< schint_t >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "using \fBtype\fP = std::conditional_t< \fBsigned_gt_signed_v\fP< \fBssint_t\fP >, \fBssint_t\fP, typename \fB__sig_SInt_for_SInt_t\fP< \fBssint_t\fP >::type >"
.br
.in -1c
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "template<typename SINT_T > static constexpr bool \fBsigned_gt_signed_v\fP = \fBgt_sz_v\fP<SINT_T,\fBschint_t\fP>"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB456\fP del archivo \fBbasic_types\&.hpp\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "using \fBNumRepr::type_traits::ugly_details_SInt_for_SInt::__sig_SInt_for_SInt_t\fP< \fBschint_t\fP >::type =  std::conditional_t< \fBsigned_gt_signed_v\fP<\fBssint_t\fP>, \fBssint_t\fP, typename \fB__sig_SInt_for_SInt_t\fP<\fBssint_t\fP>::type >"

.PP
Definición en la línea \fB460\fP del archivo \fBbasic_types\&.hpp\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "template<typename SINT_T > constexpr bool \fBNumRepr::type_traits::ugly_details_SInt_for_SInt::__sig_SInt_for_SInt_t\fP< \fBschint_t\fP >::signed_gt_signed_v = \fBgt_sz_v\fP<SINT_T,\fBschint_t\fP>\fC [inline]\fP, \fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB458\fP del archivo \fBbasic_types\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
