.TH "NumRepr::type_traits::detail::__sig_SInt_for_UInt_t< unsigned int >" 3 "Lunes, 28 de Noviembre de 2022" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::detail::__sig_SInt_for_UInt_t< unsigned int >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "using \fBtype\fP = signed long long int"
.br
.in -1c
.SH "Descripción detallada"
.PP 
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "using \fBNumRepr::type_traits::detail::__sig_SInt_for_UInt_t\fP< unsigned int >::type =  signed long long int"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
