.TH "NumRepr::auxiliary_types" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::auxiliary_types
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBresbinop_t\fP"
.br
.RI "auxiliary types for digit type and its operations "
.ti -1c
.RI "struct \fBresbinop_t< T, binop_e::add >\fP"
.br
.ti -1c
.RI "struct \fBresbinop_t< T, binop_e::div >\fP"
.br
.ti -1c
.RI "struct \fBresbinop_t< T, binop_e::fediv >\fP"
.br
.ti -1c
.RI "struct \fBresbinop_t< T, binop_e::mult >\fP"
.br
.ti -1c
.RI "struct \fBresbinop_t< T, binop_e::rem >\fP"
.br
.ti -1c
.RI "struct \fBresbinop_t< T, binop_e::sub >\fP"
.br
.ti -1c
.RI "struct \fBresult_operation_t\fP"
.br
.ti -1c
.RI "struct \fBresult_operation_t< T, binop_e::add, N >\fP"
.br
.ti -1c
.RI "struct \fBresult_operation_t< T, binop_e::div, N >\fP"
.br
.ti -1c
.RI "struct \fBresult_operation_t< T, binop_e::fediv, N >\fP"
.br
.ti -1c
.RI "struct \fBresult_operation_t< T, binop_e::mult, N >\fP"
.br
.ti -1c
.RI "struct \fBresult_operation_t< T, binop_e::rem, N >\fP"
.br
.ti -1c
.RI "struct \fBresult_operation_t< T, binop_e::sub, N >\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
