.TH "NumRepr::type_traits::integral_c" 3 "Lunes, 28 de Noviembre de 2022" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::integral_c
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SH "Concept definition"
.PP 
.nf
template<typename INT_T>
concept NumRepr::type_traits::integral_c =  signed_integral_c<INT_T> || unsigned_integral_c<INT_T>
.fi
.SH "Descripción detallada"
.PP 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
