.TH "NumRepr::auxiliary_types::resbinop_t< T, binop_e::add >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::auxiliary_types::resbinop_t< T, binop_e::add >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <auxiliary_types\&.hpp>\fP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "T \fBcontent\fP"
.br
.ti -1c
.RI "T \fBcarry\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T>
.br
struct NumRepr::auxiliary_types::resbinop_t< T, binop_e::add >"
.PP
Definición en la línea \fB40\fP del archivo \fBauxiliary_types\&.hpp\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "template<typename T > T \fBNumRepr::auxiliary_types::resbinop_t\fP< T, \fBbinop_e::add\fP >::carry"

.PP
Definición en la línea \fB42\fP del archivo \fBauxiliary_types\&.hpp\fP\&.
.SS "template<typename T > T \fBNumRepr::auxiliary_types::resbinop_t\fP< T, \fBbinop_e::add\fP >::content"

.PP
Definición en la línea \fB41\fP del archivo \fBauxiliary_types\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
