.TH "NumRepr::type_traits::is_unsigned_sz_gt< T, S >" 3 "Lunes, 28 de Noviembre de 2022" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::is_unsigned_sz_gt< T, S >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "static constexpr bool \fBvalue\fP = ((sizeof(T)>sizeof(S))?true:false)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<unsigned_integral_c T, unsigned_integral_c S>
.br
struct NumRepr::type_traits::is_unsigned_sz_gt< T, S >"
.SH "Documentación de los datos miembro"
.PP 
.SS "template<unsigned_integral_c T, unsigned_integral_c S> constexpr bool \fBNumRepr::type_traits::is_unsigned_sz_gt\fP< T, S >::value = ((sizeof(T)>sizeof(S))?true:false)\fC [inline]\fP, \fC [static]\fP, \fC [constexpr]\fP"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
