.TH "NumRepr::type_traits::ugly_details_for_greater_suitable_type_deduction::UIntTypeForRadixContainsMultResult< T, Radix >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::ugly_details_for_greater_suitable_type_deduction::UIntTypeForRadixContainsMultResult< T, Radix >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "using \fBUIntType\fP = std::conditional_t< \fBuint_value\fP<=\fBuint_value_0_max\fP, \fBuchint_t\fP, std::conditional_t< \fBuint_value\fP<=\fBuint_value_1_max\fP, \fBusint_t\fP, std::conditional_t< \fBuint_value\fP<=\fBuint_value_2_max\fP, \fBuint_t\fP, std::conditional_t< \fBuint_value\fP<=\fBuint_value_3_max\fP, \fBulint_t\fP, std::conditional_t< \fBuint_value\fP<=\fBuint_value_4_max\fP, \fBullint_t\fP, \fBuint128_t\fP > > > > >"
.br
.in -1c
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "static constexpr \fBullint_t\fP \fBuint_value_0_max\fP = static_cast<\fBullint_t\fP>(\fBsqrt_max\fP<\fBuchint_t\fP>())"
.br
.ti -1c
.RI "static constexpr \fBullint_t\fP \fBuint_value_1_max\fP = static_cast<\fBullint_t\fP>(\fBsqrt_max\fP<\fBusint_t\fP>())"
.br
.ti -1c
.RI "static constexpr \fBullint_t\fP \fBuint_value_2_max\fP = static_cast<\fBullint_t\fP>(\fBsqrt_max\fP<\fBuint_t\fP>())"
.br
.ti -1c
.RI "static constexpr \fBullint_t\fP \fBuint_value_3_max\fP = static_cast<\fBullint_t\fP>(\fBsqrt_max\fP<\fBulint_t\fP>())"
.br
.ti -1c
.RI "static constexpr \fBullint_t\fP \fBuint_value_4_max\fP = static_cast<\fBullint_t\fP>(\fBsqrt_max\fP<\fBullint_t\fP>())"
.br
.ti -1c
.RI "static constexpr \fBullint_t\fP \fBuint_value\fP = static_cast<\fBullint_t\fP>(Radix)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<integral_c T, T Radix>
.br
requires (Radix > 1)
.br
struct NumRepr::type_traits::ugly_details_for_greater_suitable_type_deduction::UIntTypeForRadixContainsMultResult< T, Radix >"DEFINICION PARA ESPECIALIZACION TYPE_TRAITS::UINT_TYPE_FOR_RADIX_WITH_CONTAINS_MULT_RESULT FOR RADIX VALID 
.PP
Definición en la línea \fB634\fP del archivo \fBbasic_types\&.hpp\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<integral_c T, T Radix> using \fBNumRepr::type_traits::ugly_details_for_greater_suitable_type_deduction::UIntTypeForRadixContainsMultResult\fP< T, Radix >::UIntType =  std::conditional_t< \fBuint_value\fP <= \fBuint_value_0_max\fP, \fBuchint_t\fP, std::conditional_t< \fBuint_value\fP <= \fBuint_value_1_max\fP, \fBusint_t\fP, std::conditional_t< \fBuint_value\fP <= \fBuint_value_2_max\fP, \fBuint_t\fP, std::conditional_t< \fBuint_value\fP <= \fBuint_value_3_max\fP, \fBulint_t\fP, std::conditional_t< \fBuint_value\fP <= \fBuint_value_4_max\fP, \fBullint_t\fP, \fBuint128_t\fP > > > > >"

.PP
Definición en la línea \fB641\fP del archivo \fBbasic_types\&.hpp\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "template<integral_c T, T Radix> constexpr \fBullint_t\fP \fBNumRepr::type_traits::ugly_details_for_greater_suitable_type_deduction::UIntTypeForRadixContainsMultResult\fP< T, Radix >::uint_value = static_cast<\fBullint_t\fP>(Radix)\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB640\fP del archivo \fBbasic_types\&.hpp\fP\&.
.SS "template<integral_c T, T Radix> constexpr \fBullint_t\fP \fBNumRepr::type_traits::ugly_details_for_greater_suitable_type_deduction::UIntTypeForRadixContainsMultResult\fP< T, Radix >::uint_value_0_max = static_cast<\fBullint_t\fP>(\fBsqrt_max\fP<\fBuchint_t\fP>())\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB635\fP del archivo \fBbasic_types\&.hpp\fP\&.
.SS "template<integral_c T, T Radix> constexpr \fBullint_t\fP \fBNumRepr::type_traits::ugly_details_for_greater_suitable_type_deduction::UIntTypeForRadixContainsMultResult\fP< T, Radix >::uint_value_1_max = static_cast<\fBullint_t\fP>(\fBsqrt_max\fP<\fBusint_t\fP>())\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB636\fP del archivo \fBbasic_types\&.hpp\fP\&.
.SS "template<integral_c T, T Radix> constexpr \fBullint_t\fP \fBNumRepr::type_traits::ugly_details_for_greater_suitable_type_deduction::UIntTypeForRadixContainsMultResult\fP< T, Radix >::uint_value_2_max = static_cast<\fBullint_t\fP>(\fBsqrt_max\fP<\fBuint_t\fP>())\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB637\fP del archivo \fBbasic_types\&.hpp\fP\&.
.SS "template<integral_c T, T Radix> constexpr \fBullint_t\fP \fBNumRepr::type_traits::ugly_details_for_greater_suitable_type_deduction::UIntTypeForRadixContainsMultResult\fP< T, Radix >::uint_value_3_max = static_cast<\fBullint_t\fP>(\fBsqrt_max\fP<\fBulint_t\fP>())\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB638\fP del archivo \fBbasic_types\&.hpp\fP\&.
.SS "template<integral_c T, T Radix> constexpr \fBullint_t\fP \fBNumRepr::type_traits::ugly_details_for_greater_suitable_type_deduction::UIntTypeForRadixContainsMultResult\fP< T, Radix >::uint_value_4_max = static_cast<\fBullint_t\fP>(\fBsqrt_max\fP<\fBullint_t\fP>())\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB639\fP del archivo \fBbasic_types\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
