.TH "NumRepr::auxiliary_types::resbinop_t< T, oper >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::auxiliary_types::resbinop_t< T, oper > \- auxiliary types for digit type and its operations  

.SH SYNOPSIS
.br
.PP
.SH "Descripción detallada"
.PP 

.SS "template<typename T, \fBbinop_e\fP oper>
.br
struct NumRepr::auxiliary_types::resbinop_t< T, oper >"auxiliary types for digit type and its operations 
.PP
Definición en la línea \fB37\fP del archivo \fBauxiliary_types\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
