.TH "NumRepr::arith_integral_c" 3 "Lunes, 28 de Noviembre de 2022" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::arith_integral_c \- TYPE_TRAITS AND CONCEPTS\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SH "Concept definition"
.PP 
.nf
template<typename IntT>
concept NumRepr::arith_integral_c =     std::is_arithmetic_v<IntT>      &&
                            std::is_integral_v<IntT>
.fi
.SH "Descripción detallada"
.PP 
TYPE_TRAITS AND CONCEPTS\&. 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
