.TH "NumRepr::type_traits::ugly_details_for_greater_suitable_type_deduction::UIntTypeForRadixContainsMultResult< T, Radix >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::ugly_details_for_greater_suitable_type_deduction::UIntTypeForRadixContainsMultResult< T, Radix >
.SH SYNOPSIS
.br
.PP
.SH "Descripción detallada"
.PP 

.SS "template<typename T, T Radix>
.br
struct NumRepr::type_traits::ugly_details_for_greater_suitable_type_deduction::UIntTypeForRadixContainsMultResult< T, Radix >"
.PP
Definición en la línea \fB629\fP del archivo \fBbasic_types\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
