.TH "NumRepr::type_traits::ugly_details_sig_SInt_for_UInt::__sig_SInt_for_UInt_t< UInt >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::ugly_details_sig_SInt_for_UInt::__sig_SInt_for_UInt_t< UInt >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "using \fBtype\fP = void"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename UInt>
.br
struct NumRepr::type_traits::ugly_details_sig_SInt_for_UInt::__sig_SInt_for_UInt_t< UInt >"
.PP
Definición en la línea \fB295\fP del archivo \fBbasic_types\&.hpp\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<typename UInt > using \fBNumRepr::type_traits::ugly_details_sig_SInt_for_UInt::__sig_SInt_for_UInt_t\fP< UInt >::type =  void"

.PP
Definición en la línea \fB296\fP del archivo \fBbasic_types\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
