.TH "NumRepr::type_traits::unsigned_integral_c" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::unsigned_integral_c \- CONCEPT FOR UNSIGNED INTEGRAL TYPES\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SH "Concept definition"
.PP 
.PP
.nf
template<typename UINT_T>
concept NumRepr::type_traits::unsigned_integral_c =  is_unsigned_type_v<UINT_T>
.fi
.SH "Descripción detallada"
.PP 
CONCEPT FOR UNSIGNED INTEGRAL TYPES\&. 
.PP
Definición en la línea \fB188\fP del archivo \fBbasic_types\&.hpp\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
