.TH "NumRepr::type_traits::ugly_details_sig_SInt_for_UInt::__sig_SInt_for_UInt_t< ullint_t >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::ugly_details_sig_SInt_for_UInt::__sig_SInt_for_UInt_t< ullint_t >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "using \fBtype\fP = \fBsint128_t\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB299\fP del archivo \fBbasic_types\&.hpp\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "using \fBNumRepr::type_traits::ugly_details_sig_SInt_for_UInt::__sig_SInt_for_UInt_t\fP< \fBullint_t\fP >::type =  \fBsint128_t\fP"

.PP
Definición en la línea \fB300\fP del archivo \fBbasic_types\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
