.TH "NumRepr::auxiliary_types::resbinop_t< T, binop_e::mult >" 3 "Lunes, 28 de Noviembre de 2022" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::auxiliary_types::resbinop_t< T, binop_e::mult >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <auxiliary_types\&.hpp>\fP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "T \fBlow_content\fP"
.br
.ti -1c
.RI "T \fBhigh_content\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T>
.br
struct NumRepr::auxiliary_types::resbinop_t< T, binop_e::mult >"
.SH "Documentación de los datos miembro"
.PP 
.SS "template<typename T > T \fBNumRepr::auxiliary_types::resbinop_t\fP< T, \fBbinop_e::mult\fP >::high_content"

.SS "template<typename T > T \fBNumRepr::auxiliary_types::resbinop_t\fP< T, \fBbinop_e::mult\fP >::low_content"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
