.TH "NumRepr::detail" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::detail
.SH SYNOPSIS
.br
.PP
.SS "Funciones"

.in +1c
.ti -1c
.RI "constexpr \fBsize_t\fP \fBceilsqrt\fP (\fBsize_t\fP n, \fBsize_t\fP low, \fBsize_t\fP high) noexcept"
.br
.ti -1c
.RI "constexpr \fBsize_t\fP \fBceilsqrt\fP (\fBsize_t\fP n) noexcept"
.br
.ti -1c
.RI "constexpr bool \fBfind_factor\fP (\fBsize_t\fP n, \fBsize_t\fP low, \fBsize_t\fP high) noexcept"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "constexpr \fBsize_t\fP NumRepr::detail::ceilsqrt (\fBsize_t\fP n)\fC [inline]\fP, \fC [constexpr]\fP, \fC [noexcept]\fP"

.PP
Definición en la línea \fB70\fP del archivo \fBauxiliary_functions\&.hpp\fP\&.
.SS "constexpr \fBsize_t\fP NumRepr::detail::ceilsqrt (\fBsize_t\fP n, \fBsize_t\fP low, \fBsize_t\fP high)\fC [inline]\fP, \fC [constexpr]\fP, \fC [noexcept]\fP"

.PP
Definición en la línea \fB52\fP del archivo \fBauxiliary_functions\&.hpp\fP\&.
.SS "constexpr bool NumRepr::detail::find_factor (\fBsize_t\fP n, \fBsize_t\fP low, \fBsize_t\fP high)\fC [inline]\fP, \fC [constexpr]\fP, \fC [noexcept]\fP"

.PP
Definición en la línea \fB88\fP del archivo \fBauxiliary_functions\&.hpp\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
