.TH "NumRepr::type_traits::allowable_signed_type_c" 3 "Lunes, 28 de Noviembre de 2022" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::allowable_signed_type_c
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SH "Concept definition"
.PP 
.nf
template<typename SINT_T>
concept NumRepr::type_traits::allowable_signed_type_c =        
                        std::is_same_v<SINT_T,sint8_t>       ||
                        std::is_same_v<SINT_T,sint16_t>     ||
                        std::is_same_v<SINT_T,sint32_t>     ||
                        std::is_same_v<SINT_T,sint64_t>     ||
                        std::is_same_v<SINT_T,schint>           ||
                        std::is_same_v<SINT_T,chint>            ||
                        std::is_same_v<SINT_T,ssint>            ||
                        std::is_same_v<SINT_T,sint>                     ||
                        std::is_same_v<SINT_T,slint>            ||
                        std::is_same_v<SINT_T,sllint>           ||
                        std::is_same_v<SINT_T,sint128_t>        
.fi
.SH "Descripción detallada"
.PP 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
