.TH "NumRepr::auxiliary_types::resbinop_t< T, oper >" 3 "Lunes, 28 de Noviembre de 2022" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::auxiliary_types::resbinop_t< T, oper > \- auxiliary types for digit type and its operations  

.SH SYNOPSIS
.br
.PP
.SH "Descripción detallada"
.PP 

.SS "template<typename T, \fBbinop_e\fP oper>
.br
struct NumRepr::auxiliary_types::resbinop_t< T, oper >"auxiliary types for digit type and its operations 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
