.TH "NumRepr::auxiliary_functions" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::auxiliary_functions
.SH SYNOPSIS
.br
.PP
.SS "Funciones"

.in +1c
.ti -1c
.RI "constexpr bool \fBis_prime\fP (\fBsize_t\fP n) noexcept"
.br
.ti -1c
.RI "constexpr bool \fBis_power_of_2\fP (\fBuint128_t\fP num) noexcept"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "constexpr bool NumRepr::auxiliary_functions::is_power_of_2 (\fBuint128_t\fP num)\fC [inline]\fP, \fC [constexpr]\fP, \fC [noexcept]\fP"

.PP
Definición en la línea \fB115\fP del archivo \fBauxiliary_functions\&.hpp\fP\&.
.SS "constexpr bool NumRepr::auxiliary_functions::is_prime (\fBsize_t\fP n)\fC [inline]\fP, \fC [constexpr]\fP, \fC [noexcept]\fP"

.PP
Definición en la línea \fB105\fP del archivo \fBauxiliary_functions\&.hpp\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
