.TH "NumRepr::type_traits::ugly_details_UInt_for_SInt::__sig_UInt_for_SInt_t< SInt >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::ugly_details_UInt_for_SInt::__sig_UInt_for_SInt_t< SInt >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "using \fBtype\fP = void"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename SInt>
.br
struct NumRepr::type_traits::ugly_details_UInt_for_SInt::__sig_UInt_for_SInt_t< SInt >"
.PP
Definición en la línea \fB370\fP del archivo \fBbasic_types\&.hpp\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<typename SInt > using \fBNumRepr::type_traits::ugly_details_UInt_for_SInt::__sig_UInt_for_SInt_t\fP< SInt >::type =  void"

.PP
Definición en la línea \fB371\fP del archivo \fBbasic_types\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
