.TH "NumRepr::type_traits::ugly_details_for_suitable_type_deduction" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::ugly_details_for_suitable_type_deduction
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBUIntTypeForRadix\fP"
.br
.ti -1c
.RI "struct \fBUIntTypeForRadix< T, Radix >\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
