.TH "NumRepr::auxiliary_types::resbinop_t< T, binop_e::rem >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::auxiliary_types::resbinop_t< T, binop_e::rem >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <auxiliary_types\&.hpp>\fP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "T \fBremainder\fP"
.br
.ti -1c
.RI "bool \fBno_div_by_0\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T>
.br
struct NumRepr::auxiliary_types::resbinop_t< T, binop_e::rem >"
.PP
Definición en la línea \fB71\fP del archivo \fBauxiliary_types\&.hpp\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "template<typename T > bool \fBNumRepr::auxiliary_types::resbinop_t\fP< T, \fBbinop_e::rem\fP >::no_div_by_0"

.PP
Definición en la línea \fB73\fP del archivo \fBauxiliary_types\&.hpp\fP\&.
.SS "template<typename T > T \fBNumRepr::auxiliary_types::resbinop_t\fP< T, \fBbinop_e::rem\fP >::remainder"

.PP
Definición en la línea \fB72\fP del archivo \fBauxiliary_types\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
