.TH "pruebas_dig_t.cpp" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pruebas_dig_t.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'utilities\&.hpp'\fP
.br
\fC#include 'nat_reg_digs_t\&.hpp'\fP
.br
\fC#include <typeinfo>\fP
.br

.SS "typedefs"

.in +1c
.ti -1c
.RI "using \fBtrisums_t\fP = std::tuple< std::int64_t, std::int64_t, std::int64_t >"
.br
.ti -1c
.RI "using \fBresult_test_binop_con_asignacion\fP = std::vector< \fBtrisums_t\fP >"
.br
.ti -1c
.RI "using \fBretorno_de_test_t\fP = std::tuple< bool, \fBresult_test_binop_con_asignacion\fP, \fBresult_test_binop_con_asignacion\fP >"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "template<size_t B, size_t L> constexpr \fBNumRepr::uint128_t\fP \fBconversion_to_int\fP (\fBNumRepr::register_of_digits_t\fP< B, L > &arg) noexcept"
.br
.ti -1c
.RI "template<\fBNumRepr::ullint_t\fP Base, \fBNumRepr::ullint_t\fP Longitud> \fBretorno_de_test_t\fP \fBtest_suma_con_asignacion\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Documentación de los 'typedefs'"
.PP 
.SS "using \fBresult_test_binop_con_asignacion\fP =  std::vector<\fBtrisums_t\fP>"

.PP
Definición en la línea \fB29\fP del archivo \fBpruebas_dig_t\&.cpp\fP\&.
.SS "using \fBretorno_de_test_t\fP =  std::tuple< bool, \fBresult_test_binop_con_asignacion\fP, \fBresult_test_binop_con_asignacion\fP>"

.PP
Definición en la línea \fB31\fP del archivo \fBpruebas_dig_t\&.cpp\fP\&.
.SS "using \fBtrisums_t\fP =  std::tuple<std::int64_t,std::int64_t,std::int64_t>"

.PP
Definición en la línea \fB27\fP del archivo \fBpruebas_dig_t\&.cpp\fP\&.
.SH "Documentación de las funciones"
.PP 
.SS "template<size_t B, size_t L> constexpr \fBNumRepr::uint128_t\fP conversion_to_int (\fBNumRepr::register_of_digits_t\fP< B, L > & arg)\fC [inline]\fP, \fC [constexpr]\fP, \fC [noexcept]\fP"

.PP
Definición en la línea \fB21\fP del archivo \fBpruebas_dig_t\&.cpp\fP\&.
.SS "int main ()"
digit_t\fB reg_digs_t<B,L>\fP
.PP
\fBPRUEBAS SOBRE LA DIVISION FUNCION AUXILIAR aprox_units_divB\fP
.PP
\fB\fP
.PP
Definición en la línea \fB78\fP del archivo \fBpruebas_dig_t\&.cpp\fP\&.
.SS "template<\fBNumRepr::ullint_t\fP Base, \fBNumRepr::ullint_t\fP Longitud> \fBretorno_de_test_t\fP test_suma_con_asignacion ()"

.PP
Definición en la línea \fB36\fP del archivo \fBpruebas_dig_t\&.cpp\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
