.TH "utilities::special::tuple_builder_t< BeginIntObj_ct, BeginIntObj_ct, EndIntObj_ct, Base, Funct_tt >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utilities::special::tuple_builder_t< BeginIntObj_ct, BeginIntObj_ct, EndIntObj_ct, Base, Funct_tt > \- ESPECIALIZACION DONDE INTOBJ_CT == BEGININTOBJ_CT\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utilities\&.hpp>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "using \fBtype\fP = std::int64_t"
.br
.in -1c
.SS "Métodos públicos estáticos"

.in +1c
.ti -1c
.RI "static consteval decltype(auto) \fBbuild\fP () noexcept"
.br
.in -1c
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "static constexpr \fBtype\fP \fBunit\fP = 1"
.br
.ti -1c
.RI "static constexpr \fBtype\fP \fBvalue\fP {BeginIntObj_ct}"
.br
.ti -1c
.RI "static constexpr \fBtype\fP \fBbegin_value\fP {BeginIntObj_ct}"
.br
.ti -1c
.RI "static constexpr \fBtype\fP \fBend_value\fP {EndIntObj_ct}"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<std::int64_t BeginIntObj_ct, std::int64_t EndIntObj_ct, std::int64_t Base, template< std::int64_t, std::int64_t > class Funct_tt>
.br
requires (BeginIntObj_ct <= EndIntObj_ct)
.br
struct utilities::special::tuple_builder_t< BeginIntObj_ct, BeginIntObj_ct, EndIntObj_ct, Base, Funct_tt >"ESPECIALIZACION DONDE INTOBJ_CT == BEGININTOBJ_CT\&. 
.PP
Definición en la línea \fB287\fP del archivo \fButilities\&.hpp\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<std::int64_t BeginIntObj_ct, std::int64_t EndIntObj_ct, std::int64_t Base, template< std::int64_t, std::int64_t > class Funct_tt> using \fButilities::special::tuple_builder_t\fP< BeginIntObj_ct, BeginIntObj_ct, EndIntObj_ct, Base, Funct_tt >::type =  std::int64_t"

.PP
Definición en la línea \fB289\fP del archivo \fButilities\&.hpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<std::int64_t BeginIntObj_ct, std::int64_t EndIntObj_ct, std::int64_t Base, template< std::int64_t, std::int64_t > class Funct_tt> static consteval decltype(auto) \fButilities::special::tuple_builder_t\fP< BeginIntObj_ct, BeginIntObj_ct, EndIntObj_ct, Base, Funct_tt >::build ()\fC [inline]\fP, \fC [static]\fP, \fC [noexcept]\fP"

.PP
Definición en la línea \fB298\fP del archivo \fButilities\&.hpp\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "template<std::int64_t BeginIntObj_ct, std::int64_t EndIntObj_ct, std::int64_t Base, template< std::int64_t, std::int64_t > class Funct_tt> constexpr \fBtype\fP \fButilities::special::tuple_builder_t\fP< BeginIntObj_ct, BeginIntObj_ct, EndIntObj_ct, Base, Funct_tt >::begin_value {BeginIntObj_ct}\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB294\fP del archivo \fButilities\&.hpp\fP\&.
.SS "template<std::int64_t BeginIntObj_ct, std::int64_t EndIntObj_ct, std::int64_t Base, template< std::int64_t, std::int64_t > class Funct_tt> constexpr \fBtype\fP \fButilities::special::tuple_builder_t\fP< BeginIntObj_ct, BeginIntObj_ct, EndIntObj_ct, Base, Funct_tt >::end_value {EndIntObj_ct}\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB295\fP del archivo \fButilities\&.hpp\fP\&.
.SS "template<std::int64_t BeginIntObj_ct, std::int64_t EndIntObj_ct, std::int64_t Base, template< std::int64_t, std::int64_t > class Funct_tt> constexpr \fBtype\fP \fButilities::special::tuple_builder_t\fP< BeginIntObj_ct, BeginIntObj_ct, EndIntObj_ct, Base, Funct_tt >::unit = 1\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB291\fP del archivo \fButilities\&.hpp\fP\&.
.SS "template<std::int64_t BeginIntObj_ct, std::int64_t EndIntObj_ct, std::int64_t Base, template< std::int64_t, std::int64_t > class Funct_tt> constexpr \fBtype\fP \fButilities::special::tuple_builder_t\fP< BeginIntObj_ct, BeginIntObj_ct, EndIntObj_ct, Base, Funct_tt >::value {BeginIntObj_ct}\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB293\fP del archivo \fButilities\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
