.TH "utilities::for_each_same_type< Head_t >" 3 "Lunes, 28 de Noviembre de 2022" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utilities::for_each_same_type< Head_t >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utilities\&.hpp>\fP
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "static constexpr bool \fBare_same_type_v\fP = true"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<class Head_t>
.br
struct utilities::for_each_same_type< Head_t >"
.SH "Documentación de los datos miembro"
.PP 
.SS "template<class Head_t > constexpr bool \fButilities::for_each_same_type\fP< Head_t >::are_same_type_v = true\fC [static]\fP, \fC [constexpr]\fP"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
