.TH "utilities::special::pow_B_to_E_t< Base, Exp >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utilities::special::pow_B_to_E_t< Base, Exp > \- FORMA ANTIGUA PERO SEGURA DE CONSEGUIR POTENCIAS DE UNA BASE EN COMPILE TIME\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utilities\&.hpp>\fP
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "static constexpr \fBNumRepr::uint128_t\fP \fBbase\fP = static_cast<\fBNumRepr::uint128_t\fP>(Base)"
.br
.ti -1c
.RI "static constexpr \fBNumRepr::uint128_t\fP \fBexponent\fP = static_cast<\fBNumRepr::uint128_t\fP>(Exp)"
.br
.ti -1c
.RI "static constexpr \fBNumRepr::uint128_t\fP \fBvalue\fP = \fBbase\fP*(\fBpow_B_to_E_t\fP<\fBbase\fP,\fBexponent\fP\-1>::value)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<\fBNumRepr::usint_t\fP Base, \fBNumRepr::usint_t\fP Exp>
.br
struct utilities::special::pow_B_to_E_t< Base, Exp >"FORMA ANTIGUA PERO SEGURA DE CONSEGUIR POTENCIAS DE UNA BASE EN COMPILE TIME\&. 
.PP
Definición en la línea \fB193\fP del archivo \fButilities\&.hpp\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "template<\fBNumRepr::usint_t\fP Base, \fBNumRepr::usint_t\fP Exp> constexpr \fBNumRepr::uint128_t\fP \fButilities::special::pow_B_to_E_t\fP< Base, Exp >::base = static_cast<\fBNumRepr::uint128_t\fP>(Base)\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB194\fP del archivo \fButilities\&.hpp\fP\&.
.SS "template<\fBNumRepr::usint_t\fP Base, \fBNumRepr::usint_t\fP Exp> constexpr \fBNumRepr::uint128_t\fP \fButilities::special::pow_B_to_E_t\fP< Base, Exp >::exponent = static_cast<\fBNumRepr::uint128_t\fP>(Exp)\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB195\fP del archivo \fButilities\&.hpp\fP\&.
.SS "template<\fBNumRepr::usint_t\fP Base, \fBNumRepr::usint_t\fP Exp> constexpr \fBNumRepr::uint128_t\fP \fButilities::special::pow_B_to_E_t\fP< Base, Exp >::value = \fBbase\fP*(\fBpow_B_to_E_t\fP<\fBbase\fP,\fBexponent\fP\-1>::value)\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB196\fP del archivo \fButilities\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
