.TH "utilities::all_are_the_same_type_c" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utilities::all_are_the_same_type_c
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utilities\&.hpp>\fP
.SH "Concept definition"
.PP 
.PP
.nf
template<typename\&.\&.\&. Ts>
concept utilities::all_are_the_same_type_c =  requires(Ts\&.\&.\&.) {
        for_each_same_type<Ts\&.\&.\&.>::are_same_type_v;
}
.fi
.SH "Descripción detallada"
.PP 
Definición en la línea \fB92\fP del archivo \fButilities\&.hpp\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
