.TH "utilities::special::pow_B_to_E_t< Base, 2 >" 3 "Lunes, 2 de Enero de 2023" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utilities::special::pow_B_to_E_t< Base, 2 >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utilities\&.hpp>\fP
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "static constexpr \fBNumRepr::uint128_t\fP \fBbase\fP = static_cast<\fBNumRepr::uint128_t\fP>(Base)"
.br
.ti -1c
.RI "static constexpr \fBNumRepr::uint128_t\fP \fBexponent\fP = static_cast<\fBNumRepr::uint128_t\fP>(2)"
.br
.ti -1c
.RI "static constexpr \fBNumRepr::uint128_t\fP \fBvalue\fP = \fBbase\fP*\fBbase\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<\fBNumRepr::usint_t\fP Base>
.br
struct utilities::special::pow_B_to_E_t< Base, 2 >"
.PP
Definición en la línea \fB199\fP del archivo \fButilities\&.hpp\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "template<\fBNumRepr::usint_t\fP Base> constexpr \fBNumRepr::uint128_t\fP \fButilities::special::pow_B_to_E_t\fP< Base, 2 >::base = static_cast<\fBNumRepr::uint128_t\fP>(Base)\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB200\fP del archivo \fButilities\&.hpp\fP\&.
.SS "template<\fBNumRepr::usint_t\fP Base> constexpr \fBNumRepr::uint128_t\fP \fButilities::special::pow_B_to_E_t\fP< Base, 2 >::exponent = static_cast<\fBNumRepr::uint128_t\fP>(2)\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB201\fP del archivo \fButilities\&.hpp\fP\&.
.SS "template<\fBNumRepr::usint_t\fP Base> constexpr \fBNumRepr::uint128_t\fP \fButilities::special::pow_B_to_E_t\fP< Base, 2 >::value = \fBbase\fP*\fBbase\fP\fC [static]\fP, \fC [constexpr]\fP"

.PP
Definición en la línea \fB202\fP del archivo \fButilities\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
