.TH "auxiliary_types.hpp" 3 "Martes, 29 de Noviembre de 2022" "Version 0.8" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
auxiliary_types.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'basic_types\&.hpp'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBNumRepr::auxiliary_types::resbinop_t< T, binop_e::add >\fP"
.br
.ti -1c
.RI "struct \fBNumRepr::auxiliary_types::resbinop_t< T, binop_e::sub >\fP"
.br
.ti -1c
.RI "struct \fBNumRepr::auxiliary_types::resbinop_t< T, binop_e::mult >\fP"
.br
.ti -1c
.RI "struct \fBNumRepr::auxiliary_types::resbinop_t< T, binop_e::fediv >\fP"
.br
.ti -1c
.RI "struct \fBNumRepr::auxiliary_types::resbinop_t< T, binop_e::div >\fP"
.br
.ti -1c
.RI "struct \fBNumRepr::auxiliary_types::resbinop_t< T, binop_e::rem >\fP"
.br
.ti -1c
.RI "struct \fBNumRepr::auxiliary_types::result_operation_t< T, binop_e::add, N >\fP"
.br
.ti -1c
.RI "struct \fBNumRepr::auxiliary_types::result_operation_t< T, binop_e::sub, N >\fP"
.br
.ti -1c
.RI "struct \fBNumRepr::auxiliary_types::result_operation_t< T, binop_e::mult, N >\fP"
.br
.ti -1c
.RI "struct \fBNumRepr::auxiliary_types::result_operation_t< T, binop_e::fediv, N >\fP"
.br
.ti -1c
.RI "struct \fBNumRepr::auxiliary_types::result_operation_t< T, binop_e::div, N >\fP"
.br
.ti -1c
.RI "struct \fBNumRepr::auxiliary_types::result_operation_t< T, binop_e::rem, N >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBNumRepr\fP"
.br
.ti -1c
.RI "namespace \fBNumRepr::auxiliary_types\fP"
.br
.in -1c
.SS "Enumeraciones"

.in +1c
.ti -1c
.RI "enum class \fBNumRepr::sign_e\fP : bool { \fBNumRepr::vminus\fP = true, \fBNumRepr::vplus\fP = false }"
.br
.ti -1c
.RI "enum class \fBNumRepr::sign_funct_e\fP : char { \fBNumRepr::vzero\fP = 0, \fBNumRepr::vminus\fP = -1, \fBNumRepr::vplus\fP = +1 }"
.br
.RI "INTRODUCIDO\&. "
.ti -1c
.RI "enum class \fBNumRepr::dig_format_e\fP : unsigned char { \fBNumRepr::BINnat\fP =0, \fBNumRepr::BCDnat\fP =1, \fBNumRepr::BCDexc3\fP =2, \fBNumRepr::BCDaitk\fP =3, \fBNumRepr::johnson_n\fP =4, \fBNumRepr::biquinario\fP =5 }"
.br
.ti -1c
.RI "enum class \fBNumRepr::num_type_e\fP : unsigned char { \fBNumRepr::natural\fP =0, \fBNumRepr::entero\fP =1, \fBNumRepr::racional\fP =2, \fBNumRepr::real\fP =3 }"
.br
.RI "A INTRODUCIR\&. "
.ti -1c
.RI "enum class \fBNumRepr::nat_num_format_e\fP : bool { \fBNumRepr::natural\fP =false, \fBNumRepr::exc_n\fP =true }"
.br
.RI "YA INTRODUCIDO, PERO NO EXPLICITAMENTE NI COMPLETAMENTE\&. "
.ti -1c
.RI "enum class \fBNumRepr::int_num_format_e\fP : unsigned char { \fBNumRepr::int_CB\fP =0, \fBNumRepr::int_CBm1\fP =1, \fBNumRepr::int_MS\fP =2, \fBNumRepr::int_EXC_n\fP =3 }"
.br
.RI "SOLO NATURAL\&. "
.ti -1c
.RI "enum class \fBNumRepr::rat_num_format_e\fP : unsigned char { \fBNumRepr::pair_num_den\fP =0, \fBNumRepr::fxd_pt\fP =1, \fBNumRepr::flt_pt\fP =2 }"
.br
.RI "EN C_B YA QUEDA EN MS\&. "
.ti -1c
.RI "enum class \fBNumRepr::binop_e\fP { \fBNumRepr::add\fP, \fBNumRepr::sub\fP, \fBNumRepr::mult\fP, \fBNumRepr::div\fP, \fBNumRepr::rem\fP, \fBNumRepr::fediv\fP, \fBNumRepr::other\fP }"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
