.TH "Referencia del directorio src" 3 "Martes, 29 de Noviembre de 2022" "Version 0.8" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio src
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBauxiliary_functions\&.hpp\fP"
.br
.ti -1c
.RI "archivo \fBauxiliary_types\&.hpp\fP"
.br
.ti -1c
.RI "archivo \fBbase_num_t\&.hpp\fP"
.br
.ti -1c
.RI "archivo \fBbasic_types\&.hpp\fP"
.br
.ti -1c
.RI "archivo \fBdig_t\&.hpp\fP"
.br
.ti -1c
.RI "archivo \fBint_num_t\&.hpp\fP"
.br
.ti -1c
.RI "archivo \fBint_reg_digs_t\&.hpp\fP"
.br
.ti -1c
.RI "archivo \fBmemory_handler\&.hpp\fP"
.br
.ti -1c
.RI "archivo \fBnat_num_t\&.hpp\fP"
.br
.ti -1c
.RI "archivo \fBnat_rat_fixed_reg_t\&.hpp\fP"
.br
.ti -1c
.RI "archivo \fBnat_reg_digs_t (Copia en conflicto de MSI 2022\-11\-24)\&.hpp\fP"
.br
.ti -1c
.RI "archivo \fBnat_reg_digs_t\&.hpp\fP"
.br
.ti -1c
.RI "archivo \fBpruebas_dig_t\&.cpp\fP"
.br
.ti -1c
.RI "archivo \fBrat_fixed_reg_t\&.hpp\fP"
.br
.ti -1c
.RI "archivo \fBreg_digs_t\&.hpp\fP"
.br
.ti -1c
.RI "archivo \fBtest_dig_t\&.hpp\fP"
.br
.ti -1c
.RI "archivo \fButilities\&.hpp\fP"
.br
.in -1c
