.TH "details::cp_new< aT, T, std::numeric_limits< uchint >::max()>" 3 "Martes, 29 de Noviembre de 2022" "Version 0.8" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
details::cp_new< aT, T, std::numeric_limits< uchint >::max()>
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memory_handler\&.hpp>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (aT **var_list_list)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename aT, template< \fBuchint\fP > class T, \fBusint\fP num_vars>
.br
struct details::cp_new< aT, T, std::numeric_limits< uchint >::max()>"
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename aT , template< \fBuchint\fP > class T, \fBusint\fP num_vars> void \fBdetails::cp_new\fP< aT, T, std::numeric_limits< \fBuchint\fP >::max()>::operator() (aT ** var_list_list)\fC [inline]\fP"

.PP
.nf
40                                             {
41                         construye_lista_de_lista_de_variables(var_list_listlist_list);
42                         static_cast<T<std::numeric_limits<uchint>::max()>*>(contruye_lista_de_variables(var_list_list[std::numeric_limits<uchint>::max()]));
43                         cp_new<aT,T,num_vars,std::numeric_limits<uchint>::max()-1>(var_list_list);
44         }
.fi


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
