.TH "details::cp_delete< 2u >" 3 "Martes, 29 de Noviembre de 2022" "Version 0.8" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
details::cp_delete< 2u >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memory_handler\&.hpp>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (aT **var_list_list)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename aT, template< \fBuchint\fP > class T>
.br
struct details::cp_delete< 2u >"
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename aT , template< \fBuchint\fP > class T> void \fBdetails::cp_delete\fP< 2u >::operator() (aT ** var_list_list)\fC [inline]\fP"

.PP
.nf
109                                             {
110                         static_cast<T<2u>*>(contruye_lista_de_variables(var_list_list[2u]));
111                         cp_delete<aT,T,1>(var_list_list);
112         }
.fi


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
