.TH "NumRepr::type_traits::detail::__sig_SInt_for_SInt_t< signed char >" 3 "Martes, 29 de Noviembre de 2022" "Version 0.8" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::detail::__sig_SInt_for_SInt_t< signed char >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "using \fBtype\fP = signed short int"
.br
.in -1c
.SH "Descripción detallada"
.PP 
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "using \fBNumRepr::type_traits::detail::__sig_SInt_for_SInt_t\fP< signed char >::type =  signed short int"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
