.TH "NumRepr::type_traits::detail" 3 "Martes, 29 de Noviembre de 2022" "Version 0.8" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::detail
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fB__sig_SInt_for_SInt_t\fP"
.br
.ti -1c
.RI "struct \fB__sig_SInt_for_SInt_t< char >\fP"
.br
.ti -1c
.RI "struct \fB__sig_SInt_for_SInt_t< signed char >\fP"
.br
.ti -1c
.RI "struct \fB__sig_SInt_for_SInt_t< signed int >\fP"
.br
.ti -1c
.RI "struct \fB__sig_SInt_for_SInt_t< signed long int >\fP"
.br
.ti -1c
.RI "struct \fB__sig_SInt_for_SInt_t< signed long long int >\fP"
.br
.ti -1c
.RI "struct \fB__sig_SInt_for_SInt_t< signed short int >\fP"
.br
.ti -1c
.RI "struct \fB__sig_SInt_for_UInt_t\fP"
.br
.ti -1c
.RI "struct \fB__sig_SInt_for_UInt_t< unsigned char >\fP"
.br
.ti -1c
.RI "struct \fB__sig_SInt_for_UInt_t< unsigned int >\fP"
.br
.ti -1c
.RI "struct \fB__sig_SInt_for_UInt_t< unsigned long int >\fP"
.br
.ti -1c
.RI "struct \fB__sig_SInt_for_UInt_t< unsigned long long int >\fP"
.br
.ti -1c
.RI "struct \fB__sig_SInt_for_UInt_t< unsigned short int >\fP"
.br
.ti -1c
.RI "struct \fB__sig_UInt_for_SInt_t\fP"
.br
.ti -1c
.RI "struct \fB__sig_UInt_for_SInt_t< char >\fP"
.br
.ti -1c
.RI "struct \fB__sig_UInt_for_SInt_t< signed char >\fP"
.br
.ti -1c
.RI "struct \fB__sig_UInt_for_SInt_t< signed int >\fP"
.br
.ti -1c
.RI "struct \fB__sig_UInt_for_SInt_t< signed long int >\fP"
.br
.ti -1c
.RI "struct \fB__sig_UInt_for_SInt_t< signed long long int >\fP"
.br
.ti -1c
.RI "struct \fB__sig_UInt_for_SInt_t< signed short int >\fP"
.br
.ti -1c
.RI "struct \fB__sig_UInt_for_SInt_t< sint128_t >\fP"
.br
.ti -1c
.RI "struct \fB__sig_UInt_for_UInt_t\fP"
.br
.ti -1c
.RI "struct \fB__sig_UInt_for_UInt_t< unsigned char >\fP"
.br
.ti -1c
.RI "struct \fB__sig_UInt_for_UInt_t< unsigned int >\fP"
.br
.ti -1c
.RI "struct \fB__sig_UInt_for_UInt_t< unsigned long int >\fP"
.br
.ti -1c
.RI "struct \fB__sig_UInt_for_UInt_t< unsigned long long int >\fP"
.br
.ti -1c
.RI "struct \fB__sig_UInt_for_UInt_t< unsigned short int >\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
sig_UInt_for_UInt_t<unsigned char> devuelve el tipo unsigned short; sig_UInt_for_UInt_t<unsigned short> devuelve el tipo unsigned long; sig_UInt_for_UInt_t<unsigned long> devuelve el tipo unsigned long long; sig_UInt_for_UInt_t<unsigned long long> devuelve el tipo uint128_t; sig_UInt_for_UInt_t<uint128_t> devuelve el tipo void; < METAFUNCION : DA EL SIGUIENTE TIPO ENTERO PARA EL ACTUAL TIPO NATURAL POR ESPECIALIZACION EXPLICITA
.PP
sig_SInt_for_UInt_t<unsigned char> devuelve el tipo short; sig_SInt_for_UInt_t<unsigned short> devuelve el tipo long; sig_SInt_for_UInt_t<unsigned long> devuelve el tipo long long; sig_SInt_for_UInt_t<unsigned long long> devuelve el tipo int128_t; sig_SInt_for_UInt_t<uint128_t> devuelve el tipo void; < METAFUNCION : DA EL SIGUIENTE TIPO NATURAL PARA EL ACTUAL TIPO ENTERO POR ESPCEIALIZACION EXPLICITA 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
