.TH "NumRepr::type_traits::detail::__sig_UInt_for_UInt_t< unsigned short int >" 3 "Martes, 29 de Noviembre de 2022" "Version 0.8" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::type_traits::detail::__sig_UInt_for_UInt_t< unsigned short int >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "using \fBtype\fP = unsigned long int"
.br
.in -1c
.SH "Descripción detallada"
.PP 
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "using \fBNumRepr::type_traits::detail::__sig_UInt_for_UInt_t\fP< unsigned short int >::type =  unsigned long int"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
