.TH "NumRepr::auxiliary_types::resbinop_t< T, binop_e::fediv >" 3 "Martes, 29 de Noviembre de 2022" "Version 0.8" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::auxiliary_types::resbinop_t< T, binop_e::fediv >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <auxiliary_types\&.hpp>\fP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "T \fBquotient\fP"
.br
.ti -1c
.RI "T \fBremainder\fP"
.br
.ti -1c
.RI "bool \fBno_div_by_0\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T>
.br
struct NumRepr::auxiliary_types::resbinop_t< T, binop_e::fediv >"
.SH "Documentación de los datos miembro"
.PP 
.SS "template<typename T > bool \fBNumRepr::auxiliary_types::resbinop_t\fP< T, \fBbinop_e::fediv\fP >::no_div_by_0"

.SS "template<typename T > T \fBNumRepr::auxiliary_types::resbinop_t\fP< T, \fBbinop_e::fediv\fP >::quotient"

.SS "template<typename T > T \fBNumRepr::auxiliary_types::resbinop_t\fP< T, \fBbinop_e::fediv\fP >::remainder"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
