.TH "NumRepr::char_type" 3 "Martes, 29 de Noviembre de 2022" "Version 0.8" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::char_type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SH "Concept definition"
.PP 
.nf
template<typename CharT>
concept NumRepr::char_type =  std::is_same_v<CharT,char>                                                ||
                                                                                std::is_same_v<CharT,signed char>               ||
                                                                                std::is_same_v<CharT,unsigned char>     ||
                                                                                std::is_same_v<CharT,wchar_t>
.fi
.SH "Descripción detallada"
.PP 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
