.TH "NumRepr::arith_natural_c" 3 "Martes, 29 de Noviembre de 2022" "Version 0.8" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::arith_natural_c
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <basic_types\&.hpp>\fP
.SH "Concept definition"
.PP 
.nf
template<typename NatIntT>
concept NumRepr::arith_natural_c =    std::is_arithmetic_v<NatIntT>   &&
                                                    std::is_unsigned_v<NatIntT>     &&
                                                        std::is_integral_v<NatIntT>
.fi
.SH "Descripción detallada"
.PP 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
