.TH "NumRepr::auxiliary_types::resbinop_t< T, binop_e::sub >" 3 "Martes, 29 de Noviembre de 2022" "Version 0.8" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumRepr::auxiliary_types::resbinop_t< T, binop_e::sub >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <auxiliary_types\&.hpp>\fP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "T \fBcontent\fP"
.br
.ti -1c
.RI "T \fBborrow\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T>
.br
struct NumRepr::auxiliary_types::resbinop_t< T, binop_e::sub >"
.SH "Documentación de los datos miembro"
.PP 
.SS "template<typename T > T \fBNumRepr::auxiliary_types::resbinop_t\fP< T, \fBbinop_e::sub\fP >::borrow"

.SS "template<typename T > T \fBNumRepr::auxiliary_types::resbinop_t\fP< T, \fBbinop_e::sub\fP >::content"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
