.TH "utilities" 3 "Martes, 29 de Noviembre de 2022" "Version 0.8" "NumericRepresentations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utilities
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBfor_each_same_type\fP"
.br
.ti -1c
.RI "struct \fBfor_each_same_type< Head_t >\fP"
.br
.ti -1c
.RI "struct \fBlocal_void_t\fP"
.br
.ti -1c
.RI "struct \fBpack2array\fP"
.br
.RI "END: TEMPLATE GENERICO Y SUS ESPECIALIZACIONES\&. "
.ti -1c
.RI "struct \fBpack2tuple\fP"
.br
.in -1c
.SS "Concepts"

.in +1c
.ti -1c
.RI "concept \fBall_are_the_same_type\fP"
.br
.ti -1c
.RI "concept \fBall_are_more_than_zero\fP"
.br
.in -1c
.SS "typedefs"

.in +1c
.ti -1c
.RI "template<\fBNumRepr::type_traits::unsigned_integral_c\fP UINT_T> using \fBuintspair\fP = typename std::array< UINT_T, 2 >"
.br
.ti -1c
.RI "template<\fBNumRepr::type_traits::unsigned_integral_c\fP UINT_T, UINT_T B> using \fBuintspairlist\fP = typename std::array< \fBuintspair\fP< UINT_T >, B >"
.br
.ti -1c
.RI "template<\fBNumRepr::type_traits::unsigned_integral_c\fP UINT_T, UINT_T B> using \fBuintspairtbl\fP = typename std::array< \fBuintspairlist\fP< UINT_T, B >, B >"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "template<class\&.\&.\&. Ts> 
.br
requires ( all_are_the_same_type<Ts\&.\&.\&.> && all_are_more_than_zero<Ts\&.\&.\&.> )void \fBassign_with_order\fP (auto &dest, const Ts &\&.\&.\&. args) noexcept"
.br
.in -1c
.SH "Documentación de los 'typedefs'"
.PP 
.SS "template<\fBNumRepr::type_traits::unsigned_integral_c\fP UINT_T> using \fButilities::uintspair\fP = typedef typename std::array<UINT_T,2>"

.SS "template<\fBNumRepr::type_traits::unsigned_integral_c\fP UINT_T, UINT_T B> using \fButilities::uintspairlist\fP = typedef typename std::array<\fBuintspair\fP<UINT_T>,B>"

.SS "template<\fBNumRepr::type_traits::unsigned_integral_c\fP UINT_T, UINT_T B> using \fButilities::uintspairtbl\fP = typedef typename std::array<\fBuintspairlist\fP<UINT_T,B>,B>"

.SH "Documentación de las funciones"
.PP 
.SS "template<class\&.\&.\&. Ts> 
.br
requires ( all_are_the_same_type<Ts\&.\&.\&.> && all_are_more_than_zero<Ts\&.\&.\&.> )void utilities::assign_with_order (auto & dest, const Ts &\&.\&.\&. args)\fC [noexcept]\fP"

.PP
.nf
158 {
159         pack2array<Ts\&.\&.\&.>::for_each(dest,args\&.\&.\&.);
160         return;
161 }
.fi
.PP
Hace referencia a \fButilities::pack2array< Ts >::for_each()\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para NumericRepresentations del código fuente\&.
