var annotated_dup =
[
    [ "details", null, [
      [ "cp_delete", "structdetails_1_1cp__delete.html", null ],
      [ "cp_delete< 0u >", "structdetails_1_1cp__delete_3_010u_01_4.html", null ],
      [ "cp_delete< 1u >", "structdetails_1_1cp__delete_3_011u_01_4.html", null ],
      [ "cp_delete< 2u >", "structdetails_1_1cp__delete_3_012u_01_4.html", null ],
      [ "cp_delete< aT, T, std::numeric_limits< uchint >::max()>", "structdetails_1_1cp__delete_3_01a_t_00_01_t_00_01std_1_1numeric__limits_3_01uchint_01_4_1_1max_07_08_4.html", null ],
      [ "cp_new", "structdetails_1_1cp__new.html", null ],
      [ "cp_new< 0u >", "structdetails_1_1cp__new_3_010u_01_4.html", null ],
      [ "cp_new< 1u >", "structdetails_1_1cp__new_3_011u_01_4.html", null ],
      [ "cp_new< 2 >", "structdetails_1_1cp__new_3_012_01_4.html", null ],
      [ "cp_new< aT, T, std::numeric_limits< uchint >::max()>", "structdetails_1_1cp__new_3_01a_t_00_01_t_00_01std_1_1numeric__limits_3_01uchint_01_4_1_1max_07_08_4.html", null ]
    ] ],
    [ "NumRepr", null, [
      [ "auxiliary_types", null, [
        [ "resbinop_t", "struct_num_repr_1_1auxiliary__types_1_1resbinop__t.html", null ],
        [ "resbinop_t< T, binop_e::add >", "struct_num_repr_1_1auxiliary__types_1_1resbinop__t_3_01_t_00_01binop__e_1_1add_01_4.html", null ],
        [ "resbinop_t< T, binop_e::div >", "struct_num_repr_1_1auxiliary__types_1_1resbinop__t_3_01_t_00_01binop__e_1_1div_01_4.html", null ],
        [ "resbinop_t< T, binop_e::fediv >", "struct_num_repr_1_1auxiliary__types_1_1resbinop__t_3_01_t_00_01binop__e_1_1fediv_01_4.html", null ],
        [ "resbinop_t< T, binop_e::mult >", "struct_num_repr_1_1auxiliary__types_1_1resbinop__t_3_01_t_00_01binop__e_1_1mult_01_4.html", null ],
        [ "resbinop_t< T, binop_e::rem >", "struct_num_repr_1_1auxiliary__types_1_1resbinop__t_3_01_t_00_01binop__e_1_1rem_01_4.html", null ],
        [ "resbinop_t< T, binop_e::sub >", "struct_num_repr_1_1auxiliary__types_1_1resbinop__t_3_01_t_00_01binop__e_1_1sub_01_4.html", null ],
        [ "result_operation_t", "struct_num_repr_1_1auxiliary__types_1_1result__operation__t.html", null ],
        [ "result_operation_t< T, binop_e::add, N >", "struct_num_repr_1_1auxiliary__types_1_1result__operation__t_3_01_t_00_01binop__e_1_1add_00_01_n_01_4.html", null ],
        [ "result_operation_t< T, binop_e::div, N >", "struct_num_repr_1_1auxiliary__types_1_1result__operation__t_3_01_t_00_01binop__e_1_1div_00_01_n_01_4.html", null ],
        [ "result_operation_t< T, binop_e::fediv, N >", "struct_num_repr_1_1auxiliary__types_1_1result__operation__t_3_01_t_00_01binop__e_1_1fediv_00_01_n_01_4.html", null ],
        [ "result_operation_t< T, binop_e::mult, N >", "struct_num_repr_1_1auxiliary__types_1_1result__operation__t_3_01_t_00_01binop__e_1_1mult_00_01_n_01_4.html", null ],
        [ "result_operation_t< T, binop_e::rem, N >", "struct_num_repr_1_1auxiliary__types_1_1result__operation__t_3_01_t_00_01binop__e_1_1rem_00_01_n_01_4.html", null ],
        [ "result_operation_t< T, binop_e::sub, N >", "struct_num_repr_1_1auxiliary__types_1_1result__operation__t_3_01_t_00_01binop__e_1_1sub_00_01_n_01_4.html", null ]
      ] ],
      [ "type_traits", null, [
        [ "detail", "namespace_num_repr_1_1type__traits_1_1detail.html", [
          [ "__sig_SInt_for_SInt_t", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___s_int__for___s_int__t.html", null ],
          [ "__sig_SInt_for_SInt_t< char >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___s_int__for___s_int__t_3_01char_01_4.html", null ],
          [ "__sig_SInt_for_SInt_t< signed char >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___s_int__for___s_int__t_3_01signed_01char_01_4.html", null ],
          [ "__sig_SInt_for_SInt_t< signed int >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___s_int__for___s_int__t_3_01signed_01int_01_4.html", null ],
          [ "__sig_SInt_for_SInt_t< signed long int >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___s_int__for___s_int__t_3_01signed_01long_01int_01_4.html", null ],
          [ "__sig_SInt_for_SInt_t< signed long long int >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___s_int__for___s_int__t_3_01signed_01long_01long_01int_01_4.html", null ],
          [ "__sig_SInt_for_SInt_t< signed short int >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___s_int__for___s_int__t_3_01signed_01short_01int_01_4.html", null ],
          [ "__sig_SInt_for_UInt_t", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___s_int__for___u_int__t.html", null ],
          [ "__sig_SInt_for_UInt_t< unsigned char >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___s_int__for___u_int__t_3_01unsigned_01char_01_4.html", null ],
          [ "__sig_SInt_for_UInt_t< unsigned int >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___s_int__for___u_int__t_3_01unsigned_01int_01_4.html", null ],
          [ "__sig_SInt_for_UInt_t< unsigned long int >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___s_int__for___u_int__t_3_01unsigned_01long_01int_01_4.html", null ],
          [ "__sig_SInt_for_UInt_t< unsigned long long int >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___s_int__for___u_int__t_3_01unsigned_01long_01long_01int_01_4.html", null ],
          [ "__sig_SInt_for_UInt_t< unsigned short int >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___s_int__for___u_int__t_3_01unsigned_01short_01int_01_4.html", null ],
          [ "__sig_UInt_for_SInt_t", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___u_int__for___s_int__t.html", null ],
          [ "__sig_UInt_for_SInt_t< char >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___u_int__for___s_int__t_3_01char_01_4.html", null ],
          [ "__sig_UInt_for_SInt_t< signed char >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___u_int__for___s_int__t_3_01signed_01char_01_4.html", null ],
          [ "__sig_UInt_for_SInt_t< signed int >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___u_int__for___s_int__t_3_01signed_01int_01_4.html", null ],
          [ "__sig_UInt_for_SInt_t< signed long int >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___u_int__for___s_int__t_3_01signed_01long_01int_01_4.html", null ],
          [ "__sig_UInt_for_SInt_t< signed long long int >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___u_int__for___s_int__t_3_01signed_01long_01long_01int_01_4.html", null ],
          [ "__sig_UInt_for_SInt_t< signed short int >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___u_int__for___s_int__t_3_01signed_01short_01int_01_4.html", null ],
          [ "__sig_UInt_for_SInt_t< sint128_t >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___u_int__for___s_int__t_3_01sint128__t_01_4.html", null ],
          [ "__sig_UInt_for_UInt_t", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___u_int__for___u_int__t.html", null ],
          [ "__sig_UInt_for_UInt_t< unsigned char >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___u_int__for___u_int__t_3_01unsigned_01char_01_4.html", null ],
          [ "__sig_UInt_for_UInt_t< unsigned int >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___u_int__for___u_int__t_3_01unsigned_01int_01_4.html", null ],
          [ "__sig_UInt_for_UInt_t< unsigned long int >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___u_int__for___u_int__t_3_01unsigned_01long_01int_01_4.html", null ],
          [ "__sig_UInt_for_UInt_t< unsigned long long int >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___u_int__for___u_int__t_3_01unsigned_01long_01long_01int_01_4.html", null ],
          [ "__sig_UInt_for_UInt_t< unsigned short int >", "struct_num_repr_1_1type__traits_1_1detail_1_1____sig___u_int__for___u_int__t_3_01unsigned_01short_01int_01_4.html", null ]
        ] ],
        [ "empty_type", "struct_num_repr_1_1type__traits_1_1empty__type.html", null ],
        [ "is_signed_sz_gt", "struct_num_repr_1_1type__traits_1_1is__signed__sz__gt.html", null ],
        [ "is_unsigned_sz_gt", "struct_num_repr_1_1type__traits_1_1is__unsigned__sz__gt.html", null ],
        [ "UIntTypeForRadix", "struct_num_repr_1_1type__traits_1_1_u_int_type_for_radix.html", null ],
        [ "UIntTypeForRadix< int64_t, Radix >", "struct_num_repr_1_1type__traits_1_1_u_int_type_for_radix_3_01int64__t_00_01_radix_01_4.html", null ],
        [ "UIntTypeForRadix< sint16_t, Radix >", "struct_num_repr_1_1type__traits_1_1_u_int_type_for_radix_3_01sint16__t_00_01_radix_01_4.html", null ],
        [ "UIntTypeForRadix< sint32_t, Radix >", "struct_num_repr_1_1type__traits_1_1_u_int_type_for_radix_3_01sint32__t_00_01_radix_01_4.html", null ],
        [ "UIntTypeForRadix< sint8_t, Radix >", "struct_num_repr_1_1type__traits_1_1_u_int_type_for_radix_3_01sint8__t_00_01_radix_01_4.html", null ],
        [ "UIntTypeForRadix< uint128_t, Radix >", "struct_num_repr_1_1type__traits_1_1_u_int_type_for_radix_3_01uint128__t_00_01_radix_01_4.html", null ],
        [ "UIntTypeForRadix< uint16_t, Radix >", "struct_num_repr_1_1type__traits_1_1_u_int_type_for_radix_3_01uint16__t_00_01_radix_01_4.html", null ],
        [ "UIntTypeForRadix< uint32_t, Radix >", "struct_num_repr_1_1type__traits_1_1_u_int_type_for_radix_3_01uint32__t_00_01_radix_01_4.html", null ],
        [ "UIntTypeForRadix< uint64_t, Radix >", "struct_num_repr_1_1type__traits_1_1_u_int_type_for_radix_3_01uint64__t_00_01_radix_01_4.html", null ],
        [ "UIntTypeForRadix< uint8_t, Radix >", "struct_num_repr_1_1type__traits_1_1_u_int_type_for_radix_3_01uint8__t_00_01_radix_01_4.html", null ]
      ] ],
      [ "base_num_t", "struct_num_repr_1_1base__num__t.html", null ],
      [ "dig_t", "struct_num_repr_1_1dig__t.html", "struct_num_repr_1_1dig__t" ],
      [ "nat_rat_fixed_reg_t", "struct_num_repr_1_1nat__rat__fixed__reg__t.html", "struct_num_repr_1_1nat__rat__fixed__reg__t" ],
      [ "nat_reg_digs_t", "struct_num_repr_1_1nat__reg__digs__t.html", "struct_num_repr_1_1nat__reg__digs__t" ],
      [ "reg_digs_t", "struct_num_repr_1_1reg__digs__t.html", "struct_num_repr_1_1reg__digs__t" ]
    ] ],
    [ "utilities", null, [
      [ "for_each_same_type", "structutilities_1_1for__each__same__type.html", null ],
      [ "for_each_same_type< Head_t >", "structutilities_1_1for__each__same__type_3_01_head__t_01_4.html", null ],
      [ "local_void_t", "structutilities_1_1local__void__t.html", null ],
      [ "pack2array", "structutilities_1_1pack2array.html", null ],
      [ "pack2tuple", "structutilities_1_1pack2tuple.html", null ]
    ] ],
    [ "func_refvar_t", "classfunc__refvar__t.html", null ],
    [ "func_refvar_t< INT **, INT *, INT >", "classfunc__refvar__t_3_01_i_n_t_01_5_5_00_01_i_n_t_01_5_00_01_i_n_t_01_4.html", null ],
    [ "func_refvar_t< UINT **, UINT *, UINT >", "classfunc__refvar__t_3_01_u_i_n_t_01_5_5_00_01_u_i_n_t_01_5_00_01_u_i_n_t_01_4.html", null ],
    [ "int_num_t", "structint__num__t.html", null ],
    [ "nat_num_t", "classnat__num__t.html", null ]
];